project:
  type: website
  output-dir: docs

website:
  title: "Nossa Língua"
  favicon: favicon.ico
  navbar:
    right:
      - sobre.qmd
      - todas-edicoes.qmd
      - textos.qmd
      - icon: instagram
        href: https://instagram.com/revistanossalingua
  twitter-card: true
  site-url: https://nossa-lingua.github.io
  open-graph: true
  google-analytics: G-F1B8E57YRL
  page-navigation: true
  sidebar:
    contents:
      - section: "A"
        contents:
          - section: Edições
            contents:
              - href: edicao/01/index.qmd
              - href: edicao/02/index.qmd
              - href: edicao/03/index.qmd
          - section: Edição 3
            contents:
                - edicao/03/index.qmd
                - edicao/03/textos/revolve.qmd
                - edicao/03/textos/paroxitona-sete-letras.qmd
                - edicao/03/textos/conselho-de-vo.qmd
                - edicao/03/textos/lilas.qmd
                - edicao/03/textos/naufrago.qmd
                - edicao/03/textos/baile.qmd
                - edicao/03/textos/cigarros.qmd
                - edicao/03/textos/reconhecenca.qmd
                - edicao/03/textos/do-que-antes.qmd
                - edicao/03/textos/biblioteca.qmd
                - edicao/03/textos/dedicatorias.qmd
                - edicao/03/textos/como-vai.qmd
                - edicao/03/textos/bichinho-virtual.qmd
                - edicao/03/textos/grilo.qmd
          - section: Edição 4
            contents:
                - edicao/04/index.qmd
                - edicao/04/textos/brasa.qmd
                - edicao/04/textos/29-04-2022.qmd
                - edicao/04/textos/ngiyakuthanda.qmd
                - edicao/04/textos/os-astros-o-sol.qmd
                - edicao/04/textos/nu-inacabado.qmd
                - edicao/04/textos/desramo.qmd
                - edicao/04/textos/sua-cidade.qmd
                - edicao/04/textos/adagas.qmd
                - edicao/04/textos/chama-fria.qmd
                - edicao/04/textos/as-faces-do-amor.qmd
                - edicao/04/textos/interludio.qmd
                - edicao/04/textos/o-amor.qmd
                - edicao/04/textos/retenha-me.qmd
                - edicao/04/textos/sininho-de-belem.qmd
                - edicao/04/textos/amor.qmd
                - edicao/04/textos/ainda-sobre-voce.qmd
                - edicao/04/textos/notas-sobre-o-amor.qmd
                - edicao/04/textos/a-historia-de-quem-me-traiu.qmd
                - edicao/04/textos/amar-verbo-proibido.qmd
                - edicao/04/textos/o-sul-da-italia.qmd
          - section: Edição 5
            contents:
                - edicao/05/index.qmd
                - edicao/05/textos/devasso.qmd
                - edicao/05/textos/(;).qmd
                - edicao/05/textos/nos.qmd
                - edicao/05/textos/crisma.qmd
                - edicao/05/textos/seu-rosto-uma-pintura.qmd
                - edicao/05/textos/febre.qmd
                - edicao/05/textos/canto-da-sereia.qmd
                - edicao/05/textos/rapto-da-razao.qmd
                - edicao/05/textos/meu-antinoo.qmd
                - edicao/05/textos/barbie.qmd
          - section: Edição 6
            contents:
                - edicao/06/index.qmd
                - edicao/06/textos/se.qmd
                - edicao/06/textos/coracao-de-sereia.qmd
                - edicao/06/textos/tchau-tchau-passarinho.qmd
                - edicao/06/textos/mediacao.qmd
                - edicao/06/textos/mergulho.qmd
                - edicao/06/textos/relacoes-alcoolicas.qmd
                - edicao/06/textos/diario-de-um-aluno.qmd
                - edicao/06/textos/romaria-a-sao-paulo.qmd
                - edicao/06/textos/na-hora-do-bandeco.qmd
                - edicao/06/textos/feitico.qmd
                - edicao/06/textos/lembrar-de-alguem.qmd
                - edicao/06/textos/-.qmd
                - edicao/06/textos/dia-12.qmd
                - edicao/06/textos/identidade.qmd
          - section: Edição 7
            contents:
              - edicao/07/index.qmd
              - edicao/07/textos/o-que-te-revolta.qmd
              - edicao/07/textos/o-poema.qmd
              - edicao/07/textos/nois-contra-eles.qmd
              - edicao/07/textos/hora-extra.qmd
              - edicao/07/textos/o-shea-sibley.qmd
              - edicao/07/textos/nos-por-noiz.qmd
              - edicao/07/textos/--.qmd
              - edicao/07/textos/cronica-de-uma-paulistana-falsa.qmd
              - edicao/07/textos/tunel-do-tempo.qmd
          - section: Edição 8
            contents:
                - edicao/08/index.qmd
                - edicao/08/textos/prusten.qmd
                - edicao/08/textos/sexta-feira-13.qmd
                - edicao/08/textos/o-gato.qmd
                - edicao/08/textos/devir.qmd
                - edicao/08/textos/paredes-de-papel.qmd
                - edicao/08/textos/funeral.qmd
                - edicao/08/textos/maria-augusta.qmd
                - edicao/08/textos/medo.qmd
                - edicao/08/textos/arranca-ossos.qmd
                - edicao/08/textos/o-hereditario.qmd
                - edicao/08/textos/--.qmd
                - edicao/08/textos/---.qmd
          - section: Edição 9
            contents:
                - edicao/09/index.qmd
                - edicao/09/textos/ostras-mangas-pepecas.qmd
                - edicao/09/textos/astros.qmd
                - edicao/09/textos/michel-foucault-enigma.qmd
                - edicao/09/textos/resenha-glicerideos.qmd
                - edicao/09/textos/companion-of-disquiet.qmd
                - edicao/09/textos/a-mosca.qmd
          - section: Edição 10
            contents:
                - edicao/10/index.qmd
                - edicao/10/textos/borbulhas.qmd
                - edicao/10/textos/alien-do-passado.qmd
                - edicao/10/textos/qual-a-chance.qmd
                - edicao/10/textos/nao-e-pra-isso.qmd
                - edicao/10/textos/futuro-do-preterito.qmd
                - edicao/10/textos/daqui-a-dez-anos.qmd
                - edicao/10/textos/o-problema-das-formigas.qmd
                - edicao/10/textos/sol.qmd
                - edicao/10/textos/promessas.qmd
                - edicao/10/textos/09-06.qmd
                - edicao/10/textos/e-uma-pena.qmd
          - section: Edição 11
            contents:
                - edicao/11/index.qmd
                - edicao/11/textos/impureza.qmd
                - edicao/11/textos/hungry.qmd
                - edicao/11/textos/tenho-fome-de.qmd
                - edicao/11/textos/banquete-do-tempo.qmd
                - edicao/11/textos/restaurante.qmd
                - edicao/11/textos/a-boba.qmd
          - section: Edição 12
            contents: 
                - edicao/12/index.qmd
                - edicao/12/textos/chuva.qmd
                - edicao/12/textos/isso-nao-e-autoficcao.qmd
                - edicao/12/textos/transformacao-merecida.qmd
                - edicao/12/textos/minitratado-sobre-falsidade.qmd
                - edicao/12/textos/sangue-falso.qmd
                - edicao/12/textos/bebida-salpicada-de-mentira.qmd
                - edicao/12/textos/o-grande-ego.qmd
          - section: Edição 13
            contents:
                - edicao/13/index.qmd
                - edicao/13/textos/nao-quero-fazer.qmd
                - edicao/13/textos/se-me-canso-pingo.qmd
                - edicao/13/textos/sombra-da-preguica.qmd
                - edicao/13/textos/a-cegonha.qmd
                - edicao/13/textos/a-preguica-entre.qmd
          - section: Edição 14
            contents:
                - edicao/14/index.qmd
                - edicao/14/textos/caos-e-cosmos.qmd
                - edicao/14/textos/efeito-ipanema.qmd
                - edicao/14/textos/pedaco-de-pecado.qmd
                - edicao/14/textos/pele-e-carne.qmd
                - edicao/14/textos/sede-noturna.qmd
                - edicao/14/textos/gabriela.qmd
                - edicao/14/textos/reflexao-sobre-luxuria.qmd
          - section: Edição 15
            contents:
                - edicao/15/index.qmd
                - edicao/15/textos/com-amor-a-burguesia.qmd
                - edicao/15/textos/avessa-avareza.qmd
                - edicao/15/textos/linha-ouro.qmd
          - section: Edição 16
            contents:
                - edicao/16/index.html
                - edicao/16/textos/endogeno.qmd
                - edicao/16/textos/campampante.qmd
                - edicao/16/textos/tia-auxiliadora-responde.qmd
                - edicao/16/textos/presenca.qmd
                - edicao/16/textos/indiferenca.qmd
                - edicao/16/textos/tem-um-lugar-pra-mim.qmd
          - section: Edição 17
            contents:
                - edicao/17/index.qmd
                - edicao/17/textos/incolume-soberba.qmd
                - edicao/17/textos/meditacao.qmd
          - section: Edição 18
            contents:
                - edicao/18/index.qmd
                - edicao/18/textos/o-tal-retorno.qmd
                - edicao/18/textos/origami.qmd
                - edicao/18/textos/desproporcao.qmd
                - edicao/18/textos/caspita.qmd
              

format:
  html:
    theme: 
      light:
        - cosmo
        - custom.scss
      dark: 
        - darkly
        - custom.scss
    css: styles.css
    lang: pt
    toc: true
    toc-location: left
    toc-title: Nesta edição
    mainfont: 'Roboto Slab'
    language:
      title-block-published: " "
      title-block-author-single: "POR"
  

