project:
  type: website
  output-dir: docs

website:
  title: "Nossa Língua"
  navbar:
    right:
      - sobre.qmd
      - icon: instagram
        href: https://instagram.com/nossalingualetras
  twitter-card: true
  site-url: https://nossa-lingua.github.io
  open-graph: true

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    lang: pt
    toc: true
    toc-location: left
    toc-title: Nesta edição
    mainfont: 'Roboto Slab'
    language:
      title-block-published: " "
      
editor: visual

