---
title: '09.06'
author: 
  - name: "Gabriella Menezes Soares"
---

Quase 4 da manhã – casa do ****** e da *****

| Primeiramente gostaria de ressaltar que está sendo um prazer escrever isso deitada num quarto vendo gatos comerem.
| -------------> essa caneta é muito boa!
| Pontuados estes aspectos, irei à motivação da escrita:
| A falta de finitude do processo de amadurecimento.
| Recentemente houveram situações que me causaram mudanças, na verdade não posso usar do pretérito pois ainda estão ocorrendo e permanecerão assim após essa escrita.
| (Isso é um pequeno recorte do tempo espaço)
| O amadurecimento não é um processo que se pode encerrar.
| Sou naturalmente egoísta, tanto que essa conexão não faz sentido a qualquer outra pessoa sem a devida explicação.
| Não posso considerar um encerramento do amadurecer pois automaticamente isso me torna estática e inalterável.
| Morta.
| Eu persegui a morte como uma explicação, se a finitude é plena posso então relaxar pois a partir daí tudo se torna previsível.
| Não foram apenas 40mg de fluoxetina que me fizeram perceber que não estava dando realmente certo.
| Apenas o ato físico de morrer é finito e nem mesmo assim pode-se dizer que há alguma inalteração da percepção do indivíduo morto, pq o espectador está sempre em alteração por consequência de encontros.
| Não há delimitação do pensamento, dito isso posso entender pq normalmente me é muito mais cômodo pensar que escrever. Colocar em palavras limitaria meu pensamento e consequentemente me tiraria o direito de mudar.
| Nesse momento é isso,
|   amanhã vai ser?
|   tem que ser?
| A alteração é inconstância e por assim o ser também se tornaria inconfiável.
| Quem quer ser uma pessoa que não se pode confiar?
|  mas de fato é isso?
| Nunca quis aprender uma série de coisas, principalmente a lidar com o meu egoísmo (não estou fazendo juízo de valor).
| Sempre me considerei uma série de coisas e todas as vezes que me deparei com o fato dessas "percepções" não fazerem mais sentido a realidade vigente, eu suprimi a mudança por meio do que isso me tornaria.
| É como ler o mesmo capítulo sempre pq não se pode lidar com a imprevisibilidade.
| Novamente: falta de controle.
| 
| Quero me confortar com o não saber.
| Escolher fazer algo é automaticamente tomar uma decisão, mas seria o fim?
| De fato as consequências vem...mas o depois também.
| Me "anular" de dizer/interagir/pensar/fazer/escrever algo não me torna nada além de covarde.
| Pensar que minhas atitudes não vão gerar qualquer tipo de consequência é infantil.
| 
| Ação e Reação - ? 
|                                    algo que vc vai conseguir lidar
| 
| Não errar é não aprender 
| Não aprender é não errar.
| Não mudar é não se permitir crescer (e lidar com isso)
| Assuma as consequências das suas ações sabendo que as possibilidades são infinitas.
| Estático ou Movimento?
| Não quero dizer que sei o que vai acontecer.
| Poderia dizer que vou sobreviver...mas se eu morrer? 
| Isso importa?
| O cumprimento da morte vai lhe alcançar
| mas e depois?
| Eu não quero saber.
| Hoje estou  
|                        não sou
|                                          eu não posso ser.
| 
| Para os covardes!
