---
title: 'Borbulhas'
author: 
  - name: "Rodrigo Adriano Machado"
---

<p style="text-align:right; text-style:italic">
Une seule chose importe: apprendre à être perdant.
</p>
<p style="text-align:right; text-style:italic">
E.M. Cioran
</p>

Eu estava sem dinheiro para o final de ano, com trabalhos atrasados por fazer e principalmente achando que as forças do universo conspiravam contra mim. Não é que pareça muito chato mimetizar um personagem de Dostoiévski, nada disso; a farpa alojada nas ideias dizia que não foram exatamente essas as expectativas para ganhar São Paulo. Aqui entre nós, um lugar com nome de santo suspeitojamais poderia dar certo.

Enquanto encarava ela por cima da mesa do bar — ela sorrindo com dentes pequenos de criança ingênua —, o vento e a chuva derrubaram uma moto estacionada na rua. A situação desviou a introspecção, um garçom serviu outra dose de wisky para a garota e eu acendi o cigarro.

| — Estou me sentindo velho... — Resmunguei.
| — Isso é bobagem, Adriano. — Cristiane respondeu mexendo nos cabelos cacheados, curtos — Acho que estou começando a ficar bêbada... É divertido. Tudo parece mais alegrinho.

Queria saber o que dizer, mas constato que minhas palavras chegaram ao fim, exatamente como nosso namoro horroroso. Trata-se do elemento perlocucionário, dizem os linguistas. Engraçado como anos de intimidades — repentinamente — cavam com os pés um abismo de estranheza. Mostrei os dentes e a observei do jeito que se nota uma pessoa nada familiar puxando assunto na fila do ônibus.

| — Sim... Tudo parece mais alegrinho.

<p style="text-align:center">*</p>

Enquanto lavava a roupa, meditava. Tocou uma música do The Strokes no vizinho. Meu inglês limitadíssimo fez com que entendesse versos. Insistentemente era cantado que “É isso?... Não somos inimigos, apenas discordamos”. Lembrei de tirar o lixo e corri com sacolas pelas escadas do apartamento até a rua. A chuva parou. Talvez o amor seja tipo a chuva imprevisível de São Paulo. O santo que mente demais sua importância. 

Às vezes eu só queria ser um peixe, mesmo correndo o risco do Fagner escrever uma canção. Outra coisa é a cafeteria “cult” colocando o lixo no meu lado da lixeira. Entendo coisas bem complexas, o cálculo de aceleração de queda dos corpos em Isaac Newton; mas isso — “isso” estou chamando a mania dos funcionários da cafeteria de me achar mais sujo do que eles... — me escapa. Nesses momentos, para evitar ressentimentos, imagino a cafeteria pegando fogo. O coração fica quentinho. 

Como nem só de economia, músicas do The strokes, imaginar cafeterias em chamas, se vive a vida; voltei ao meu apartamento para terminar de lavar as roupas. Não estar fedido deve ajudar em algo, concluo.

<p style="text-align:center">*</p>

Nem tudo está perdido, eu acho. Por exemplo, eu não tenho nariz de rato, barba suja tapando um queixo fino, princípio de calvície disfarçado com uma boina, um pinguim de geladeira tatuado na perna, tampouco apelido no diminutivo que lembra codinome para órgão genital. Isso significa que ainda tenho uma chance de melhorar na vida.

Depois de passar uma boa parte da tarde transando com Cristiane e ouvindo suas frases de despedida, fico pensando quantas pessoas no mundo tiveram a oportunidade de um prazer fúnebre ao trepar durante um velório.

| — No que está pensando, Adriano?
| — Em arranjar uma filha para postar fotos nas redes sociais e atrair mulheres com crises familiares.
| — Mentiroso! — Ela ri, mas não gosta. — Eu acho que você deveria parar de ser tão crítico.
| — Isso me parece muito crítico... Não sei se estou preparado para uma reflexão dessas após o terceiro orgasmo. 

Cristiane ajeita os cabelos na frente do ventilador para se refrescar. Não sei se pensa no que falei ou ignora. Vou na segunda opção. Será que pensou que acabou de trair o novo afeto com o ex? Observo a maneira como se movimenta procurando algo para prender os cabelos, elogio seu corpo enquanto se espreguiça e ela elogia o meu. Clichê fofo. Ela vai ao banheiro e eu recolho pensamentos no teto do quarto. Rapaz, coitado do ‘Cleitin’. Tomara que nunca saiba sobre hoje. Amém.

<p style="text-align:center">*</p>

Depois só sei afogar minhas mágoas no jeito dos velhos cães que fuçam no lixo mais por tédio do que qualquer outra invenção da psicanálise — perdão, Jacques Lacan e companhia. Se tiver um lugar para fechar a porta e deixar as coisas lá fora, algo para rabiscar frases razoáveis, a mágica acontece. Todo mundo sabe que quando Raduan Nassar resolveu parar, a expectativa era se extraviar abraçado no pedaço de navio naufragado chamado literatura. Antes fossemos peixes, né Fagner? Também não deu.

Calcei as botinas velhas e aprumei o chapéu na minha cabeça indigena. A corrente presa no lado esquerdo da calça preta. Olhei no espelho se os brincos de argola brilhavam na cor da faca para contrastar a pele negra. Sim. Graças a isso tudo ficará bem.

> Rodrigo Adriano Machado, mestre em Filosofia (PUC-SP), escritor com alguns prêmios literários, guitarrista e vocalista no projeto Os Belos Cães Cantores. 

| \@reles.escritor <a href="https://instagram.com/reles.escritor"><i class="bi bi-instagram"></i></a>
| \@rodrigoadrianomachado <a href="https://instagram.com/rodrigoadrianomachado"><i class="bi bi-instagram"></i></a>
| \@osbeloscaescantores <a href="https://instagram.com/osbeloscaescantores"><i class="bi bi-instagram"></i></a>
