---
title: É uma pena
author:
- name: Giovanna Sabino
categories:
- LÍRICO

---

“É uma pena... É verdadeiramente uma pena...”

| É o que se arrasta pelas paredes e vãos da minha cabeça todas as noites quando me olho no espelho e vejo o retrato de tudo aquilo que eu poderia ter sido.
| Não fui, entretanto.
| Não fui pros outros? Não importa, não fui pra mim.
| Queria ter sido grande, queria ter feito os olhos da minha mãe brilharem e meu falecido pai se orgulhar queria ter feito os professores sobressaltarem da cadeira tamanho o meu talento queria queria queria... queria
| Eu queria isso tudo... queria pra esconder que nem mesmo todos os prêmios, nem todo o reconhecimento do mundo vai me fazer cruzar a linha que eu mesma desenhei - e desenhei só pra mim -
| Quanto mais peregrino, menos parece que eu fiz e se fiz é patético
| Ah... tudo é tão patético, sobreviver é patético, a faculdade é patética, esse texto é patético...
| Nada, nada nunca vai ser bom e eu nunca vou poder vencer nada enquanto eu mesma for minha carrasca e juíza.
| É, de fato é uma pena... porque eu -tola- nunca vou ser tudo o que minha mentezinha parasita planejou para mim.
| Essa linha de chegada não é visível e eu, tão jovem, já não aguento mais correr.
| É uma pena...

<a href="https://instagram.com/forlissies"><i class="bi bi-instagram"></i></a>

