---
title: 'O problema das formigas'
author: 
  - name: "Brunno R. Sousa"
---

Sabe, ultimamente eu tenho tido um problema com formigas, eu tenho uma mesa relativamente grande, eu diria que até grande demais, e essas malditas criaturinhas conseguem aparecer e se enfiar em cada micro espaço existente dela, e isso tem me tirado do sério. Eu acredito ser uma pessoa paciente, no sentido de que, caso acontecesse só uma ou duas vezes, com uma ou duas formigas, eu estaria bem, porém não estou! Todos os dias, pelo menos algumas vezes, vejo elas fazendo um pequeno rebuliço em algum dos cantos daqui e fico sem saber o que fazer, vou matá-las? Não! Não causaram diretamente mal algum, mas também não posso deixá-las aqui me atrapalhando. Não consigo removê-las da mesa com delicadeza o suficiente que não as machuque, mas não suporto que simplesmente fiquem aqui. Acredito que seja culpa minha. 

Há um tempo atrás resolvi mudar um pouco as coisas de lugar na minha mesa, removi alguns pesos que estavam me causando problemas, joguei fora diversas inutilidades e memórias que já não me serviam mais, coloquei em quadros momentos de maravilha, organizei tudo o que precisava, me senti mais confortável, tendo melhor proveito da minha vida, digo, mesa. Mas aí então as formigas começaram a aparecer, esses problemas minúsculos e verdadeiramente insignificantes que têm um significado e poder enorme sobre mim! Não sei ao certo se mudar as coisas de lugar e tentar reiniciar o meu status enquanto... dono de uma mesa, deu a esses incômodos abertura o suficiente para que passassem pro outro lado, não sei se me libertar desses outros alvoroços que por muito tempo machucaram minhas costas com suas inconstâncias funcionais me provou forte o bastante para lidar com a sutil e enraivecedora presença desses insetos no que deveria ser o meu domínio. Eu de fato não sei. 

O que eu sei, é que existem opções para acabar com essa situação de maneira fácil, eu até citei algumas aqui, se não me engano, mas, e posso não estar certo em relação a isso, há alguém que concorde que, quando nos acostumamos a viver solucionando problemas imensos, os pequenos, quando são muitos, parecem insolucionáveis! São tantos e acontecem tão rápido que não podem evitar de nos tornar confusos, seguem uma sequência desconexa inimaginável, são volúveis e desgraçados como personagens de Machado, não se dão a decência de ter um pingo de consistência em suas ações, malditas formigas! 

Temo ter me tornado alguém que não consiga mais lidar com coisas menores do que as imensas, ou, pior ainda, quem sabe agora eu sou alguém que transforme coisas minúsculas em enormes, afinal, se fossem problemas tão insignificantes assim, por que diabos eu estaria falando sobre essas formigas? 

<a href="https://instagram.com/maybebrunno"><i class="bi bi-instagram"></i></a>