---
title: Promessas
author:
- name: Sea Star
categories:
- LÍRICO

---

Dizem que aqueles que juram costumam mentir, então, se você deseja acreditar na palavra de alguém, peça-lhe que prometa, pois, popularmente, promessas são dívidas perpétuas.
| Era pensando nisso que lhe pedia e implorava por promessas, não juramentos.

De uma certa ótica, nossa relação fora baseada em um amontoado de tratos eternos, porque queríamos um para sempre e achávamos que, ao torná-lo um pacto, resistiríamos a qualquer tormenta.

Se houvesse punições divinas para compromissos quebrados, eu e você teríamos sido condenadas ao mais profundo dos abismos.

| Prometemos não brigar e brigamos,
| Não guardar segredos e soterramos o que sentíamos.
| Não nos perdermos em mar aberto e afundamos o nosso barco à vista do porto,
| Não amarmos outras pessoas e agora me pergunto o porquê de não ter sido o bastante para você,
| Não nos odiarmos caso chegássemos ao fim e eu guardo um rancor por ti que quase não cabe em mim.

| Algumas vezes, promessas são a esperança de alguém.
| Por um tempo, as suas foram a minha e gosto de acreditar que tenha sido o mesmo para você. Até que as quebramos e arrancamos qualquer confiança que ainda poderíamos ter.
| Era mais fácil termos jurado, pois nós duas mentimos, afinal.

| Dizem que o amor não dura para sempre, você me jurou que seríamos a exceção.
| Agora, juro-lhe um dia te conceder algum tipo perdão.


<a href="https://instagram.com/meet.meinthesea"><i class="bi bi-instagram"></i></a>
