---
title: Qual a chance
author:
- name: Gabriel Leal
categories:
- CONTO

---

— E aí, tava lá? Tava lá? TAVA?

— A encomenda que o porteiro acabou de interfonar avisando que tinha chegado? Sim, ela tava lá, sim. 

— CADÊ?

— Por que eu que tive que buscar isso mesmo?

— Porque, quanto mais possibilidades eu pensasse, mais coisas diferentes poderiam ser.

— A caixa que estava na portaria? Ela ia vir diferente dependendo do que você pensasse?

— É.

— Enquanto eu subia com ela no elevador?

— Isso.

— A coisa de dentro da caixa podia mudar?

— Aham!

— Tá.

— Às vezes parece que você não acredita em mim, Maria Clara.

— E pra você isso é um conceito muito difícil de entender, né? Desconfiar de alguma coisa.

— Você é quem precisa acreditar mais.

—  Veio um e-mail de um desconhecido e você comprou a nova caixa misteriosa da China. Sem saber o que tem dentro. E eu preciso ser mais que nem você.

— Se eu soubesse, não seria misteriosa.

— Quanto que você pagou nisso, Yuri?

— Eles fazem de tudo por lá, pode vir literalmente qualquer coisa. Tá explicado no e-mail de confirmação de compra que é assim que eles testam as novas mercadorias.

— Confirmando a compra de quanto?

— Falaram que nessa edição iam mandar coisas que têm a ver com energia. 

— Foi isso que fez você estourar o cartão?

— Só não sei se é energia elétrica ou algum outro tipo.

— Yuri, eu tive que pagar sua coxinha ontem.

— Você na real tá me atrapalhando. Se for energia mística, eu devo estar todo desalinhado pra abrir a caixa agora.

— O que você entende de energia mística?

— Podia começar a entender agora, ué.

— Você é quem tá me atrapalhando por não ter pagado o aluguel por causa dos feijões mágicos da China.

— Olha aí! Pode ser alguma coisa que dê muito dinheiro, na história dos feijões era isso, né?

— Claro, depois de matar o cara era isso, sim.

— Verdade, tem essa parte do latrocínio, né? Qual que era a mensagem dessa história?

— Acho que é se você for feito de otário vá até as últimas consequências pra que outro seja otário no seu lugar. 

— Não parece uma boa moral.

— Mas é a realidade. Olha a gente aqui, você foi feito de otário e tá me fazendo pagar todas as contas no seu lugar.

— Calma, que vai valer a pena.

— Claro que vai. O povo Chinês. A maior indústria do mundo. O país milenar. O maior polo de tecnologia e desenvolvimento desse e do próximo século. É assim que eles testam os novos produtos, enviando pro Yuri que mora em Mauá. Esse é o segredo deles.

— É tipo um tablet.

— Que faz o que?

— Não sei, veio sem o carregador na caixa.

— Ô Yuri, vai te tomar no meio do teu cu, vai.

<p style="text-align:center">*</p>

— E aí chegou? Chegou? CHEGOU?

— O cabo que você teve que encomendar da China pro seu tablet que não faz porra nenhuma? 

— ISSO!

— E que tava vindo de lá tem 4 meses?

— É!

— Toma essa merda.

— VALEU!

— E aí, o que que faz?

— Não sei. Tem que ler o manual aqui.

— E deixa eu adivinhar, tá em Chines, né?

— Tá.

— Claro que tá. É claro que tá.

<p style="text-align:center">*</p>

— CONSEGUI!

— O quê?

— Traduzir.

— O quê?

— O manual do negócio da caixa misteriosa.

— O manual que segundo os e-mails você mesmo tinha que saber falar chinês pra ler?

— É.

— Que não podia só pedir pra alguém traduzir, você mesmo tinha que aprender se não ele não funcionava.

— 是的

— Oi?

— É, sim. Em chinês simplificado. 

— Do mesmo pessoal que fala em português por e-mail com você numa boa, mas no manual não pode.

— Se você lesse os e-mails que eu te encaminho, entenderia o motivo; eles foram bem convincentes. 

— Claro que foram. Mas me fala aí então, o que faz o supertablet, o motivo de você estar estudando Chinês faz três anos.

— Ele fala quando que vai faltar energia e quando que ela volta.

— Não fala.

— Fala, sim.

— Nem fodendo.

— É verdade.

— Você já testou?

— Na noite passada. Queria testar antes de te falar.

— E funcionou? Você tá me dizendo que essa merda é realmente útil?

— Eu falo pra você acreditar mais nas coisas, Maria Clara.

— Calma. Você sabia quando que a luz ia voltar e não me avisou?

— Mais ou menos.

— Como assim mais ou menos?

— Você olha aqui, ó, e aí ele te mostra qual a porcentagem de faltar energia e aí, se já tiver sem, tem uma outra tela que te fala a porcentagem de ela voltar.

— E esse número quinze aí na frente?

— Ah, tem isso, ele consegue calcular até quinze segundos no futuro.

— Se vai faltar luz?

— Isso.

— Então ele me fala: “olha, em quinze segundos vai acabar a luz.

— Mais ou menos, essa é a primeira versão. Então a precisão dele é de uns 35%.

— Ele me fala que em quinze segundos pode ser que a energia acabe, mas que não tem total certeza disso?

— É um jeito de ver.

— E depois ele me fala que talvez ela volte, mas que não dá pra saber também.

— É. A precisão de acerto da volta é de 25%, é mais difícil mesmo.

— Claro, mais difícil. São muitas variáveis, né?

— Isso.

— E ele tá falando de probabilidade, talvez nem dê pra prever totalmente, né?

— Aham. E ele tem que estar carregado, se demorar muito, a bateria acaba.

— Quanto tempo dura a bateria?

— Olha, na versão atual que eu consegui pedir por já ter essa, ela vai durar muito mais.

— Você pediu outro?

— E além da coisa da energia tem mais.

— Pagou quanto nessa merda agora?

— Fala quando que uma encomenda que você pediu vai chegar.

— Você não vai pagar o aluguel de novo?

— E aí dessa vez eles nem falaram quando enviam nem quando chega. Pra você já ver como seria útil de ter a parada.

— Mas com toda certeza pagar você já pagou.

— Coisa de saber valorizar o produto mesmo, né? Esse pessoal não brinca.

— Nesse novo, qual a chance de ele acertar tudo?

— Olha, como envolve muitos processos, eles falaram que não é tão alta quanto o da energia. Mas pra ficar tranquilo, que estão trabalhando nisso e o quanto antes vão resolver os possíveis problemas nas possíveis próximas versões.

— Eu te odeio muito, Yuri. Muito. Com cem por cento de acerto.
