---
title: Sol
author:
- name: Xico
categories:
- POEMA

---

| O que será que eu fiz de errado?
| Talvez eu seja a pior pessoa
| Que destrói por onde passa
| A vida de quem se atreve a chegar
| 
| O que será que eu fiz de certo?
| Pra chegar a esse ponto
| Nem sei se planejei direito
| Mas tudo bom é assim
| 
| Talvez eu seja um desastre ambulante
| Uma pandemia solitária 
| E nada que eu toco funciona direito
| Talvez eu seja uma sorte quebrada
| 
| Será que é por querer que tudo vá bem
| Que nada vai bem? Que eu não vou bem?
| Se esse é o destino então cadê a rota de fuga?
| Eu me flagelaria eternamente por um segundo de paz 
| 
| E assim a minha alma pararia de rasgar
| Saindo pela pele tudo aquilo guardado pra depois
| Deixando todas as marcas, invisíveis aos olhos
| Até que um dia todos vejam com clareza
| 
| Queria ser um pouco pior
| Pra ao menos não me importar
| Queria poder prever
| Queria ao menos saber lidar
| 
| Mas talvez nessa tempestade eu encontre o meu Sol…

<a href="https://instagram.com/xicoszn"><i class="bi bi-instagram"></i></a>
