---
title: "&nbsp;"
author: 
  - name: Amanda Genevieve
---

| Morro de medo de sentir medo
| Morro de medo da vida, do futuro, do que me espera
| E
| Enquanto sinto medo, continuo vivendo
| Porque o medo anda comigo
| Por isso que nunca estou só
| O medo é a minha sombra
| Sempre está na minha frente, atrás ou ao meu lado
| Esperando que um dia a gente perceba que sentir medo não é uma escolha, é algo que nasce com a gente
| E que vai caminhando ao nosso lado sem que a gente perceba
| Sussurrando no nosso ouvido os nossos maiores medos
| Até que, um dia, ficamos aprisionadas, mais do que já somos
| Pelo nosso próprio medo
| Que está ao nosso lado, de forma tão sublime, delicada
| A ponto de só percebermos que paralisamos por conta dele
| E, então, nos damos conta de que todo dia ele murmurava algo em nosso ouvido
| O medo nunca esteve distante da gente 
| A felicidade, sim.
| O medo sempre andou colado em nós.

<a href="https://instagram.com/Amandaa.ols"><i class="bi bi-instagram"></i></a>
