---
title: "Arranca ossos"
author: 
  - name: Tiago Torres
---

| Do teor alcoólico da boca faminta 
| Ao tremular dos membros e pálpebras 
| Exigindo do terceiro alheio que não minta
| Carregando raiva e angústia como marcas 
| 
| Cravado em meu peito o medo original 
| Cavalgando em teus seios a liberdade 
| O terror impresso no mundo sem sal 
| O cansaço permanente da idade 
| 
| Ânsia, receio, o jogo valendo a vida
| Passos antecipados três movimentos antes 
| O julgamento do outro não nos dá saída
| A porta dos fundos é para os amantes 
| 
| O arrancar dos ossos na crise aguda 
| Falta verba para sobreviver 
| Suplicam à fera que não ruja e fique muda
| Dinheiro que tem só serve para morrer 
| 
| Investimento psicografado 
| A dor de todo trabalhador prenuncia reunião 
| Depois da marmita fria o seu olho garfado 
| Cutucar o seu cérebro com o metal da união


> Tiago Torres (Camaragibe, 1996) é escritor, realizador cinematográfico e capoeirista. Publicou o livro de poemas Poesias Antropofágicas para Exportação (Editora Viseu, 2021), escreve esporadicamente na revista Ladrão de Fogo. Realizou o curta-metragem documental si amar é viver vivo porque amo você (2021).
