---
title: "Maria Augusta"
author: 
  - name: Alyson Freitas
---

Minha família e meus amigos mais próximos sabem que, com frequência, tenho sonhado com uma garotinha. Ela está sempre usando um vestidinho florido e às vezes um chapéu; tem cabelo curto e liso, pele bem clarinha e olhos castanhos.

O sonho é basicamente o mesmo toda noite: a gente fica brincando num campo enorme e cheio de flores muito bonitas durante a tarde toda.

Apesar de ser pequena, ela é muito inteligente, bem falante e muito educada, fora que está sempre sorrindo. Lembro-me de ela dizer que se chama Maria Augusta. É uma gracinha.

Acontece que, quando o sonho está perto de acabar, ela começa a chorar e diz que vai ficar com saudade porque se sente sozinha e eu sou a única companhia dela. E que vai me esperar voltar.

Mesmo sabendo que é apenas um sonho, fico triste. Isso dá um enorme aperto no peito. Aí acordo e esqueço disso durante o dia.

Hoje mais cedo fui com um amigo ao cemitério visitar o túmulo do tio dele. Na saída, olho para o lado e vejo um túmulo com a foto de uma garotinha chamada Maria Augusta, morta há trinta anos.

<a href="https://instagram.com/alysonfreitas"><i class="bi bi-instagram"></i></a>
