---
title: Medo
author:
- name: Bruna Castro
categories:
- CONTO

---

Vivia assim; sem muito ter. O que tinha era pouco e sua cela vivia cheia de outros, que, por outro lado, o tinham por inteiro. 

Primeiro veio Ela, que sussurrava todo dia em seu ouvido, que gritava quando ele tentava sair. Ela que era a origem e o motivo de ele estar soterrado por tantos outros. Ela, por sua vez, trazia todos eles. Ele sentia seus socos, seus gritos, suas mãos segurando as dele, mas não conseguia vê-la, não conseguia tocá-la e se livrar dela era quase impossível - toda vez que ele conseguia a solução, toda vez que ele quase conseguia que fosse embora, ela mesmo revertia o jogo e fazia ele sentir que estava errando, pecando, espalhando ingratidão e estupidez. 

Foi Ela quem apresentou Ele. Ele a quem ele conseguia enxergar. Uma visão preta, turva, que fazia com ele se arrepiasse todas as vezes. As más línguas diziam que Ele e Ela eram quase que o mesmo. Andavam, portanto, de mãos dadas. Rodeavam a cela com a autoridade e confiança de quem tinha o controle de tudo, porque de fato o tinham. 

Mas Ele e Ela não se bastavam. Ele e Ela faziam estrago juntos, mas tinham uma fonte maior. Aquela que dava mais medo. Aquela que ele evitava a todo custo. Aquela que fazia ele aceitar qualquer coisa, qualquer migalha, qualquer fagulho, só pra mantê-la longe. 

O trio perfeito estava formado. O Medo, a Insegurança e a Solidão dominavam a cela e, toda vez que a Colorida aparecia, eles conseguiam fazer com que ele pensasse que ela era a errada e que tudo além da cela era pecaminoso. 

Os três juntos traziam o efeito colateral e se orgulhavam disso. Ela vinha trêmula, ao longe. Rapidamente chegava perto. Chacoalhava a cela. Deixava todo mundo de cabelo em pé.

Com a fusão de Solidão, Medo e Insegurança, a Ansiedade era resultado, consequência e burburinho.

E de quem seria a culpa no fim das contas? De quem era a responsabilidade de ele estar ali dentro, preso, soterrado, sem chances de escolha, sem livre-arbítrio ou individualidade?

Quem o impedia de seguir? Quem, dos quatro, deixava ele bloqueado, travado, estatelado?

Ele queria entender. Ele queria ao máximo saber. Ele queria respirar. 

Mas ele tinha Medo. Tinha Medo de não ter mais a presença de todos que o prendiam. Medo de ficar sozinho com a Solidão. Tinha Medo porque ficava inseguro consigo mesmo. Medo porque com a Solidão tudo era turvo. Com a Solidão tudo era opaco.

Tinha Medo de não ter mais a visão trêmula da Ansiedade, que já trazia uma sensação de rotina. De continuidade. De casa.

Ele tinha Medo de mudar o espaço. Se não soterrado, como ele ficaria? Se não esquecido, se não pela metade, se não longe dele mesmo, se não em último lugar sempre, como ele ficaria? 

Como seria a sensação de estar no topo? Ele tinha Medo de altura. Tinha Medo de ser o centro das atenções - afinal, a Insegurança sempre disse que ele não era tão bom assim pra estar em primeiro lugar. Tinha Medo de ser lembrado, desgostado. Tinha Medo de ser inteiro e descobrir que sua outra metade estava podre.

Ele tinha Medo de não ter Medo. O Medo era confortante. Deixava ele parado.

A sensação de que o perigo estava sempre afastado o impedia de perceber que o perigo sempre esteve tão perto.

Temia mais do que vivia. Morreu sem viver. 


<a href="https://instagram.com/brunathv"><i class="bi bi-instagram"></i></a>
