---
title: o gato
author:
- name: Larissa Shiromoto
categories:
- CONTO

---

A tempestade seguia interminável. O clarão dos relâmpagos fazia arder os olhos do gato, que deitava todo enrolado numa almofada perto do sofá manchado. Quanto tempo havia se passado desde o primeiro rugido de trovão? O gato não sabia. Matava as horas ali,
cochilando, sonhando com dias ensolarados, quando em seus passeios pela vizinhança,
esfregava-se na grama lambuzado de Sol. Podia sentir o calor abraçando seus pelos, a brisa afagando-lhe os bigodes, o focinho envolto em cheiro de terra úmida, e já de noitinha, ao voltar para o apartamento de seu dono, voltava cheirando a insetos, a crianças no parquinho, a pipas no céu... Mas a realidade era, como sempre, uma grande estraga-prazeres. Aquela chuva o acordava a cada cinco, talvez dez minutos, estragando todos os seus remédios-fantasia.
Como incomodava aquele barulho que tremia suas orelhas. Que petulante a natureza
interrompendo seu sono assim, tão grosseira, tão estúpida! Pensava espreguiçando-se na
almofada. Sua vida já não era difícil o suficiente tendo de caçar as baratas que apareciam no ralo do banheiro? Aguentando as gracinhas que as pombas do outro lado da grade da janela faziam para atiçar suas garras? Ou ainda ter de ouvir o zunido infernal das moscas que flutuavam acima daquele cadáver caído na cozinha? Aquela coisa já estava ali apodrecendo fazia dias, o cheiro se tornou insuportável para o gato, que preferia morrer de fome do que ter a atravessar o cômodo infestado de um aroma repugnante de carne putrefata para chegar ao pote de ração.

Mas se afastar do corpo não adiantava. A presença opressiva e obscura da morte já tinha se instalado no apartamento. Estava em todos os cantos, no sofá manchado de sangue, no arsenal de comprimidos suspeitos do armarinho do banheiro, nas várias trancas que barravam a porta. O gato não entendia por que ele continuava fazendo isso, mas com certeza não parecia normal. Por fora era tão comum quanto qualquer outro ser humano que já vira, exceto talvez por aqueles olhos ébrios de abutre meio escondidos pelas pálpebras sempre entreabertas. Tinha um aspecto um tanto modesto, podia passar despercebido pela multidão das ruas como um homem invisível, e talvez fosse mesmo. Trabalhava na prefeitura das oito da manhã às seis da tarde. Depois chegava em casa, enchia o pote de ração e se trancava no quarto até o dia seguinte. O que ele fazia ali? O gato não sabia, provavelmente só ele poderia responder a essa pergunta. Mas o fato é que passava horas lá dentro, fazendo barulhos indescritíveis que faziam o gato duvidar de seus conhecimentos sobre a natureza humana. Eram gritos que pareciam ter saído das entranhas de algum tipo de animal desconhecido, rouco, bruto, cavernoso, e completamente solitário.

Às vezes ele saia do quarto na madrugada. Enchia um copo de whisky e sentava no sofá.
Permanecia no escuro, calado, imóvel, como uma sombra. Não bebia o whisky, quase não respirava. Os olhos ficavam fixos em alguma coisa perdida no ar, ou talvez estivesse perdida dentro de si mesmo. Era atormentado por essa coisa dia e noite. O gato não sabia ao certo o que era. Ele deixava o whisky de lado, colocava as mãos no rosto e fazia de seu próprio corpo um projétil contra a parede. Se jogava com toda a força nos tijolos do apartamento tantas vezes que sua cabeça ficava sangrando por semanas. Os roxos no seu corpo deixavam claro para o gato que ele não era uma daquelas almas desencarnadas presas no mundo, não, não era. E muito menos uma besta infernal. Era apenas um homenzinho miserável e extremamente amargurado.

Geralmente, nos dias seguintes a essas madrugadas, ele trazia alguém para a casa. O gato não fazia questão de aparecer, teria muito tempo para se apresentar para a visita quando ela estivesse caída na cozinha. Ou melhor, teria muito tempo para se apresentar a todas as partes da visita, seus pés, seus braços, seus fios de cabelo espalhados pelo chão. Todas as suas minúsculas partes. Como alguém que sem querer arranca as asas de um mosquito ao esmagá-lo entre as palmas das mãos, ele desmembrava o corpo em pânico para se livrar das provas. Não importava quantas vezes já tinha feito aquilo, depois de matar, o medo que corria em suas veias era sufocante, mas não o medo de ser pego pela polícia ou de passar o resto da vida numa instituição psiquiátrica macabra, tinha medo de si próprio, de sua compulsão, daquele seu vício horrendo que tinha dado fim a pelo menos sete coitados no último ano. Como ele podia? Como conseguia dormir à noite acompanhado da própria pessoa? Pensava o gato.

Em que parte da sua vida ele se perdeu de si mesmo? Não havia traumas exorbitantes em sua memória ou alguma história excruciante que explicasse seus atos de horror, seu ser abominável escondido no escuro de um apartamento. O que teria dado errado? Seriam seus pensamentos condenáveis por todo o resto da humanidade? Ou será que aquelas mesmas pessoas que o gato observava em suas saídas no verão, andando pelas calçadas com seus filhos, amigos, dando gargalhadas e admirando a si mesmos, às vezes, na calada da noite, também já tinham alguma vez compartilhado das mesmas sensações que seu dono? Será que, alguma vez na vida humana, todos se depararam com uma escolha que, mesmo que parecesse insignificante aos seus olhos mortais, mudou seus caminhos para o lado oposto daquele homem que decepava membros? E, se fosse assim, não seriam todos seres abomináveis por sequer pensar nessas coisas horrendas? Qual a real diferença entre aqueles que pensam e fazem se no fundo a essência é a mesma?

Que terríveis os humanos, pensou o gato. E pôs-se a dormir apesar do barulho lá fora.

<a href="https://instagram.com/lariis_sh"><i class="bi bi-instagram"></i></a>
