---
title: O hereditário
author:
- name: Rodrigo Adriano Machado
categories:
- CONTO

---

Desconfio que você também concordaria com Martinha se percorresse à sua mente o seguinte pensamento: nada pior do que a impressão de estar penetrando em uma ilusão. Decorreu disso os repetitivos movimentos de sua perna direita, a maneira como apertou as mãos, assim que olhou pela janela do ônibus.

A provinciana cidade chamada Calleiolândia. Rapaz, que desgraça! Segundo lhe disseram, por algum motivo, sua mãe decidiu passar as férias do meio do ano ali.

Descendo no terminal rodoviário ela já sacou o celular do bolso da calça e buscou nos seus arquivos a foto de sua versão mais velha, fim de apresentar para qualquer ser vivo que lhe cruzasse o caminho.

— Moço, com licença, chegou a ver esta mulher por aqui?

O balconista da lanchonete apertou os olhos no meio da face magra e pálida. Bocejou, sacudiu negativamente a cabeça.

— Talvez você poderia mostrar para mais alguém...

O balconista continuou lentamente movimentando a cabeça.
Martinha recolheu o celular irritada e foi na direção de um táxi estacionado do outro lado da rua. Um senhor de cabelos brancos cochilava estirado no assento do motorista, óculos escuros. Ela bateu com os nós dos dedos na janela.

— Por gentileza, o senhor poderia me levar até o hotel Hevel?

O taxista puxou os óculos para a testa, observou Martinha em silêncio por um tempo e finalmente gesticulou para que ela subisse.

— Há outros hotéis na cidade?

Ele sacudiu negativamente a cabeça e suspirou profundamente.

— O senhor poderia olhar essa foto e me dizer se já viu essa mulher?

Mexeu nos óculos outra vez e resmungou algo indistinguível, mas parecia uma negação.
Não entendia como sua mãe, uma mulher muito agitada, optou por visitar justamente essa cidade. Era quente e abafado o lugar, ruas poeirentas. Uma atmosfera tão animada quanto as lembranças de um cadáver.

Chegando ao destino, largou o dinheiro sobre o assento do passageiro e avisou que o motorista poderia ficar com o troco. Bateu a porta como sinal de indignação para com tamanha má vontade.

Tocou a campainha na recepção. O som ricocheteou agudo, irritante, metálico. Ouviu passos arrastados atrás de uma cortina bordô. Pareciam percorrer a eternidade através do tédio.

— Boa tarde, fiz uma reserva pelo telefone...

Uma mulher com um rosto redondo e rosado lhe encarou com raiva. Longos cabelos loiros, lisos. Mascou alguma coisa na boca e colocou no lado da bochecha esquerda.

— Marta. Isso? — Conferiu em um caderno de capa vermelha que parecia
combinar com a cortina.

— Isso. Posso perguntar uma coisa? — Mostrou a tela do celular.

— O que que tem?

— Essa mulher não se hospedou aqui alguns dias atrás?

— Nunca vi.

— Não é possível, esse é o único hotel da cidade e…

— Não admitirei ser interrompida ou contestada!

— Não, não é isso. Apenas queria dizer que é estranho…

— Todos nossos processos são claros e concretos, objetivos, não admitimos nenhum tipo de opressão.

— Ah, sim senhora. Então, posso ir para o quarto que reservei?

A mulher girou sobre si mesma e saiu arrastando os pés. Martinha sentiu que o certo era andar às suas costas seguindo a velocidade ditada como uma marcha. Atravessaram um corredor escuro até uma porta. A mulher destrancou a porta e deu um passo ao lado. Permaneceu imóvel encarando o nada.

— Será que eu posso entrar?

— Será que tu vai conseguir sair?

> Rodrigo Adriano Machado. Escritor, músico, mestre em Filosofia.
