---
title: Paredes de papel
author:
- name: Clara Maas
categories:
- CONTO

---

Eu sempre achei esquisitas as paredes lá de casa. Elas pareciam tortas na diagonal, como se qualquer estrutura que tivesse tentado se manter ali não fosse suficiente, então elas tinham que pender pra um lado só.

Eu falava disso pros meus pais, mas eles não entendiam muito bem. Do meu ângulo curto, cresciam os medos de que a casa fosse desmoronar em cima da minha cabeça, enquanto eu estivesse tentado a esquecer do teto para dormir, e me imaginar flutuando céu adentro. 

Por anos, eu chegava em casa e me esgueirava pelas portas, um pavor profundo do toque entre a minha pele e aquele cimento pintado. Um leve contato meu, e tudo vinha ao fim. 

Depois de um tempo tudo começou a ficar pesado demais. Já não era a minha pequena existência, ou melhor, o fim dela que parecia me despedaçar, mas um aperto bem no meio de mim, que me parecia mil vezes pior. Se eles não entendiam que as paredes podiam cair, se eles não percebiam toda sua tortura em auge, então quando tudo se acabasse só eu iria saber? Se tudo fosse em vento, o vão seria minha culpa? 

Eu comecei a viver em súplica. Às vezes mencionando as paredes todas as horas do dia que eu podia, o que às vezes se encontrava com um leve esporro de ignorância, ou às vezes eu ficava completamente muda, encarando aquela catástrofe lenta como uma tentativa de desistência. Daías noites em que imaginara que os céus acabaram se transformando em noites onde eu indagava sozinha se, quando a hora chegasse, eu deveria apenas sentar e esperar, em um acordo silencioso comigo mesma, de perecer entre os meus, ou se deveria me prevenir e sair correndo assim que visse seus sinais profanos, afinal, que vida tola e despedaçada seria essa onde se vê que ocorrerá e se entrega sem tentativa de luta. 

E o dia finalmente chegou. Ou pensei que tinha chegado. Eu acordei com os rugidos de dentes trituradores aos meus ouvidos, gritos abafados vindo do andar de baixo, um tremor estranho todos misturados na mesma atmosfera. Era isso, eu pensei. Finalmente tinha acabado. E eu havia restado para viver com esse pesar. Agora só me restava a curta caminhada do meu quarto até a sala, onde me sentaria no chão e refletiria sobre a minha inutilidade. 

Para minha surpresa as escadas estavam intactas, os degraus não rangiam o suficiente para quebrar debaixo de meus pés, e, de onde eu estava, não via nenhum dos destroços. Cheguei na porta da sala e dei de cara com elas. As paredes. Intactas à minha frente sem nem uma fissura sequer. Tortas como sempre, mas paradas, estagnadas, no mesmo exato lugar de sempre. Os gritos abafados que eu ouvira há pouco eu reconhecia agora no rosto dos meus pais, sentados em frente à tv, vendo alguma bobagem de terror qualquer. E o barulho triturante e medonho que eu ainda ouvia ao fundo, fora pouco a pouco se tornando na britadeira da reforma no vizinho.

Meu mundo tinha quase chegado ao fim. Mas ninguém parecia ligar. Uma catástrofe poderia ter ocorrido alguns segundos antes, mas todos eles respiravam igual, miravam igual, existiam igual. O mundo quase tinha acabado mas não importava, porque não tinha acabado de verdade, não de uma forma que pudesse ser vista, ou compreendida. E pela primeira vez eu olhei para as paredes, encarei-as com todo o resto das energias que possuía em mim, e as vi como qualquer outra parede, em qualquer outro lugar. Rígidas, solenes, e realmente retas. 

O cansaço me alcançou, e eu comecei a me arrastar escada acima. E, quando cheguei ao seu topo, olhei para baixo. O assoalho perfeito à minha frente. Ou quase perfeito. Toda madeira ali se encontrava encaixada sem defeito entre elas. Se não fosse por dois tacos. Um maior que o outro, saltando para cima do chão. O suor correu frio por mim. Que alarme intenso. Como poderia viver em uma casa assim, com a superfície tão prejudicada, com um chão tão mortal. Um chão tão torto. É claro que ali poderíamos tropeçar, um por um, e quebrar o pescoço. Também havia o perigo de pisar em cima e demolir a casa ou extrair toda a fisionomia do mundo ou…

<a href="https://instagram.com/clara_maas_"><i class="bi bi-instagram"></i></a>
