---
title: "Pesadelos"
author: 
  - name: Vinicius Lima
---

| Primeira noite,
| 
| Está frio em pleno verão.
| Talvez eu pegue mais um... Não,
| Um cobertor a mais não vai
| Aplacar a dor que recai
| Em meus ossos quando me deito.
| Talvez eu vá dormir direito
| Depois de ir mais uma vez
| Ao banheiro. Quem foi que fez
| O favor de abrir a janela?
| Minha mãe, deve ter sido ela...
| Mesmo assim não consigo ver
| Nada em meu quarto pra poder
| Chegar à porta. Já estou
| Dando voltas sem parar, ou
| Andando reto... Este lugar
| Já não parece mais meu lar.
| 
| Segunda noite,
| 
| Noite chuvosa e barulhenta,
| Clima gostoso pra dormir.
| O sono vem de forma lenta
| E o sonho começa a fluir...
| Eu estou em uma montanha,
| É noite, e aqui também chove;
| Sinto uma sensação estranha
| De que alguma coisa se move
| Na floresta. Ouço uma voz
| Se aproximando por trás,
| Das árvores vindo veloz
| Com um som ríspido que faz
| Eu querer logo me esconder.
| Começo a descer a montanha
| Rapidamente. Esse ser
| Chega perto de mim e apanha
| Meus ombros, e quando me viro
| Assustado: nada.
| 
| Terceira noite,
| 
| Já estou quase chegando em casa
| Pra poder enfim descansar.
| A iluminação aqui é rasa,
| Quase não dá pra enxergar
| O próprio chão que estou pisando
| E os insetos que andam nele.
| Com nojo apresso o passo, quando
| Vejo uma fissura que expele
| Mil baratas na minha direção.
| Um desespero em meu íntimo
| Me lança em direção à porta
| Que não abre, emperra. Por fim sinto
| Esses bichos em grande horda
| Rastejando pelo chão
| Como se fosse em minha própria pele.
| A janela também não abre
| E já não tem ninguém em casa
| Pra poder me ajudar.
| Um estalo forte e abafado
| Que parece um osso quebrando...
| A janela abriu.
| 
| Quarta noite,
| 
| Vento forte, um assobio
| Que quer me fazer companhia.
| Há um sentimento febril
| Em meu peito, uma agonia
| Me soterrando em minha cama.
| Me agito, e de pouco em pouco
| Arranco da terra o meu corpo.
| Ouço alguém que se move,
| E sinto que ele pode me ajudar
| A escapar desse tormento.
| Tento gritar por socorro mas a voz não sai,
| Apenas um grunhido horrível;
| Me aproximo o suficiente para tocá-lo
| Mas, num piscar de olhos, me calo...
| Estou sozinho de novo,
| E essa floresta tem o cheiro
| Do cemitério que eu fui ontem.
| 
| Quinta noite,
| 
| Eu estou num lugar fechado
| Descendo uma escada desgastada.
| Cada degrau que eu piso estala
| Com um ruído abafado
| Que me corrói também um pouco.
| No fim dela tem uma porta aberta,
| E através, uma sala deserta.
| Dentro, uma abominação:
| Um braço contorcido de forma inumana
| Pendendo do que é agora
| Um bocado de matéria que emana
| Puro horror em minha direção.
| Perco a respiração por um instante,
| Pois já vi algo semelhante a isso,
| Mas alegre, animado, colorido...
| Esses olhos de vidro que nunca vou esquecer,
| Pois posso vê-los em meus próprios olhos,
| Cravou em meu peito um olhar imortal
| Nessa cena que não paro de reviver:
| Minha mãe jazia no chão, morta.

