---
title: "Sexta-Feira 13"
author: 
  - name: Larissa Shiromoto
---

Sexta feira 13.
Onze e meia da noite.

Seu Bentinho bateu à porta. Silêncio. Seu Bentinho bateu de novo.

-- Cumpadre Bento! Sas hora passando aqui em casa. Quié que aconteceu?
-- Ô seu Chico, cê me perdoa, mai eu tinha que passa aqui pra ti devolve o dinhero do
almoço. Gosto de fica devendo nada pra ninguém não. Ainda mais depois de hoje, ainda
mais procê.
-- Ah cumpadre, num carecia de vim sas hora paga coisa qui nem me alembro. Mai já que cê ta aqui, entra! Vamo toma um café antes de dormi que é bom que dá sono.

Seu Bentinho entrou. Tudo escuro, tudo vazio. A casa era oca como um tambor, daqueles
que ressoa um barulho estranho, alto, inconfundível. O som do luto, claro. Essa onda que
quebra o frágil ser dentro do nosso peito, e ecoa num infinito distante, irreparável. A onda
vai, a onda volta. O vazio fica. Todas as paredes eram iguais. Brancas. Com exceção
daquela imagem da Virgem Maria, já bem gasta, que decorava inutilmente a estante onde
antes bateu a sombra do caixão.

-- É seu Chico. não tá facil. Oia só. A Ritinha da esquina, fia da dona Marta, que quando a
gente era criança dava biscoito pa nóis, o cumpadre Aliceu, qui tinha mais de 70 anos nas
costa, e agora teu irmão. Como que pode? Três velório seguido pra uma cidade miudinha
dessa.

Compadre Chico abriu o bule de café, e sentou na mesa.

-- Sei não Bentinho, sei não. Isso ai não tá normar. Meu irmão era véio já tava doente, mai ia na missa comunga todo domingo andando sozinho essas ladera arriba. Seu Aliceu também inda que véio trabaiava na loja qui nem moço de cidade grande. Pra mim isso é coisa di lobisome seu Bentinho, é trabaio do coisa ruim.
-- Ave Chico! Num diga coisa dessa não, hómi.
-- Pois é verdade. Meu pai qui contava qui quando ele era criança, lá pelas banda pra cima
do Morro do Gigante, ele viu um bicho enorme adentrando pros mato de Minas Gerais,
perto daquela capelinha di Guadalupe. Num era gente, mai tamém num era bicho. Era uma coisa feia qui só. O cão anda por essas banda Bento. Só isperô eu sai de casa pra pesca lambari onti a noite qui já ataco otro coitado.
-- Mai num brinque cum essas coisa Chico. Óia a Virge abençoando nois tudo aqui nessa
casa. O qui teve co seu irmão foi acidente. Tamém essa iscada im caracol aqui nesse
sobradão mai vazio que casca de jabuti. Mi dexa bobo vê ocê creditando em coisa ruim.
-- Só num vê quem num qué, Bento. Eu num temo purque Deus ta do meu lado. Mai ocê qui fique isperto. Vindo aqui sas hora da noite. A cidade vai cisma cocê hein. Inda mais peludo desse jeito qui ocê é, nunca vi hómi pra te tanta barba.

Meia-noite
Seu bentinho, espantado, não responde nada.

-- Ixi! Oia a hora, Chico! Mió eu i andando antis qui esse nevoero dessas banda mi dexa
perdido.
- Cumpadre, é mês de juio i tá fazendo o maior frio, depois ocê fica doenti i vai di velório
tamém, i andando sem blusa inda. Passa a noiti aqui qui cama num falta.

Os pelos do braço de Seu Bento se arrepiam.

-- Sabe o qui é, cumpadi, é qui minha muié tá mi isperando, i si ela acha q fui pô bar eu durmo e na rua. Preciso i mesmo.
-- Mai num fique assim qui eu converso com ela dispois, num tem purquê tanta braveza.
Vamo, compadre, vamo subi pro seu quarto qui já ta tardi.

A testa do compadre Bentinho brilha. Um suor enigmático corre sua pele salgada, parecia
que havia sido mergulhado num balde de manteiga que se rastejava pelo seu corpo. O
rosto, áspero de sol, refletia uma sensação inexplicável de dor sufocante que corria das
unhas dos pés até a ponta dos cabelos. Lá vinha um tremelique. Pensou em Deus, nas
montanhas do Gigante, no seu pai, no velório, na fazenda, e a neblina e o frio escaldante da noite ,virgem, como a santa que cravava os olhos nele. Era ele! O coisa ruim! Era ele!

-- Chico, sai de perto! - gritava- To ti avisando, Chico! Fica longe! Fica longe!

Mas não deu tempo de mais nada. Seu Chico, já transformado naquela coisa que tirou o
fôlego de Bentinho, arrancou a cabeça molhada de suor numa mordida descomunal. As
paredes se pintam com as cores de compadre Bentinho. Não era bicho. Não era gente. O
diabo surge na neblina da cidade.

<a href="https://instagram.com/lariis_sh"><i class="bi bi-instagram"></i></a>
