---
title: 'À cegonha'
author: 
  - name: "Attilio Braghetto"
---

Se preguiça fosse uma letra, seria um R caipira daqueles que se vão embora até o pôr-do-sol, faz de dedinho que volta e, despercebido, fica vendo a chegante Lua passar. Sim, senhora preguiça, mãe das causas deixadas e filha das horas perdidas, te tragaram dum bafo quente, e a sua malicenta pele ainda guarda dessa quentura. Relógios derretem; nua, a musa posa ao nada, a ninguém, e devaneia; aternado, um empresário preguiça: se tudo, deixe o hoje para depois. Vi maçãs em seu rosto, elas eram as grandes ideias, as grandes perdições e o fim dos nossos futuros. Seus sóis cor de morno me preenchem o espírito, as almas todas e a cabeça; fico como que emarasmado. Preguice-se, mundo! Acho que a cegonha errou-me o lar se vivo numa terra em que condenam a preguiça e abençoam o trabalho. Concretos e concretos emparelham, escracham, tic-taqueiam e trazem a insólita sentença: trabalhe!, crie!, torne-se digno! Parte-te em 7, cegonha torta, e morra de solidão, não te perdoo o erro de me botar aqui. Contrario todas as formas de me mandar se mexa: sou um saco de carne quente e malicento. À cegonha que primeiro amaldiçoou as carnes do meu cadáver, dedico-te cada uma de minhas injúrias. Acabe, mundo, acabe, e deixe tudo para amanhã…

<a href="https://instagram.com/attiliobraghetto"><i class="bi bi-instagram"></i></a>
