---
title: 'Sombra da preguiça'
author: 
  - name: "Caio Aruanã Batista"
---

A inação, chaga da preguiça corrosiva, atormenta a alma sem parar como um relógio incessante a tilintar. Escutam-se gritos, lamentos, risos e nada... Ignora-se a dor como uma brisa fria d'uma manhã cinzenta que, na mera esperança, tende a passar, mas nunca passa.

A preguiça refuga a ruminação da esperança que desce ansiosa dos céus na forma de raios cintilantes dissipando a forma nebulosa do finito. Ruminando, como na encosta ladina, a ideia d'outro amanhã, talvez.

A covardia, sangue de pedra, corrói a retidão do caminho; caminho esse, antes iluminado, agora sombrio pela preguiça acovardada, que esguia-se em meio a passagens imundas, mas serenas pela vagueza.

A preguiça, como num sumidouro infinito, emudece os ecos do amanhã, selando-os nas sombras infecundas de um nada retumbante. Mas talvez, no jogo do destino, reencontre-se a luz, como peixes cavernosos tocados pela luz cintilante de um raio insípido, sentindo o chamado silencioso para um outrora distinto.

A voz da consciência desperta mas algo clama pela sonolência inebriante, como que alegre em sua liberdade imóbil... Afinal, na preguiça, não há fracasso. Resguarda-se, assim, a frustração da realidade sofrida, mas vivida.

A crônica de uma preguiça incessante, cantada pelos poetas do acaso, revela a imaturidade do irrealizado em sua frustração incontida, berrando como nos gritos estridentes de uma criança. A preguiça, na maturidade, torna-se o bolor de uma fruta em seu próprio cacho.

A reflexão final, no ápice da preguiça encarnada, encontra, no passado, o vazio da insignificância; incrédulo, o espírito insiste e, quando tomado pelo espanto do desaparecimento, desperta para aquilo que urge, mas jaz sem tempo... Resta, agora, o apagamento de mais um que sucumbiu à preguiça.

<a href="https://instagram.com/Batista.caioaruana"><i class="bi bi-instagram"></i></a>
