---
title: 'Caos e cosmos'
author: 
  - name: "Ludmilla Rios"
---

De certa feita havia céus e terra e era necessário fazer criaturas. O exagero das criaturas. Num grande caldeirão de dendê, nada frutado, oliveiro ou extravirgem, a quatro mãos se tirava o azeite borbulhante da superfície, se fazia uma dança, se beijava assombroso em cima da pia, se chupava, demoradamente, o dedo queimado da panela quente, na cozinha celestial, e assim nasceram as criaturas — das gotas pulando do dendê, do ar úmido expirado, dos olhos quase fechados, do susto. 

Depois de passados os tempos ancestrais, andaram sob céus e sobre terras milhares de criaturas. Eu, uma delas, entro na minha cozinha, ansiando repetir os rituais. Não sei de onde vem a ideia de ser esse um pecado, te botar de joelhos diante de mim. Não sou eu um recipiente da vertente santa infinita da criação, objeto digno de adoração? Não poderiam ser estes um fogão celestial, uma geladeira celestial, uma mesa vazia lá no alto dos céus? E não poderíamos nós fazer criaturas?

Numa virada rápida, ficando agora eu prostrada, em resposta ao som de gente do lado de fora da porta, a língua estrangeira me diz: Disguise your bliss. O tanto que ando avoada, o tanto que nego e escondo e suspiro em mais de um canto, diante de fotos, diante de ideias. Disguise your bliss. Desejos e diásporas, um quase esfacelamento do modo como eu me penso, os cachos sempre caídos sobre os olhos agora puxados para trás, os óculos num canto, abandonados, você não me deixa ver para além de um borrão, não me deixa falar para além de um ou dois sons, então sentencia silêncio mortal, antetemporal, devaneio noturno, e o sol brilha no canto da cozinha, enquanto ficamos na sombra, a luz do forno, a torta assando, o arroz borbulhando, gotas a escorrer e ebulir sem fim. 

Há algumas semanas, sentada num banco de concreto no saguão da faculdade, eu te vi de passagem, conversando. É isso que acaba por me atrair por tudo ao redor, o ato de criar com palavras. Você me diz porra ao pé do ouvido, e nasce uma ideia, a de que o desejo da nossa fusão botaria ordem no mundo. A de que o ser eu-você seria suficiente para preencher todos os espaços, todos os tempos, só por eu ser assim tão gostosa.

Dá vontade de jogar tudo no chão, que quebre!, como um dia, andando na rua, me deu vontade de desajustar as mesas, os carros, as lojas, os meio-fios. Só de te ver conversando. De te ver, queria retomar o caos dos tempos primitivos. E há de se escrever, de piscar, de respirar, de comer. Imagina te ver e assinar papéis, imagina te ver e ter de calcular o horário, organizar pensamentos, paginar citações, concluir sentenças. A glória buscando alívio e o mundo querendo me botar significado plausível. Ainda bem que aqui são só borrões e um ou dois cochichos. 

Foi e há de ser assim em algum momento em todas as existências terrenas, para se perpetuar criaturas. Há de se cometer o pecado do exagero da luxúria para o pecado do exagero das criaturas. Há de um ser, sentado num banco, ver outro ser conversando. De acompanhar em vidro. De esquecer do livro na mão. E num instante não sei sequer quanto depois, retornar forçosamente ao cosmos, ao som do fim do temporizador, vapor saindo do forno. 

<a href="https://instagram.com/mill_eumanoites"><i class="bi bi-instagram"></i></a>
