---
title: Efeito Ipanema, Amor
author:
- name: Monalisa de Bandana
categories:
- POEMA

---

| Seus olhos de jabuticaba 
| fitavam,
| A opulência natural vem de ti 
| e é linda,
| a partir deles senti o doce 
| teu fruto
| Os sutis toques em tuas costas 
| revelavam o veludo de tua pele 
| 
| 
| Na beira mar, 
| estirados a areia 
| senti que era capaz de levitar 
| A brutal colisão das ondas 
| em Ipanema 
| foi testemunha do encontro
| Esses lábios
| vorazes como o mar 
| se atracaram 
| a amar
| 
| 
| Acho-te imensamente lindo 
| igual o oceano, 
| também acho obscuro, 
| profundo 
| e inexplorado 
| 
| 
| A poesia que tocava dizia: 
| “now I know how I feel como rio
| no riacho dos teus braços 
| descasco em arrepio”
| Fui na contramão das ondas 
| tomei um caldo 
| 
| 
| Como Ipanema
| Você é um ecossistema luxuoso
| completo
| vejo todas as suas
| cadeias alimentares funcionarem
| 
| 
| Não esqueço,
| antes do caldo 
| você me explicava
| a ecolocalização das baleias
| você 
| emitia 
| sons 
| quando meu objeto rígido lhe atingiu 
| tal qual as baleias 
| 
| 
| No apertado apartamento, 
| você teclava em tecnologias 
| eu almejava 
| que tocasse em mim.
| Sua profundidade 
| emergida em superficialidade 
| Num rápido momento
| nossos corpos se comprimiram 
| um sob o outro
| 
| 
| era um tsunami 
| 
| 
| sensações arrebatando 
| tudo que pudessem 
| “aproveitemos o momento”, 
| ao mergulhar em seu açúcar 
| me cristalizei 
| afoguei
| Sua boca tem gosto salgado, 
| dos mais doces que já provei
| 
| 
| Contraditoriamente 
| é o mar 
| vem e vai. 
| 
| 
| Vem dando indícios 
| de que quer me banhar em seu sal 
| vai embora 
| recolhendo-se para você
| (espera adoçar a si mesmo?)
| Você é uma contradição, 
| das mais gostosas
| de se provar. 
| 
| 
| Cê vive emergido 
| nas profundezas 
| assim como teu animal favorito
| tal qual as baleias
| 
| 
| Você é Ipanema a mim
| Você é a ecolocalização a mim 
| Você é o quebrar das ondas a mim
| Você é o vazio do carro a mim 
| 
| 
| Na despedida, 
| não nos beijamos 
| Fique seco
| Sem sal
| Sem mar
| Sem localização alguma 
| Sem o doce suco da sua fruta
| úmida e marítima
| Desidratado 
| Sem luxo. 
| 
| 
| Eu queria que a gente 
| fizesse
| ecolocalização
| ao final, 
| o único objeto que me atingiu 
| foi o vazio 
| Este, surgiu luxuoso de tão grande 
| Desequilibrou nossa cadeia.
| 
| 
| 
| 
| Este escrito é sobre a luxuosidade do que se sente. É sobre baleias, doce tesão, contradição, natureza, vazio, ecolocalização. 
| Efeito Ipanema, amor.
 
<a href="https://instagram.com/monalisadebandana"><i class="bi bi-instagram"></i></a>
