---
title: 'GABRIELA'
author: 
  - name: "Amanda Genevieve"
---

Desde que o pai da minha amiga foi morar com outra família, Gabriela nunca mais foi a mesma. Não é que a tristeza tenha invadido todo o seu corpo, porque, desde o ocorrido, ela tem ficado cada vez mais bonita, mais deslumbrante;  observá-la passando em qualquer lugar é quase um espetáculo, uma performance, não dá vontade de tirar o olho dela nem por um minuto sequer.

De um ano pra cá, não saímos mais aos fins de semana. Ela tem gastado seu tempo com a libertinagem, Gabi quer se sentir livre, desejada, seduzir, ser seduzida. Não quer saber de conversas, de calmaria. Quer fugir de si, acho que é por isso que ela tem evitado nossos encontros, penso que, quando ela me vê, ela lembra de si e do que lhe falta. Toda essa sensualidade que ela tem exalado é poder, é fuga dos seus problemas, é vida ou a morte.

Quem olha de fora pensa que Gabriela está vivendo uma vida recheada de amores, de desejos, de trocas, de várias vidas em uma única. Só que quem acompanha a sua vida por mais de uma semana percebe que não há como ter tudo isso de vivacidade, com tanta fuga de si. Não há como ter desejo no outro se ela só quer ser desejada. Perguntei a ela o que a impedia de voltar para si e parar de viver com tanta fuga. Ela me respondeu que não tava preparada para abandonar um vazio que mantinha seu pai presente em sua vida. Começar uma nova vida, abandonar a libertinagem, esse excesso de busca no prazer carnal, é conhecer outros vazios. Há que se ter muita coragem para preencher alguns vazios e construir outros.

<a href="https://instagram.com/amandaa.ols"><i class="bi bi-instagram"></i></a>
