---
title: 'Pedaço de pecado'
author: 
  - name: "Morgana"
---

| O doce calor do sol me amortece 
| Um suave toque quente de dedos na pele
| Palavras sussurradas 
| A respiração pesada
| 
| Você me faz dançar mesmo deitada 
| Me chamando de sua
| Você gosta que te olho com cara de atirada 
| Safada, tarada, deflorada
| Sempre fazendo questão de deixar minha alma nua
| 
| Sou seu pedaço de pecado 
| E gosto quando você me implora
| Amarrando meu cabelo 
| Me pedindo pra eu te mostrar como é o céu 
| Como o mundo é pequeno 
| Como pular de um paraquedas não te engrandece como eu 
| 
| 
| Sou pecaminosa
| Te devoro
| Te defloro
| 
| Sou sua Eva 
| Erva daninha 
| 
| Seu arrependimento 
| Vem e perde teu discernimento 
| 
| Me arrasto demoradamente até o ápice do sabor 
| Entrando em seus beijos 
| Vem 
| E Me mostra como a vida a dois é saciável 
| 
| Brinque de instrumentista
| Finja ser um ladrãozinho
| Me mostre malabarismos 
| Seja um bom  artista
| 
| Te apresento novidades
| Me faço de puritana 
| Assumo suas fantasias 
| e te deixo implorando 
| 
| Em um belo dia
| Chuvoso e pastoso
| Você me faz um pedido:
| - Fique comigo 
| Apenas mais uns momentos 
| Mas não seremos assumidos 
| 
| Sou sua perdição 
| Não posso servir para um casório 
| 
| 
| Quem sabe?
| Um dia você aprenda  
| sou sua boa moça 
| sua beata 
| 
| apenas uma fantasia
| nesse seu universo 
| de homem babaca
