---
title: Uma reflexão sobre a luxúria
author:
- name: Giovanna Sabino
categories:
- ENSAIO

---

:::{.center-push}

Ia escrever da luxúria, mas então pensei...

existe a luxúria pura? Luxúria sem contexto...

luxúria sem nada a mais por dizer... 

luxúria por luxúria... 

luxúria sem amor?

O leitor pode apontar-me, e com muita razão, que esses questionamentos são um tanto... individuais demais...
Mas eu rebato ao caro leitor:

Existe a luxúria sem individualidade?

Como pensar no carnal e no físico,no pecado literal em sua forma demonstrada,
sem pensar no que, para o indivíduo, valha a pena colocar tudo isso em prática?

E como pensar luxúria sem pensar no sentimento que vem escondido atrás dela quase que despercebido?

Sim porque o leitor pode tentar me dizer que não, mas a luxúria se entrelaça ao primeiro desavisado que passar por perto dela devagar o suficiente... a paixão forte o suficiente... A dor... o trauma.

E se é pecado, é pecado porque é bom e é contra as leis divinas se sentir bem, ou é pecado porque o pobre coitado que um dia decidiu o que era ou não contra as regras de deus teve uma péssima foda e achou que ninguém merecia passar por isso?

É de se pensar caro leitor...

E vem primeiro o amor para vir a luxúria?

Ou vem primeiro a luxúria...desacompanhada e independente...
casualmente encontrando o velho conhecido amor pelo caminho?

Ou será que, se há o encontro, necessariamente há uma briga ao longo do trajeto? 

E quanto a uma possível reconciliação? 
Como fica o relacionamento dos sentimentos dos que sentem enquanto sentem em conjunto?

A luxúria é um problema? Existe um vício na luxúria ou isso é um mito porque a luxúria é um pecado, e tudo o que é bom deve ser jogado ao fogo dos infernos, Deus nos perdoe caro leitor?

É de se pensar!... É de se pensar!...

:::

<a href="https://instagram.com/forlissies"><i class="bi bi-instagram"></i></a>
