---
title: '-'
author:
- name: Anônimo
categories:
- POEMA

---

| Você tinha apenas doze,
| Quando te tiraram o sabor da infância,
| E quando fez catorze,
| Seu marido tirou à força sua esperança
| E com brutalidade,
| Te fez deixar de ser criança.
| Ele não era muito homem de respeitar as leis,
| Gastava o dinheiro em todas de bar,
| Era dela que vinha o sustento família,
| Mas nem isso era suficiente,
| Suficiente pra ela se revoltar...
| "E é melhor nem ousar reclamar",
| Era isso que a patroa dizia,
| Você nada respondia,
| Porque é ela que alimenta suas filhas.
| Quando a noite chega,
| Seu marido está em casa,
| Ele espera que você o aceite de peito aberto,
| Você tem medo,
| Não quer que ele chegue perto,
| Você rapidamente se afasta,
| Ele não diz, uma palavra,
| E você sabe que é melhor ficar calada.
| Eu nunca vi seus cabelos ficarem brancos,
| Você não morreu naturalmente,
| Eles te assassinaram bem antes de eu te conhecer,
| Ninguém viu as coisas que você fez para sobreviver,
| As decisões tomadas por obrigação,
| Me perdoa por não ter conseguido ver,
| Que você já tinha se perdido.
| Curtir
| Encaminhar
| Copiar
| Denunciar
| Bem antes de eu te perder.
