---
title: dia 12/6 - tia bia
author:
- name: Gabriella Menezes Soares
categories:
- LÍRICO

---

| Eu amo o crepúsculo da USP.
| Qualquer momento de distração e você pode perder algo muito importante, como o cair de
| uma sombra ou a passagem de uma nuvem que muda o sol.
| Não me sinto mais tão nova, há um cansaço nas minhas ações, a magreza do corpo como
| um aviso de tudo que perdi. É claro que na maior parte dos dias acredito que aprendi,
| ganhei alguma coisa nessa troca toda, mas abri mão de outras também. Acho que há dias e
| dias.
| ...
| Sempre irei ficar fascinada com a forma desse lugar, lembra-me o conforto do isolamento na
| cidade e das boas, mesmo que escassas, memórias do lar.
| O fluxo emocional me consome e fascina, é divertido mas parece tão perene... a maior
| crueldade que faz a vida é a incerteza, a paz absoluta de não errar.
| Eu quero ver você hoje e possivelmente vou querer te ver amanhã e por mais que queira
| não posso dar conta do depois.
| A graça de achar que está tudo resolvido e portanto está tudo bem, mas me sinto bem
| apesar de tudo.
| Acho que vai chover.

<a href="https://instagram.com/gab.ismenezes"><i class="bi bi-instagram"></i></a>
