---
title: Diário de um aluno USP
author:
- name: Vinicius Torres Mendes
categories:
- DIARIO

---

Adentramos o campus da USP, um lugar que se ergue majestoso em meio às árvores e ao
concreto, um oásis intelectual em meio ao caos da cidade. Mas é quando mergulhamos em
suas profundezas que descobrimos que nem tudo é o que parece.
Entre as salas de aula e bibliotecas, há uma névoa que paira sobre a alma dos estudantes,
um vazio que se instala no peito e que parece não ter fim. O desespero, esse vilão
insidioso, parece encontrar na USP seu terreno fértil, seu lar doce lar.
O realismo capitalista se manifesta aqui em sua forma mais pura, como uma serpente que
se enrola em torno da mente dos jovens, sugando toda a vitalidade e energia que antes os
impulsionava a seguir em frente, restando apenas desilusão de que a única solução seria o
fim do mundo.

Mas talvez haja uma solução. Talvez possamos criar algo tão louco, tão absurdo, que possa
nos fazer rir dessa terrível condição. Um lugar onde possamos depositar todas as nossas
tristezas e desilusões, onde possamos trocá-las por algo que nos traga alegria e esperança.
Imaginem um banco, um banco de troca desse desespero, um lugar onde possamos
depositar todas as nossas notas baixas, nossas rejeições amorosas, nossas inseguranças e
medos. E em troca, recebamos algumas moedas que possam ser gastas em algo que nos
faça sentir vivos novamente.

Um cinema, um concerto, um bar com os amigos. Qualquer coisa que possa nos tirar dessa
prisão de tristeza e nos levar para além das paredes da USP e fazer com que nos sentimos
vivos novamente, mas por um curto período de tempo.
Escrevo isso tudo, mas talvez seja uma ideia maluca. Talvez seja uma tentativa
desesperada de encontrar um pouco de humor em meio à tristeza. Mas quem sabe, talvez
um dia essa ideia maluca possa se tornar realidade. E o desespero e a tristeza não serão
mais inimigos implacáveis. Só me resta aproveitar essa clínica de reabilitação em massa
que é a USP, e tentar sobreviver ao meio dos amores plásticos. aooo coisa boa👏👏👏


<a href="https://instagram.com/Vini.memes_"><i class="bi bi-instagram"></i></a>
