---
title: "Identidade"
author: 
  - name: Otávio de Sousa
---

| Eu não sou 
| Uma pessoa 
| Talvez eu seja 
| Uma lagoa 
| E alguém
| Se afoga em mim 
| Talvez eu seja espaço
| Aberto 
| Ao contrário
| Jogado
| Ao acaso 
| Do montante 
| Logrado 
| Fazendo-me assim 
| Eu claramente
| Não sou 
| Uma pessoa 
| Estou mais para 
| Um pássaro 
| Voando com asco
| Do meu ser 
| Enfim 
| Eu sou uma Pepsi cola 
| Gelada 
| Enquanto se chora 
| No verão
| Quente 
| Estação
| Talvez eu seja
| Um verme
| Nos intestinos 
| Dos cernes
| Celestiais 
| De jasmim 
| Talvez eu seja 
| Gota do Brahma
| Um giro 
| Em volta 
| De mim 
| Quem te 
| Disse 
| O que eras 
| E por que 
| Foste seu pai ? 
| Quem lhe deu
| Um caminho 
| Uma fala 
| Nesse teatro 
| Que gira 
| Anti
| Horário
| Sobre meu rim 
| Um labirinto
| Sem entrada 
| Um versículo
| Da chama 
| Sagrada 
| Do amor 
| Prostituto 
| De minh ‘alma
| Brande 
| A espada 
| Da justiça 
| Do Dharma
| E me entrega 
| Festim 
| Brio 
| Não se compra 
| E identidade
| Não se pega 
| Se  paga
| Eu perdi a minha 
| Em alguma estrada 
| Entre aqui 
| E meu jeans  


<a href="https://instagram.com/dastavio"><i class="bi bi-instagram"></i></a>
