---
title: "O mergulho"
author: 
  - name: Pedro Santos
---

Depois de muito matutar, Clara amontoou toda coragem que tinha e, finalmente, pulou na piscina. As pernas brancas se desfiguraram debaixo da água gelada, trêmulas, tortas em relação ao próprio corpo. O sol se refletia sobre a superfície, fragmentário, mil soizinhos que Clara quebrava com os dedos que deslizava, criando redemoinhos. 

Somente na segunda semana de janeiro, o céu decidiu abrir, o calor tão prometido havia chegado. “Vamos, Clara, agora a senhorita não tem mais desculpas!”, a mãe lhe havia ordenado; na cabeça, um chapéu cinco vezes maior do que ela própria, um tubo branco e grande de protetor solar e uma revista de fofoca em mãos. Enfurnada no próprio quarto desde o início das férias escolares, sob livros fortes de travesseiro, Clara empalidecia, a pele morena agora com uma tonalidade fria. Demorou, mas Clara, enfim, acabou-se por convencida, chovera todo dia desde o natal, o que lhe custava? Decerto, um pouquinho de sol não lhe faria
mal.

A piscina do condomínio, geralmente branca e solitária, hoje pulsava colorida, com crianças e seus pais, uma multidão de maiôs e sungas. O falatório se exasperava, os assuntos da piscina e das espreguiçadeiras se unindo em uma massa sonora indistinta. O verão trazia consigo uma característica interessante, pensou Clara, “até quem nem pagando! não se olha, olha e finge que se gosta”. Sua mãe mesmo, Dona Vera, conversava com o filho da vizinha do quarto andar, Felipe, menino endiabrado que umas três vezes já quebrara a boneca de louça
de Dona Vera. E a mãe de Felipe, por sua vez, revezava elogios com o síndico, que — todos sabiam — se odiavam quase de vidas passadas, na briga se metiam até família e romance, num emaranhado de troca de farpas tão complicado que a vizinhança desistira de entender. E seguia-se a roda, aberto o céu e posto um drinque em mãos que todo o resto se esvaía.

“As pessoas são engraçadas”, pensou. Ela, por exemplo, mesmo três meses depois, só encontrava o olhar de Isabela de soslaio, a dor pela lapiseira emprestada que voltou comida ainda persistente. Não se tratava de rancor, era justiça dura e fria, quem comia seu material escolar aos plenos doze anos? Com o olhar, a punia. A água gelava a alma sem perspectiva de esquentar, Clara movia as pernas e braços como espaguete. Por algum motivo, isso a fez se lembrar da época em que passava os verões em São Sebastião, todo dia por um mês acordando para logo se jogar na água, ainda em jejum, de forma quase ritualística. No mar, a mão do pai secretamente a sondá-la, remexia as pernas e braços como o fazia agora, “olha, sou água viva!”, e ria.

A memória ardeu amarga na garganta, nunca gostara da praia. Voltando da orla à casa, tremia-se de raiva, “Areia! Areia pra todo lado!”, o corpo coçava cheio de pedrinhas, pingando água que se grudava à pele, mas não a limpava. “Eu nunca volto mais, mamãe, nunca mais!”, gritava sob o secador de cabelo, queimando quente, Dona Vera tão em paz que com o barulho ou não a ouvia, ou o fingia muito bem — assobiando Garota de Ipanema. De cabelo ainda molhado, deitava-se na cama emburrada, xingando a Deus e a todos os seus mares. Cinco anos depois e sem a casa da praia, somente aí que São Sebastião lhe soava doce. 

“Mimada, mimada!”, queria estapear-se. Ah, como o sol deveria estar lindo, rolando na areia quente, pingando d’água que gruda e não limpa. No entanto, a imagem lhe vinha à cabeça incongruente: São Sebastião não era da Clara de doze anos, e sim da de sete. Se imaginando agora, pisava sobre os castelos de areia, pegadas perpétuas no lugar de suas ruínas, calçava 35, será que a praia lhe aceitaria? O mundo lhe cabia de modo estranho agora, a boneca descansava na prateleira distante, os braços curtos demais para alcançá-la; sua dança não valia mais, só a elegantíssima, passos leves femininos de menina; os meninos olhavam-na perversos, desavergonhados, pediam para esconder suas vergonhas e, envergonhada, descobria que tinha algo de que se envergonhar.

“Se eu morrer, o que acontece com o tempo?”, perguntou-se meio tola, em um ímpeto de fugir de si mesma. “Nada”, a resposta era-lhe tão clara que doía e entristecimento toldava o sol em um eclipse tão tristonho que sorrir em meio ao escuro não produzia mais o efeito falso e plástico de outrora, a coceira infeliz do cérebro de felicidade induzida. Os meninos brincavam na piscina, rindo alegres, falando de carros e alienígenas de desenho, um leve e sorrateiro olhar compartilhado em direção ao inferior de uma mulher mais velha escapando por meio das conversas. Eles sabiam que doía? Clara ponderou sobre a questão, sem saber ao certo o quê doía, dentre tantas coisas o quê?, mas com certeza algo doía pungente e com uma urgência de alívio que nunca vinha, se dissipava e retornava sete vezes mais forte como uma fome prolongada. Não. Não? Não, sim, eles sabiam, mas a esse algo ignoravam porque podiam, porque em sua meninice viril e masculina apagavam-se a si mesmos por intermédio de um apagar do outro, com raiva colonizadora nos olhos bem-apessoados.

Clara olhou de volta para os adultos, o síndico agora conversando com outra vizinha, presa numa roda de amigos do marido, que confraternizavam gordos e espaçosos, todos eles, risada e cerveja, futebol e os seios da prostituta da rua ao lado, vagabunda, e a mulher no canto, dentes avitrinados, concordando apequenada. Olhando de volta para os meninos à sua frente, Clara não conseguia distingui-los dos homens. E se doía resignada, o sol caindo sobre a água e se quebrando em milhões, dançando.

A natureza celebrava? Em meio a tudo isso, crescia, sentia o corpo mudando rápido demais, a alma recém-nascida. Do outro lado da piscina, um espelho. Clara olhou para a outra garota, de braços cruzados sobre o busto, pensativos, os cotovelos apontando ligeiramente para cima como pontos de exclamação. O maiô cabia-lhe mal, sobrava um pouco ao lado. Sua pele era mais escura que a sua, os cabelos também, o rosto arredondado e jovem, tão diferente de si, velha e aguda como facas, franzina e alva com tanta pouca-idade. Mas, no entanto, doía. Doía também, a outra menina e vibravam juntas em uma sintonia estranha, os olhares não se cruzavam cruzando em um reconhecimento mútuo de existência solitária e tão física que o mundo em volta lhes parecia mais real, a água na qual pousavam tão mais água do que antes, percorrendo-as como um rio. O segredo latente e pulsante. Naquele instante, doía-se. Vida vomitava dentro da própria boca, doce e gosmenta e, ansiando tão forte quanto um desmaio, sabia sem uma palavra sequer que do outro lado alguém correspondia-lhe, doendo em resposta.
