---
title: Na Hora do Bandeco
author:
- name: Isaac Retiro Libera Martins
categories:
- CRÔNICA

---

> Senão chega a morte
> Ou coisa parecida
> Aparecida

Faria com certeza a fila ter valido à pena, foram mais de 15 minutos de fila porque estavam no começo do ano. “Os calouros logo cansam da novidade de comer por dois reais” disse Jorge, o que todo mundo concordou porque todo mundo sabia disso, não precisava Jorge ter dito, mas disse, e todo mundo concordou porque Jorge disse. 

Arroz/arroz integral, feijão, carne, opção: PVT, legume frio, pão murcho, fruta verde, suco de açúcar, as delícias do dia a dia, pelo menos não passavam fome, e é por isso que alguns oravam antes de comer, não todos, e acredito que nem mesmo a maioria, mas oravam, e havia também aqueles que não oravam mas faziam suas orações já comendo, os não-praticantes, como Maria. Maria era uma não-praticante, estava cheia de fé, cheinha, fé em Deus, fé em búzios, fé em astrologia, fé no dia de amanhã, fé nos orixás, fé no seu sangue latino, e fé de que fumar iria ajudar ela a parar de se cortar diariamente. Mas ainda assim, uma não-praticante. Me lembrava minha vó, que xingava, mas tava sempre com sua santinha por perto. Senhora de bem, sabe?	

Acharam uma mesa vazia para os quatro, raríssimo feito e impressionante acima de tudo, é muito comum termos 50 mesas com 50 pessoas sem que nenhuma olhe para a outra, e esse dia não era diferente, mas pelo visto havia menos de 50 pessoas, provável, não contei. Mas os quatro acharam uma mesa, os quatro: Jorge já foi citado, Maria Maria já foi analisada, agora só falta eu contar de Luís e de Ana. Luís é o jovem de bigode. Ana eu não sei direito, nunca falei com ela, mas Ana é bonita, e acho que inteligente, pelo menos nunca a vi estressada com as provas, o que eu acho admirável acima de tudo. 

Dos quatro, dois eram vegetarianos: Luís e Maria, Luís porque gostava de animais, Maria por fé. Jorge pegou o PVT porque não gostou da carne do dia. Ana só não ligava e comia o que tinha. Todos com seus sucos, suas bandejas com prato em cima, com saladinha. Olhavam um para o outro e falavam coisas. “Porque o Joaquim ensina muito mal, não consigo aprender”. “Mas a festa foi incrível, eu nem sei quem beijei”. “Eu não aguento mais esperar pelo show de Domingo”. “Só o Luís que fica quieto na dele, por que não fala mais? Tá preocupado com a prova?”. “Só quero ficar quieto”. “Tá bom né”. 

Levanta um, pega suco, levanta um, pega água. Pega um celular, lê a tela. Jorge olha pra Luís, Luís olha pra Jorge.

Luís pula com o garfo para cima de Jorge. Enfia-lhe no olho direito e o sangue jorra em cima do arroz de Maria. “Ah não… eu espero que o arroz esteja gostoso”. Ana se levanta pra pegar mais suco, o arroz tava seco.
