---
title: Relações alcoólicas
author:
- name: Mariana Yumi Sadoyama
categories:
- CONTO

---

Semana passada, visitei um antigo amigo, Arthur, advogado formado com carreira já traçada. Bom homem, ele. E como todo homem digno que se preze, apresentou-me sua adega de vinhos mais caros e difíceis de comprar.

Embalagens com aqueles escritos à mão, imagem bem preservada. Nada de marcas ou manchas, isso estraga a vontade de beber. Que me perdoem os "desconstruídos", mas quem deseja experimentar algo empoeirado por fora? Admiramos pelos corredores todos aqueles vidros delicados ao toque, enfileirados e imóveis, dispostos para quando a sede do vinho aparecesse. 

Mas por falar a verdade, os gostos são quase todos iguais. Suco de uva o qual desce, fica o amargor e vem a sensação quente na garganta. A principal graça está em obter, não em consumir. 

É fácil assim julgar pessoas pelas suas coleções de vinhos durante a vida. Os que vestem ternos e são bem engravatados, geralmente têm as melhores e mais bem selecionadas.
Arthur se divorciou pela terceira vez, disse querer ir atrás daquela loura de 20 e poucos anos enquanto dava goles incessantes na bebida. Ela tem bons modos, adora vestidos caros, deve ser uma boa moça. 

A coleção de vinhos dele? Maior do que nunca.

<a href="https://instagram.com/lirio.vermelho"><i class="bi bi-instagram"></i></a>
