---
title: "a história de quem me traiu"
author: 
  - name: Anônimo
---

Sentada no banco da lanchonete Phillies, ao entardecer, encaro meu reflexo no vidro da janela. Pergunto-me se meus olhos castanhos ou se a minha pele pálida fazem com que eu pareça tola. Fiz-me de tal, mas eu sempre soube de todas as mentiras que ele carregava no paletó, sempre que chegava tarde em casa, com hálito de cerveja. Mas eu fiquei quieta, mesmo quando ele se deitava ao meu lado, com aquele perfume feminino de lavanda que eu desconhecia. Eu fiquei quieta, para não causar nenhum incômodo. Sempre que eu lhe perguntava, percebia os olhares nervosos enquanto ele insinuava minha paranoia.

Durante meses, questionei minha própria sanidade. Perguntava às minhas amigas se poderia estar acontecendo algo, e todas diziam que ele me amava, que nunca faria nada do tipo. Afastei esses pensamentos, mas não consegui conter minha angústia quando encontrei um batom cor vinho embaixo do banco do carro. Ele sabia que eu nunca usava aquela cor.

E no dia em que o encontrei dormindo no nosso sofá, com a marca da merda daquele batom no pescoço, eu estourei. Acordei-o com o som de uma garrafa de vinho quebrando-se contra as paredes brancas da cozinha, manchando-as da mesma cor do batom daquela outra. Ele correu até a cozinha, me perguntando se eu estava louca.

- Louca? – gritava, enquanto jogava mais coisas contra ele. – Louca? Eu? Imagina! É tudo coisa da minha cabeça! Você que é um santo! Eu sou a noiva histérica que fica inventando coisas!

Fui para o nosso quarto, onde dormimos juntos por pelo menos um ano. Desfiz os lençóis, jogando as cobertas no chão, junto das roupas dele, que estavam no armário. O terno, que ele usava no dia em que me pediu em casamento, foi jogado pela janela. Ele gritava algo, mas eu não escutava. Na minha cabeça, só conseguia pensar nele, deitado com outra, que gastava o batom em seus lábios, perfeitamente macios. Em seus cachos sendo desfeitos pelas mãos de outra mulher, e nessa mesma mulher sentindo o cheiro do homem que eu amei por anos. O homem que chegava em casa, nos primeiros dias do nosso noivado, dizendo que eu era a mulher da vida dele e que passaríamos o resto das nossas vidas juntos, e que mentia na minha cara quando eu perguntava se estava acontecendo alguma coisa. Não fui enganada só por ele, quando ouvia suas longas mentiras sobre como seu amor por mim era raro como uma jóia, mas também por mim mesma. Eu ignorei minha intuição e preferi acreditar na realidade distorcida que ele me oferecia do que nos detalhes que tudo entregavam. O perfume que eu não usava, o batom que nunca foi meu. Tudo tão claro e, ao mesmo tempo, tão turvo. 

Naquele dia, saí de casa enquanto ele me seguia, implorando para que eu ficasse, que eu o perdoasse. Ignorei suas súplicas, peguei o carro e fui para a casa da minha irmã. Lá, me desfiz em lágrimas no travesseiro, e mal dormi, pensando o que eu havia feito de errado. Mas ele estava tranquilo, ao lado da amante, descrevendo como eu havia surtado, colocando seus cabelos para trás da orelha e beijando sua testa.

Se ele sofreu, eu acho que não, pois dias depois, ouvi de uma amiga que ele estava numa loja de discos com uma loira, usando o batom que encontrei debaixo do carro daquele filho da puta. Pergunto-me como ela aceitaria beijar o homem que trai a própria noiva.

A traição que mais dói não é o sexo com outra. Lógico que me enoja imaginá-lo deitado despido com outra mulher, mas o que me dilacera é saber nada importou eu ter estado ao seu lado quando ele mais precisou. É saber que essa dor agora me rasga, não o assombrará, não irá sequer despertá-lo a menor gota de remorso, talvez até o divirta. Ou, talvez quando a validade expirar, ele se dê conta de que nenhuma outra mulher impedirá o caos que ele carrega consigo de explodir. E aí ele irá tentar mudar o final da história.

Meus pensamentos são brutalmente interrompidos quando um ônibus, em alta velocidade, passa em frente a lanchonete, bloqueando meu reflexo momentaneamente. Seco minhas lágrimas ao ver o garçom se aproximando da minha mesa, e ele me pergunta o que eu gostaria de comer, e peço só um café sem açúcar.

Enquanto saboreio o amargo da bebida, meus olhos correm pela parede amarela do estabelecimento, e eu simplesmente não consigo parar de pensar nele. Talvez eu apenas esteja sendo boba, mas a cor me lembra ao vestido que ele comprou para mim no meu aniversário de 23 anos. Desenho mentalmente tudo o que passamos juntos durante os anos, e fico me questionando como alguém que me declamava poesias e trazia rosas do trabalho simplesmente iria mentir na minha cara, se esquivar das perguntas e me jogar à loucura. 

Meus devaneios morrem quando eu o vejo entrar pela porta do estabelecimento, vestindo um terno azul marinho e o chapéu que eu comprei para ele numa viagem à praia. Ele está com a cabeça baixa enquanto caminha em minha direção, e vejo que traz consigo um buquê de flores. Ele se senta no banco ao meu lado e me encara com o olhar taciturno, me pedindo perdão, somente com os olhos.

- Olivia... – ele começa. Reviro meus olhos e engulo seco; já sei o que virá pela frente. – Eu sinto muito pela dor que devo ter te causado. Eu sei que o que eu fiz é imperdoável, mas por favor, me dê outra chance – ele diz, segurando a minha mão sobre a luva.

Não. Eu não havia sido a coitada traída na história para ouvi-lo pedir pelo meu perdão com palavras tão pobres como as que ele escolheu agora. Viro a cabeça para a parede e continuo a comer, ignorando sua presença. Continuo a ouvi-lo falar e registro todas as mentiras que ele insiste em me dizer. A diferença é que desta vez, eu sei que não passam de palavras vazias. Ah, se eu soubesse disso antes!

Após um tempo, ele suspira, e escuto o som de seus passos indo embora. Depois de ouvir a porta fechando, olho para o lado, e ele não está mais aqui. 

<a href="https://instagram.com/lelesphotoalbum"><i class="bi bi-instagram"></i></a>
