---
title: ainda sobre você.
author:
- name: Allie Santos
categories:
- LÍRICO

---

Como um romper de minhas barreiras, soltando as águas de meus canteiros alagados e constituindo as várzeas de minhas emoções rasteiras, um intenso derramar de meus pesares sobre teus gestos lépidos.

Como milhares de carícias suaves em meu peito, cócegas em meu âmago que me roubam o ar e o dão a você. Invadem minha mente confusa de você, e só você. Como se não existisse outro alguém para mim.

Fazem borbulhar os sentimentos reprimidos, os choros mal contidos que serpenteiam por tudo que há aqui dentro. E há tanto. Tanto que nem cabe mais. E é por isso que tudo sai. Sai voando para minhas bochechas num rubor desavergonhado que me envergonha. Chega às minhas pernas que tremulam e ao meu coração que ralha, ensandecido, cansado destas borboletas que não o deixam ir sem levar junto a melodia de batidas que elas sempre dedicam a você.

<a href="https://instagram.com/allieversos"><i class="bi bi-instagram"></i></a>
