---
title: "Amar, verbo proibido: um pequeno comentário sobre Frederico Paciência"
author: 
  - name: Valentina Nicolino Pereira
---

O amor, enquanto objetivo coletivo de uma sociedade, é fonte de debates, reflexões e entretenimento aos que se importam minimamente com ele. Nesse sentido, muitas obras se inspiram nos dilemas do sentimento em diversos aspectos — um objeto quase místico para a literatura é o amor proibido.

Escrito e reescrito durante 18 anos, Frederico Paciência foi o conto em que Mário de Andrade mais se debruçou enquanto escritor; publicado postumamente, é uma ficção de tom memorialista sobre o romance entre dois rapazes do ginasial. Em uma São Paulo dos anos 1920, o relacionamento homoafetivo seria claramente reprimido e violentado. Aí temos a fonte da proibição — membros da comunidade LGBTIQ em geral foram, e ainda são, perseguidos e expulsos dos mais diversos ambientes, pelas mais diversas intolerâncias. Em um país moldado pela escravidão, misoginia e forte influência católica, marcado por um contexto histórico em que as sexualidades são conceitos recém abordados, o amor entre Juca e Frederico surge como inadequado.

 Juca, narrador do conto, coloca-se como o "tipo do fraco": "Ffeio, minha coragem não tinha a menor espontaneidade, tendência altiva para os vícios, preguiça." (Andrade, 1947). Já Frederico Paciência, objeto da paixão, é descrito como uma solaridade escandalosa — não era beleza, era vitória. Temos mais uma narrativa de opostos atraídos. Não podemos pautar o amor proibido somente na diferença entre personagens, que muitas vezes é catalisadora da paixão, mas podemos tratá-la como um fator de crises eventuais no desenvolvimento do amor.
 
Eliane Robert Moraes (2022) pontua que o conto se constrói a partir da tensão entre confissão e omissão — o caráter memorialista traz duas versões limitadas dos fatos: o lembrado e o reinterpretado. Isso transparece pelas ambiguidades narrativas de Juca, que nada mais são que fruto de sua melancolia por amar alguém que não pode ter. A autonomia afetiva dos rapazes não é respeitada, e com isso surge o sofrimento psíquico, recitado por Mário de Andrade de forma soturna, em um jogo de luzes representado pela descrição de espaços e personagens. A confecção do amor proibido é entrelaçada com diversas agressões e extremismos — a narrativa se constrói por opostos.

> Passei noite de beira-rio. Nessa noite é que todas essas ideias da exceção, instintos espaventados, desejos curiosos, perigos desumanos me picavam com uma clareza tão dura que varriam qualquer gosto (...). No dia seguinte, Frederico Paciência chegou tarde, já principiadas as aulas. Sentou como de costume junto de mim. Me falou um bom-dia simples mas que imaginei tristonho (...). Como que havia entre nós dois um sol que não permitia mais nos vermos mutuamente. (ANDRADE, 2022[1947], p.219, grifos meus)

Ao longo do conto, os amantes passam por aproximações e distanciamentos, de forma que Juca, quase perturbado pela relação, escorrega lentamente em uma espiral melancólica, a ponto de considerar que um telegrama — informando a morte da mãe de Frederico — é um convite para juntar-se ao amigo no Rio de Janeiro após sua saída de São Paulo.

 A mudança de Frederico Paciência para o Rio de Janeiro, seguida da morte da mãe, é o ponto final no relacionamento entre os rapazes, que deixam de trocar correspondências quando Juca desiste de perseguir o antigo colega de sala em outro estado. O distanciamento físico é a primeira rachadura no amor entre as personagens, que se quebra totalmente com o falecimento da mãe de Frederico. "Nós nos amávamos sobre cadáveres. Eu bem que percebia que era horrível." (Andrade, 1947). O amor sobre cadáveres escancara o entrelaçamento entre a paixão e a violência, o sensível e o grotesco, de forma que o amor, uma vez proibido, se aproxima do desagradável lentamente até que não haja distinção.


| Referências bibliográficas
| 
| MORAES, E. R. (org). Seleta Erótica/Mário de Andrade. São Paulo: Ubu Editora, 2022.

<a href="https://instagram.com/valley.n.tina"><i class="bi bi-instagram"></i></a>
