---
title: "Amor"
author: 
  - name: Xico
---

Quando o amor bate na porta, a cabeça gira em emoções, o suor frio da ternura incendeia o corpo em uma faísca de felicidade. Quando o amor quer a sua vez, não se medem os esforços, não se conta mais o tempo como antes, os segundos são eternos na saudade, e os anos voam nos minutos que se sente a presença. Quando se ama, se pensa em todos os outros amores, e em todas as outras histórias, e por fim conclui-se: um novo tempo está nascendo. Quando se ama, as flores têm mais cores, o corpo desafoga do cotidiano, as idas e vindas são anestesiadas pela química que se forma, e quando o horizonte se torna rosa e laranja com o início da noite, se pensa em todos os momentos que estão por vir com a pessoa amada. O frio noturno é menos intenso, e a chama do dia vem queimando no Leste.

O amor tem direção?

Quando o mundo se fecha para nós, o amor pode ser a única chave para sair do abismo que se forma entre o universo interno e o externo, a mente enfim se ilumina para o que está vindo, e o que se imagina não é mais o pessimismo constante, mas se substitui pelos melhores cenários na nossa cabeça, daqueles em que todas as cores vibram em uma sintonia combinante e que nos fazem desviar da realidade, mas não por muito tempo, pois a realidade é mais linda de se viver quando o amor chega.

E a vida caminha para uma nova rota, um novo destino, um caminho puro e sem obstáculos para aqueles que tem a coragem de abrir os seus corações, o amor não contagia, não se contrai e nem se adquire. O amor se aceita, e não se pode vir sem que estejamos prontos para o que ele nos causa, e é preciso cuidado e zelo para aceitar esse novo balanço que transborda do infinito e nos pega quando menos esperamos. Sim, o amor é uma visita, uma visita inesperada, quando pensamos que nada mais pudesse vir, e então nos preparamos para que ele se manifeste na sua forma mais pura, não há como vencer isso.

Quando o amor por fim se manifesta, não há mais o que temer, se o fim que dizem está mesmo chegando, que seja acompanhado, e que não se pense nele a todo instante, pois só se pensa em amar.

Quando o amor bate na porta, não há mais para onde correr.

<a href="https://instagram.com/xicoszn"><i class="bi bi-instagram"></i></a>
