---
title: "As faces do amor"
author: 
  - name: Ioná Vasconcellos
---

As faces do amor

Ao longo do tempo lhe foi dado diversas definições, sendo essas, tão distantes e dissemelhantes umas das outras, e de proporção tão abstrata - individual e compartilhada - que acabaram por torná-lo em uma grandeza inefável.
Seria o amor então, resumido apenas ao belo e a incapacidade geral dos indivíduos de descrevê-lo por completo? 
Dentre as muitas teorias e interpretações do sentir possíveis, algumas se destacam, sobre a percepção dessa que aqui vos escreve. 

Certa vez, Shakespeare apontou: "A verdade é que não te amo com meus olhos que descobrem em ti mil defeitos, mas com meu coração, que ama o que os olhos desprezam", nesse excerto o autor revela uma face do sentir, em localidade comum de se dizer estar.

Mas afinal, o amor está ou não está localizado no coração?

Certamente não está nos olhos, segundo o que diz no trecho acima citado; mas não é o que diria Nando Reis, em uma parte da música Do seu lado, onde canta: "Só que precisa cuidado pra perceber que olhar só pra dentro é o maior desperdício. O teu amor pode estar do seu lado…" e assim, o amor ganha mais uma face: a dos olhos de quem vê. Dizem os apaixonados, que nem todo gesto, palavra, música ou poesia descreveriam tão bem o amor, quanto um simples olhar. Há quem diga ser arte, o ato de reconhecer o amor no olhar, há quem enxergue com os olhos, os mil defeitos que Shakespeare declarou desprezar, e há quem despreze a possibilidade de amar, sem enxergar o amor com o olhar.

E sobre amar com o coração?

Um pensador de nome Zoncro, eventualmente escreveu: "Não te amo com coração, pois um dia ele vai parar de bater e o meu amor por você morrerá. Por isso te amo com a alma, pois embora ela se vá... aonde quer que esteja ela continuará a te amar para todo o sempre", permitindo com esse dizer, que seja possível reconhecer e explorar a presença de uma outra face do sentir do amor, onde a localidade não se encontra no coração, mas sim na alma. O autor descreve um amor infinito, descreve a utopia da existência de um "sempre", e uma intensidade, que só é encontrada de fato, da forma descrita.

Então como proceder com aqueles que são descrentes da alma e se dizem desalmados? Seriam esses incapacitados de sentir o amor? Ou ainda assim, o amor poderia se instalar pois a descrença não exclui o fato de haver a presença? Mas quem poderia afirmar se existe ou não uma presença de fato?

O direito de amar verdadeira e profundamente, só é concedido àquele que declara o sentir em sua alma?
Fazendo uma analogia ao conto _A terceira margem do rio_ de Guimarães Rosa, há a presença  do narrador personagem -um filho abandonado por seu pai logo na infância- que semeia um amor incondicional pelo pai, e diz aprender coisas com ele durante  toda a vida, mesmo este encontrando-se ausente durante todo o percurso do conto. O mesmo cria dentro de sí, um sentimento para com o pai. O personagem também produz cenas utópicas e inexistentes em sua mente. E o pai, possivelmente localizado numa espécie de umbral, não demonstra no decorrer do conto, sentimento algum para com o filho. O que vem a nos revelar uma face do amor, onde o sentir do amor pode vir a estar presente, por exemplo, em uma projeção inventada pelo ser. 

E o que dizer do amor? 

De toda forma, se faz necessário ao que diz sentir o amor -independente de sua face -  entender, que sempre haverão, incontáveis formas de descrever o mesmo sentir, e que não necessariamente essas, hão de estar corretas ou incorretas. As faces do sentir, assumem uma infinidade em sua descrição e não se faz necessário que haja um julgamento de quais dessas terminam por ser verdade ou não.

Não hei de afirmar ou desafirmar quaisquer que sejam as faces do amor que cheguem até mim. Escrevo porque desconfio que haveremos de nos desprender desta terra, antes de que seja possível se ter certeza sobre todas as faces do sentimento que rege esse texto.

E por fim, ainda parafraseando Guimarães: "Eu quase que nada não sei. Mas desconfio de muita coisa". Encerro dizendo que anseio que o amor, nunca deixe de nos revelar novas faces, e que sejamos capazes de reconhecer cada uma delas como sendo única.
