---
title: "[interlúdio.]"
author: 
  - name: Allie Santos
---

Foi no embalo das águas de março.

Na iminência do outono, no balanço dos meus cadarços que viviam desamarrados, noutra poesia sobre amor e abandono. Foi como num sonho, tão leve e tão rápido, como um suspiro ou um tombo. Só um respiro, bem mais como um assombro. A dor mais bonita que eu já pude sentir até aqui, o choro mais íntimo que eu já me permiti dentre tantos outros textos vazios que eu já rabisquei pra ti.

Nas palavras bambas, nos sentidos incertos, nas inseguranças e até em momentos mais libertos, quando o externo se fez presente e se fez ficante e se fez ficando e... Ficou. Ficou e eu fui. E você deixou. Por que era tão bom me ter tão longe, mas ainda por perto? E foi ali que eu descobri o horror que é amar de peito aberto. Que com você nunca seria apenas sobre borboletas no estômago, mil rosas roubadas e frases melosas numa tela acesa à noite. Que todo o prazer da minha companhia não seria o bastante pra te afastar da boemia dos braços dele. Ou dela. Ou deles. Porque o "nós" nunca foi tão bom quanto o "eles", eu acho. Se fosse… Bem, você teria ficado (?). 

<a href="https://instagram.com/autoralliez"><i class="bi bi-instagram"></i></a>
