---
title: "Ngiyakuthanda"
author: 
  - name: Figo Maduro
---

::: {#text-center}
| **ii**
| me sobra tempo e me desvairo pelo transporte meio que inconsciente de mim mesmo, como um espectro que deixa ectoplasmas pelos livros que abro no metrô e quando menos presto atenção nos sons ao meu redor e nos entes e etc me vejo esperando alguém
| 
| apago.
|
| imatéria de quartzo pálido: minha mente
|
|  e acordo de repente longe de tudo no ócio frágil e vejo ela arrastando seus pés nos meus, levando suas mãos geladas ao meu bolso e fazendo murmúrios de fones glotais ingressivos sonoros. cliques.:
|
| - inhá! \[ŋ̊\]
|
| rimos feito bobos loucos tolos do sentimento mútuo da reciprocidade rouca que se cala em miúdos já que da vergonha faz sua voz
|
| o íntimo é menina universo de esclarecimento; ocorrência de conforto
|
| - então o íntimo é mãe!
|
| - e mãe é tudo que tem sentimento então é também.
|
| e abro agora meus olhos e não sei bem como descrever a verdade e não o real; a linguagem me mata, me seduz, me despreza. eu a desprezo: objetiva burra limitada impositiva! quisera eu só pensar e transmitir! abstrair sentidos e sentimentos e
|
| - eu gosto disso do tato inadequado da sua bochecha encostando na minha. me lembra os tubarões que não querem machucar só sentir e encostam o nariz na gente e lembra? a nossa geração não nasceu mais Gente e por isso eles mordem e matam, não são maus apenas justos
|
| ruim é nós
|
| respiração profunda atestado de coragem tensionando suas mão em meus bolsos para esquentar aproximando e aproximando suas engrenagens e tecnologia! encostando a máquina de respirando nas dobras das minhas máquinas de vendo e de beijando e se debruçando debruçando com o fino tocando da ponta da máquina de suspirando reconhecendo matrizes e trópicos demográficos e geográficos da minha máquina de expressando é um avião ou uma nau e você me mapeando e imprimindo e me roubando me encontrando-me na sua busca às Índias pois amor é matéria-prima e eu desejando
|
| foi essa a primeira vez que fizemos amor que pra mim é mecanismo que pra mim é engrenagem que pra mim é indústria e é necessário humanizar as máquinas - mais simples que as elites - aliás trabalhamos o gozo, o tempo, o sensível e te sinto aqui com seu nariz passando e turistando os campos de centeio e produzindo cercamentos no meu rosto ou criando comunidades autóctones e adquirindo esse meu conhecimento ancestral no nariz e sobrancelhas árabes nos lábios carnudos pretos nos olhos indígenas e na minha pele terrosa e bem que o boiadeiro disse: tá no meu sangue transmitir conhecimento
|
| pois ser amor é sofrer a dor de ser Humano esvaziado de Ser e cheio de desHumano duvidoso esperançoso em seu feitiço e ser amor não deve ser dor amor não deve Ser amor não deve
|
| é
|
| - encosta seu pé no meu, nossa dança monossilábica, nosso caso tateante ou tonteante...
|
| - tediante?
|
| - destoante, matéria fina e cristalizada. encosta seu pé no meu, porque faca no peito é a dor da traição foi o que me ensinou o ponto do terreiro então me ensina segurança...
|
| - ser criança... matéria obscura ou muito Clara; resíduo aleatório de outros resíduos de memória afetiva ou genética
|
| ninguém nunca no mundo em tempo algum nasceu Gente só nasceu e quando foi pra andar só andou
|
| assim é com o amor também
|
| e te segurando o dedão com o meu e nossos pés parindo homens mulheres caboclos católicos macumbeiros indígenas do Nordeste ao Pará à Minas até o Grande ABC
|
| - essa é a segunda vez que a gente faz amor
|
| você só dorme se for assim
|
| eu não durmo
|
| melhor: não acordo e não que viver contigo seja um sonho menos ainda é um pesadelo
|
| só é
|
| e as coisas são o que são serpentes flechas pela terra pele chão
|
| ou quem sabe você é, eu sou... elas não
|
| DITADO: O QUE É QUE NÃO SE EXPLICA MAS SEMPRE SE ENTENDE
|
| o nosso amor no frio ou no calor cansado com esforço ou de saco cheio
|
| delícia do céu dentro do coração e por fora no peito aqui na esquerda ideológica de nós infinito particular. eco de vazio cheio de paixão e na terceira vez que fazemos amor no começo linear do tempo do fio transparente:
|
| - Com você eu me sinto menos Eu e mais Gente.
:::

