---
title: "notas sobre o amor"
author: 
  - name: Letícia Montes
---

| dizem que amar é doloroso 
| e se jogam no fogo os apaixonados;
| queimam-se por medo
| mas também por desejo:
| o amor é na linguagem poética
| essa chama —
| trêmula, cega de si, destruidora —
| o amor do poema move homens
| fomenta guerras   
| enlouquece toda a gente
| a murmurar pelas esquinas da cidade
| ou em campos floridos —
| o amor não escolhe coração 
| para plantar essa semente inflamável 
| toma um por um em marcha fúnebre 
| ninguém escapa desse desastre —
| 
| porém vive no amor
| uma doçura tenra
| escondida atrás da chama —
| a fogueira ilumina 
| esse detalhe antes insípido —
| delicada garoa fina
| do tipo que não te livra do fogo
| mas te faz balançar ao redor dele —
| é este sabor que procuram os apaixonados 
| na ponta da língua, suave agrado 
| ao corpo incendiado 
| quem sabe um frescor
| um alívio do medo
| por um instante que seja
| uma descoberta silente 
| clareando o dia.

<a href="https://instagram.com/lelesphotoalbum"><i class="bi bi-instagram"></i></a>
