---
title: "Nu Inacabado, Oscar Pereira da Silva"
author: 
  - name: Pedro Santos
---

É lindo. Mesmo por trás do vidro. Cada traço no corpo violeta-rosado fala; o olhar branco na cara branca, como o inacabado esparso pela obra, quase que intencional, faltando — como a vida. O pensamento repassa em minha cabeça, duas ou três vezes e o amasso antes de você me perguntar: “Vamos?”. Te observo concentrado no quadro, eu nu e envergonhado. A Pinacoteca está cheia, é sábado e a entrada é gratuita. As pessoas andam pelo santuário de silêncio farfalhando e os celulares são tantos que é como se fossem câmeras antigas, clicando a cada foto tirada, à altura dos olhos. Descemos na estação da Luz, vindo da sua casa em Pinheiros. Eu nunca tinha parado lá, então fez questão de pegar o metrô no nosso caminho. Éramos ingleses perdidos sob os arcos férreos, nem mais parecíamos estar em São Paulo. Esqueço que o mundo é tão grande.
Eu me preparo para seguir para a próxima câmara, mas você permanece.
Sinto que quer que eu diga algo então eu digo:

“É bem bonito.”

“Sim,” você concorda e morre ali.

Mas não anda e permanece, de novo. Permanecer contigo aqui parece algo constante de um jeito repetido, e não contínuo. O relógio me avisa que estamos há sete minutos olhando um nu inacabado em meio de dezenas de nus finalizados classicistas. A mulher olha para o lado e para baixo, suas costas viradas para nós e está — óbvio — nua. O que lhe chama tanto atenção? Minha brincadeira cai no ditado e sinto um pouco de verdade nela, mas chega a ser ridículo: a vida? Você sempre amou peculiarmente, às vezes me pergunto o que isso indica sobre mim.

Suspirando devagar, você segura minha mão. Começa pelo dedinho como se fosse um segredo. O quadro desaparece, de repente sou eu e seu rosto. A barba feita, a pele cujo toque tanto sei, seu cabelo a cortar, as orelhas alvas coladas, a boca entreaberta de perfil, seu olho aguado... E me bate: eu te amo e não te Percebo. Você é qualquer descrição que fiz, e eu desabo sorrindo sem que você sequer veja. E é estúpido e é mais do que eu possa suportar. A mulher nua volta a foco. Por que inacabada, por que violeta e rosa e branca, por que de costas, por que o olhar terno-penetrante-vazio-sóbrio? As perguntas vão degringolando e tudo que encontro é pouco: 1865–1939. 1939, o ano da pintura. Tentei descrevê-lo tanto e nada que lhe fizesse jus, os contos me falham e o romance nosso, no papel, natimorto.

Você me puxa mais perto e o dedo-anzol se transforma em um abraço, obstruindo a vista da turista atrás e foda-se: eu o amo.

“Tudo bem?”

Sua voz abafada através da corta-vento ressoa até meu crânio. Dizer sim parece tão óbvio, mas o óbvio mesmo é não-dito.

“Ei, Pedro...”

Você me levanta o queixo e eu nego, nego e nego até enfim aceitá-lo e não é tarde demais. Meu nu inacabado.

“Vamos?” você diz.

O paulistano é irritado, outros atrás já resmungam alto, reclamando, mas não é por isso: eu sei. A mulher de novo me encara e dessa vez estufo o peito e a saúdo, com os olhos quase como os seus e, mesmo sabendo que nunca os terei, por um momento me conforto na sua pele emprestada — e cedo. Depois vamos ao Museu da Língua Portuguesa, comeremos numa padaria por perto e voltaremos pela Amarela cansados, mas eu cedo, e é lindo. Lindo.

“A gente pode ficar mais um pouquinho?” pergunto e seus dentes abrem em
um coro.

E olhamos. Música, encanto, sorrisos.

