---
title: "O amor"
author: 
  - name: Sea Stars
---

O amor poderia ser descrito como algo sorrateiro, que pode aparecer a qualquer
momento, em qualquer lugar e forma, você querendo ou não.

O amor pode aparecer em um ponto de ônibus e um petisco no caminho para casa,
Em um parque de bairro desprezado ou em um shopping no centro da cidade em um
sábado,
Em uma energia inexplicável que lhe acompanha a mais tempo do que o esperado,
Ou em um rascunho de algum sonho "sem futuro".

O amor pode vir te acompanhar e pedir atenção ao longo da sua rua,
Vestir roupas meio folgadas ao manobrar um skate na praça ou parecer saído de uma
linha estética em uma cafeteria ao meio dia,
Ser uma sensação de acolhimento que não se pode ver a todo momento,
Ou se explodir em um pico de inspiração para aplacar a escuridão.

O amor pode parecer um animalzinho do qual você cuidou sem compromisso,
Um garoto bonitinho ou uma garota linda que gostaria de ter conhecido,
Uma entidade mística que lhe segurou em seu momento mais sombrio,
Ou os sentimentos que você transformou em algo magnífico.

Eu poderia definir o amor em diferentes perspectivas. Todavia, qual delas seria a minha
definitiva?

Costumava acreditar que o amor aparecia inesperadamente, no lugar que eu menos
gostaria,
Que vinha como uma supernova, bonita de observar, porém destrutiva a amar,
Que parecia dilacerar e queimar até lhe apagar.

O amor apareceu em uma manhã fria de fevereiro,
No meio de um corredor cheio, por um segundo que pareceu durar um infinito inteiro,

Como aquelas coincidências destinadas de filmes estrangeiros.

O amor veio até mim em uma noite vazia, durante uma partida de alguma jogatina,
Enquanto eu temia estar sendo consumida por aquela sensação tão conhecida. Apesar de
não me lembrar disso ao conversar com ela.

| O amor parece com uma garota de cachos pretos perfeitos,
| Uma paixão incondicional por maquiagens e bichinhos fofinhos,
| Que crê em entidades da natureza e na bondade e potencialidade das pessoas,
| independente de quaisquer coisas,
| Um gosto peculiar por roupas, sobretudo as cor-de-rosa,
| Com a inocência de uma criança e a bravura de uma mulher que levou uma vida dura,
| Que sonha em despertar o coração das pessoas em um palco de teatro ou nas entrelinhas
| de algum parágrafo.
| Se parece com beijos em varandas ao pôr-do-sol e nas escadarias de medicina, ouvindo
| as minhas bandas favoritas,
| Flores amarelas no gramado da escola, emaranhadas nos meus brincos prateados,
| Metáforas astronômicas e citações de literatura e personalidades da cultura,
| Conversas futuristas em madrugadas escuras, me empurrando em direção aos sonhos
| que afundei em minhas águas sombrias,
| E questionamentos ceticistas sobre almas gêmeas de outras vidas.
| Se parece com aquele tipo de coisa que se encontra uma única vez na vida, e que lhe dá
| um novo motivo para levar a sua existência finita.

Acredito que o amor seja sincero e que te faça sentir o que há de mais belo,
Revivendo as estrelas mortas pelo tempo.

Você mudou minha perspectiva, revirou a minha vida e mostrou a minha melhor versão.
Você é a minha real definição.


<a href="https://instagram.com/meet.meinthesea"><i class="bi bi-instagram"></i></a>
