---
title: '&nbsp;'
author:
- name: Ela Morassi
categories:
- POEMA

---

| Queria mesmo era saber
| lidar com a raiva.
| A tristeza? Sou ótima nessa.
| Ansiedade? Entendo o protocolo.
| Culpa? Até essa sei usar,
| nutrir, me corromper e, por fim,
| me perdoar.
| 
| Agora a raiva…
| O que faço com ela?
| E não me venha com 
| “respire fundo, conte até 10”
| que essa merda o patriarcado
| fez questão de deixar marcado
| em cada aspecto da minha socialização.
| 
| O que eu quero, de verdade,
| é saber como expressá-la.
| 
| Sabe qual é a minha resposta
| FÍSICA pra raiva? Chorar!
| E você sabe como é ter
| como única resposta 
| pra raiva
| o choro?
| É patético.
| 
| É odiar seu primeiro namorado
| e chorar de raiva numa briga
| e ser lido como terna.
| Ter tanta coisa presa na garganta
| que não consegue nem dizer que
| NÃO! Você não quer o perdão desse 
| machistinha de pica fina!
| 
| … E a verdade é que eu 
| nem lembro daquela pica.
| 
| Às vezes parece inevitável, isso de
| cair na referência unilateral da raiva, 
| essa coisa máscula, viril, violenta:
| chutar cadeiras, socar paredes,
| aumenTAR A VOZ.
| 
| Mas tentar fazer isso 
| sendo mulher 
<p style="text-align: left">
| [ou pelo menos sendo lida como tal]
</p>
| é condenar-se ao título de desequilibrada.
| Dramática. Histérica. Louca!
| “Cê tá de TPM é??”
| 
| Um… Dois… Três… Quatro….


<a href="https://instagram.com/elamesma.eu"><i class="bi bi-instagram"></i></a>
