---
title: Crônica de uma paulistana falsa
author:
- name: Mari Rodrigues
categories:
- CRÔNICA

---

*[publicado originalmente em 18/02/2013]*

Tive hoje uma péssima noite de sono. O tranquilizante me faltou. Acordei com náuseas, com uma dor de cabeça horrível. Pensei que era apenas tomar o meu café da manhã e pronto. Ledo engano. Só piorou a situação.

Perdi o ônibus, fui andando até o trabalho porque estava inquieta. Chego, começo o meu trabalho, e logo me dá uma vontade terrível de vomitar. Quase acontece. O mal estar persiste. Resolvo ir ao hospital.

Três horas de espera. Três. Hospital mal equipado, médicos mal educados, funcionários despreparados. Que mais eu poderia esperar de um hospital público? Chuva. Eis que ela surge, instantaneamente. A tempestade tropical que faz árvores caírem, os bueiros entupirem, o trânsito da metrópole ficar ainda mais caótico.

A metrópole. Ela, tão esplêndida, tão cheia de urbanidade, tão cheia de modernidade. Dominada pelo barulho inquietante das buzinas, pela água que escorre dos cantinhos mais imprevisíveis e pela barbárie que é o retorno para casa numa cidade de crescimento desordenado. É, aprendi a odiar São Paulo em certas ocasiões, um ódio que um paulistano legítimo sentiria.

Agora estou em casa, e a chuva de repente vai embora, deixando meu sapato inutilizado e minha calça para lavar. Hora de pôr novamente a saia que mostra meus pelos nascentes.

Para hoje só me resta saborear uma deliciosa pizza e ir dormir. Porque amanhã tudo começa novamente.

<a href="https://instagram.com/marimuer"><i class="bi bi-instagram"></i></a>
