---
title: HORA EXTRA
author:
- name: Dentinho
categories:
- CONTO

---

| — A gente tem que dar um jeito nessa brincadeira! — Disse um trabalhador. 
| — É, realmente a coisa tá estranha. Tô até fazendo serviço que é pros caras do andar  de cima fazer. Por acaso eles vão fazer o meu? — Respondeu um outro.  
| — Mano, eu tô ligado nesse trampo aí... Chato que só a po... 
| — Demais. Dar o serviço dos outros pra gente eles querem, aumentar nosso salário já é  outra história... 
| — Acho que a gente devia se organizar pra conversar com o supervisor. Não acho certo  essas coisas que eles andam fazendo com a gente. Só essa semana, já fiz seis horas  extras contra minha vontade e ainda é quarta-feira. Sempre que tá quase na hora de ir  embora o supervisor joga um monte de coisa pra eu fazer e fala pra eu ficar a mais,  sendo que não posso. Se tivesse banco de horas nessa empresa eu teria direito a uns  três meses de folga, de tanto trabalho que esse cara me dá. — Comentou Lúcia, até  então calada. 
| — Eu percebi isso também. Os cara sacaneia muito e esse supervisor aí é pior que o  Diabo — Retrucou o primeiro trabalhador. 
| — Ele é o Diabo e a gente tá trabalhando no inferno — Disse o segundo. 
| — Eu só não me demito e busco outro emprego porque acabei de comprar esse celular  e tenho que pagar as parcelas — Comentou Lúcia. 
| — Eu tenho que pagar a escola dos meus filhos. Se não fosse isso, eu já tinha vazado — Acrescentou Mário, o segundo amigo. 
| — As contas lá de casa são o que me prendem aqui. Tenho que alimentar minha família... — Colaborou Joelinton.  
| Entra na copa bem de mansinho o autoritário funcionário-supervisor:  
| — E aí, galera... 5 minutos aqui, já!! Hoje a gente tem bastante trabalho pra sair. Vocês  conseguem ficar um pouco a mais? 
| — Hoje não dá. — Responderam os três, em coro. 
| — Que falta de sangue, hein? — Disse o supervisor.  
| Faltando 15 minutos para o fim do expediente ele traz mais trabalho para os três  trabalhadores, mas em vão. No fim do expediente, todos vão embora para suas casas. 
| Amanhã será outro dia que inevitavelmente chegará. 
