---
title: Nóis contra eles
author:
- name: Gabriel Leal
categories:
- CONTO

---

| — Essa porra desta obra é o mais completo absurdo!
| 
| — Lá vem você de novo com esse papo. É a prefeitura, vai fazer o que?
| 
| —Tem um ano inteiro sem parar disso e pelo que eu tô sabendo, não tem previsão pra acabar.
| 
| — Vai lá falar com eles, ué.
| 
| — Como que a gente não se junta pra impedir? É o que me deixa mais puto. Ninguém aqui tem coragem de tomar uma atitude, enquanto isso, esse pessoal faz o que quer.
| 
| — Já falei que é a prefeitura; se a gente se junta e isso fica público é pior, vão falar que a gente não quer que todos tenham acesso até aqui. Hoje em dia é assim, o máximo que dá pra fazer é reclamar, mas só entre nós, que ninguém ouça isso.
| 
| —Ué! Eu não quero que eles tenham acesso mesmo, agora não pode mais? Ter opinião?
| 
| —Ter você pode. Eles só não podem ficar sabendo.
| 
| —E outra, é um metrô que vai do nada pro lugar nenhum, pra que fazer isso? Eles querem vir aqui pra quê?
| 
| — Pelo que eu entendi vai melhorar pra chegar em algum estádio, acho, começou a ter uns shows por lá e o pessoal não conseguia chegar.
| 
| — Tem certos espaços que certos tipos não têm que frequentar mesmo, isso é a natureza agindo. Qualquer um que olhar direito consegue ver que a gente é de espécies diferentes, porra! Aparecemos eu e você nesse estádio, nesse show que essa gente quer ir, vamo ver se não fica todo mundo comentando.
| 
| — É, mas hoje em dia essa gentinha tá em todo lugar. Perdemos. Não tem o que fazer e isso já faz muito tempo. Parece que agora eles tão nessa de dar direito das pessoas ocuparem todos os espaços. Melhorar o acesso público.
| 
| — Melhorar pra quem? Você quer dizer que termina essa obra barulhenta e fica ainda mais fácil dessa gente vir pra cá? Eu não sei o que é pior, a dor de cabeça da obra ou um certo tipo frequentando aqui. Eu me mudei pra cá justamente pra não conviver com isso. Ainda mais que com isso daí, não dá pra ter nenhum diálogo, eles parecem não ter nem capacidade pra entender o que a gente diz.
| 
| — Esse seu papo de ódio é foda também. A gente fica odiando eles e eles a gente.
| 
| — Como é que é? A gente odeia eles? Eu nunca fiz nada pra esses filhos da puta! Agora aparece lá na casa de um desgraçado desse pra ver o que te acontece. APARECE! QUERO VER!
| 
| — Realmente não dá.
| 
| — É nóis contra eles porra!
| 
| — Mas vamo fazer o que? Isso daí é que nem praga, quando vem é pra ficar mesmo. Daqui a pouco ainda vão se multiplicar.
| 
| — Á lá, ó. Olha o que eu tô te falando. Vagabundo comendo sem educação nenhuma e deixando tudo cair no chão. MAS CHEGA EU PERTO PRA FALAR ALGUMA COISA PRA VER SE A CHINELA NÃO VAI CANTAR.
| 
| — Para com isso, pô, arrumar confusão à toa.
| 
| — À toa? Esse pessoal sujo começa a frequentar nossa área do nada e é a gente que tá errado depois? Como que isso é justo?
| 
| — Tá bom. Vem um pessoal mais limitado, menos desenvolvido intelectualmente pra cá fazer bagunça. Mas acho que a gente tem que aprender a conviver, dar o exemplo. Não dá pra exigir que eles aprendam do nada também.
| 
| — Conviver é o caralho! Eu tô falando com o pessoal, a gente vai dar um jeito de fazer com que esse povinho não chegue mais pra cá, eles vão voltar pra onde vieram.
| 
| — A é? E vão fazer como?

<p style="text-align:center">
**TSSSSSSSSSSSSSSSSSS**
</p>

| 
| — OLHA LÁ! OLHA O QUE EU FALEI! LÊ ALI Ó: DEDETIZAÇÃO. É nóis contra eles, eu avisei. Filho da puta com máscara de gás e os caralho.
| 
| — FUDEU! Eles obrigam a gente a fazer colônia cada vez mais longe, e mesmo assim gostam de vir matando todo mundo; sempre que conseguem matam. É spray, veneno, sapato, qualquer coisa.
| 
| —De todos os predadores que a gente tem que se preocupar nessa vida, a desgraça do ser humano é de longe o pior. Eu rezo pra cair uma bomba, queria ver esse tipo de ser subdesenvolvido sobreviver. A gente? Ia estar de boa, vivendo nossa vida igual agora. Ser humano de longe é a pior praga que já se espalhou pela Terra.


