---
title: "o poema"
author: 
  - name: Rafael Bonavina
---

| queria escrever um poema
| que matasse essa ânsia
| poema que explicasse 
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iminente colapso
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;as crises nas palmas das mãos
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;as próximas guerras (e as distantes)
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a compreensível revolta da massa
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a televisão com suas risadas gravadas
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o cheiro estranho na varanda
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;o motor da geladeira
|     tudo&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;eu
| 
| poema que oferecesse a mão
| e por que não o braço todo de uma vez?
| Poema que não fosse mais um papel na gaveta
|			                (palavras na nuvem?)
| poema que me explicasse por completo
| e eu já não precisasse dizer mais nada
| viveria em silêncio contemplativo
| em paz comigo e com o mundo
|     
|         mas não há estética
|         nem leitor que aguente
|         um poema desses
|
| além do mais, se perguntam
| está tudo bem?
| digo logo 
|         "tudo"
| que significa 
|         nada 
| então pra que esse tal poema que explica tudo?
|     pra quê?	se o silêncio é maior que o grito
|     pra quê?	se a sombra é mais clara que a luz
|     pra quê?	e a explicação só confunde
|     pra quê, 	afinal? 
|         pra quê?
| 
| se sempre falta dizer algo
| se o sono nunca vem
| e o poema tampouco.

<a href="https://instagram.com/oblomovsessive"><i class="bi bi-instagram"></i></a>
