---
title: "O QUE TE REVOLTA?"
author: 
  - name: Gabriella Menezes
---

| descaso
| enganação
| mentira 
| 
| o que nos revolta?
| o que me revolta?
| lutar contra o mundo e perder.
| 
| Me revolto contra a instituição que me impede de seguir minha vocação e minhas vontades, pela burocracia inútil que 
| serve de obstáculos nesta corrida, impostos por pessoas que nunca precisaram atravessar a pista, pois o pódio já lhes 
| pertencia.
| 
| Me volto contra mim, pois a consciência da escolha infeliz me pega de assalto e me faz questionar se o que deveria mesmo 
| me impulsionar na vida são os sonhos.
| 
| Podemos nós, mortais, termos escolha?
| o ardil do livre arbítrio me devora os pensamentos.
| 
| O que me move?
| angústia insone 
| o que me move são as batidas dos instrumentos na noite alinhados ao meu coração
| o que me move são os gritos da multidão
| as luzes vermelhas ameaçando as correntes e barricadas 
| o que me revolta é o que tenta me impedir de mover
| 
| o que te revolta?
| 
| me revoltam as cadeiras duras,
| as salas apertadas,
| as portas fechadas,
| as disciplinas trancadas,
| 
| o que te revolta?
| 
| me revolta o rosto cansado do espelho futuro
| os prédios espelhados inatingíveis
| as reuniões que decidem o quanto vale a minha vida
| Qual será o orçamento do dia?
| 
| e você,
| o que te revolta?

<a href="https://instagram.com/gab.ismenezes"><i class="bi bi-instagram"></i></a>
