---
title: "coluna Túnel do Tempo"
author: 
  - name: Gabriel Carra e Bruna Silva
---

**Gabriel Carra**

*''O que pode a literatura? Ou dois vinténs para a papisa Joana''*

Na juventude conheci uma palavra fascinante: "papisa". Jean de Mailly, primeiro a mencioná-la, escreve *"papissa, quia femina erat"*[^1]. Tantas palavras de que a língua parece carecer (é o sentimento do tradutor), e temos "papisa", cujo único referente, Joana, é imaginário. Por quais caminhos tal lexema pôde existir? Não parece plausível que compartilhe do mesmo processo que nos deu "unicórnio", pois primeiro esta surgiu para designar algo do mundo. Só posteriormente, por uma cadeia de transmissões ruidosas, é que chegamos ao complexo imaginário ilustrado que conhecemos. Antes, os unicórnios eram simplesmente rinocerontes.

[^1]: \"Papisa, pois era mulher\". Para a história e a tradução dos documentos de Jean de Mailly e outros que mencionam a figura, recomendo o artigo de Dominique Vieira Coelho dos Santos e Camila Wackerhage, \"PETRE, PATER PATRUM, PAPISSE PRODITUM PARTUM\" (2013).

Alguns afirmam que a história de Papisa Joana foi inventada para desmoralizar a Igreja Católica. A hipótese é plausível, mas para nossa discussão não basta. Fofoqueiros e caluniadores do mundo nunca precisaram ser Joyces ou Rosas para aumentar um ponto. Bastaria a de Mailly ter escrito *"papa femina erat"*. Mas ele realizou um gesto que podemos considerar, sem prejuízos, literário: com "papisa", codificou uma fantasia coletiva sem precedentes com a realidade percebida. Em termos conotativos, ela associa poder e mulheres e sugere-nos pensar a partir de uma estrutura "e se...": como seria nosso mundo acaso mulheres e homens compartilhassem estruturas de poder há mais de um milênio? Em termos denotativos, a palavra cria uma possibilidade de realidade ainda não explorada, e perguntamos *por que não podem haver papisas*?

Um tal signo, só posso o considerar como um gesto puramente literário, uma vez que causa curto-circuito na função referencial da linguagem. Como é típico acontecer nesses casos -- quando não se pode definir a linguagem como mera comunicação ou designação --, palavras como "papisa" e discursos como o literário impelem à pergunta: o que podem essas linguagens? Em outras palavras, o que pode a literatura?

Proponho, então, aos amigos e colaboradores da revista (se a equipe editorial gentilmente composse uma edição assim tanto melhor) um exercício de exame de consciência: o de tentar responder à pergunta acima num curto espaço. Um parágrafo, dois talvez. Como se sabe, a generalização é uma atividade pouco demandada a nós ao longo do bacharelado. Não é difícil de imaginar também que tal número da revista não será nem o mais brilhante e nem o mais instigante ao leitor. Um texto de nossos mestres, de Perrone-Moisés ou Candido, valeria muito mais a ele; e seríamos nós, aliás, os primeiros a sentir o ridículo de tal empreitada e a ter vontade de abandoná-la.

A aventura não é inútil, no entanto. Individualmente, o que se nos oferece é a oportunidade futura de relermos o que corajosamente publicamos -- é preciso ter coragem para expor convicções íntimas e calar a tréplica, deixar ao outro o direito da palavra final --, e de refletirmos como de cá chegamos ao que seremos lá. Coletivamente (é a dimensão que me interessa), realizamos um ato de gentileza para a geração futura: entregamos a ela um instantâneo de nossa compreensão sobre a literatura. Um exame de consciência no pleno sentido do termo, portanto.

De minha parte, faço minha contribuição: a literatura pode espanar a indiferença. Ideia que me contenta, uma vez que tem a humildade de permanecer no trabalho do significante, e assim preservar diferenças: o que "indiferença" significa para você? As ênfases variam: para uns, será a indiferença à política, às questões urgentes para nossa sociedade; para outros, será indiferença à moral, aos modos com que levamos a vida, automatizados por uma sociedade de consumo; para alguns será a indiferença à sensibilidade, àquilo tudo que perdemos quando evanesce a capacidade de ser sensível às experiências; para outros, ainda, será a indiferença da linguagem cotidiana, da estereotipia, que homogeniza os modos de vida. Todas essas possibilidades, ao meu ver, são complementares e não excludentes, e atraem uma definição positiva: a literatura pode produzir diferenças.

**Bruna Silva**

Nosso colega Gabriel, em *"O que pode a literatura? Ou dois vinténs para a papisa Joana"*, soltou o verbo na investigação das funções individuais, sociais e práticas da Literatura, e nos convidou a fazer o mesmo:

O que pode, afinal, a Literatura?

Antônio Cândido, patrono do nosso curso, acredita que a Literatura desempenha um papel fundamental ao espelhar a sociedade, possibilitando a compreensão e a crítica das condições sociais. Além disso, ele argumenta que a Literatura tem a capacidade de explorar tanto experiências universais quanto particularidades culturais, abordando temas fundamentais como amor, morte, identidade e justiça, ao mesmo tempo em que reflete as características específicas de uma sociedade ou grupo cultural.

Partindo de um conjunto bordado por estudos críticos, vivências genuínas do criar artístico, experiências empíricas que a leitura oferece e pelo ambiente -- inspirador -- em que o poder de se expressar é elevado à potência de luta, resistência e grito, essa Literatura, para nós, esculpe caminhos e lapida sentimentos. É o ato de tomar posse da linguagem que nos é oferecida e ir além... Romper estruturas porque essas não mais conseguem expressar a grandiosa complexidade de ser. Mergulhar em si mesmo e oferecer voz ao que fica intrincado. Ou não; emprestar do vasto universo linguístico a forma, modificando seu conteúdo e, assim, obrigando-o a ser o que precisamos que seja.

Impor-se à sua maneira e entender que nossos discursos são próprios de nossas vivências e devem dialogar com o que toca nosso ímpeto de movimento.\
Desobrigar e obrigar, pois ela nos demanda movimentação -- cortante como Machado, intimamente instigante como Clarice, preciso como Guimarães, determinada como Conceição Evaristo...

É a disposição de abraçar o revolto, não importa de onde ele venha ou o que ele exija. É um esforço conjunto para traçar o caminho que escapa das curvas normativas ou conceituais, pois a Literatura é, em si, a busca pela essência humana e sua expressão mais autêntica. Em última análise, é um compromisso profundo consigo mesmo, com a arte e com a capacidade da linguagem de capturar a vastidão da experiência humana.
