---
title: A biblioteca
author:
- name: Dereck Alexandre Ferreira Dourado
categories:
- CONTO

---

O fim da tarde chegou, e a chuva caía lá fora.

Os olhos dela corriam pelas longas prateleiras repletas de livros. Não entendia como alguém poderia ler tantos. Os livros tinham sido herdados de sua mãe, leitora voraz e arquiteta, que morrera havia alguns dias.

As prateleiras eram nichos quadrados de tamanhos variados, e não tinham mais espaço para qualquer coisa além dos livros. Quantas histórias não havia ali, entre aquelas páginas empoeiradas? Quantas aventuras com monstros, criaturas e seres mitológicos? Livros técnicos, com rabiscos e notas? Romances antigos, sombras de vidas nunca vividas? Quantos daqueles livros tinham as anotações de sua mãe? Talvez todos. Ela adorava fazer pequenas marcações a lápis enquanto lia, dobrar as orelhas das páginas, tocar e sentir os livros, como se eles fossem pessoas.

Levantou-se e pegou um livro ao acaso, tirando-o da prateleira e abrindo-o na
primeira página. Havia um arabesco desenhado na folha, a lápis. Percebeu que ele parecia ser um embrião do arabesco que circundava o rodateto em gesso da biblioteca. Impressionou-se ao perceber que nunca soubera que sua mãe o havia desenhado. Tinha muitas perguntas que gostaria de fazer a ela, mas não poderia mais, pelo menos diretamente.

Pousou o livro sobre a mesa, e foi à cozinha, preparar um bancha, como tinha visto a mãe fazer tantas vezes. Trazendo consigo a pequena bandeja, sentou-se na cadeira de salgueiro projetada pela mãe, e se aconchegou, apanhando o livro. 

Queria estar novamente com ela, e agora estava.

<a href="https://instagram.com/dereckalexandre"><i class="bi bi-instagram"></i></a>
