---
title: Cigarros
author:
- name: Sea Stars
categories:
- CONTO

---

**Eu fumava de três a cinco cigarros por dia.**

Tinha sempre uma maço junto de um isqueiro no bolso da jaqueta. Acendia um e tragava a minha única válvula de escape desse mundo imundo.

Você olhava com reprovação e tristeza para o cigarro aceso, e sempre dizia que eles acabariam me matando, enquanto andávamos uma ao lado da outra em direção aquela cafeteria retrô da esquina.

| -- Isso ainda vai te matar. - dizia fazendo uma careta pelo cheiro ruim.
| 
| -- Eu sei. - respondia rindo amarga, dando mais um trago.
| 
| -- Sabendo que pode morrer, por que ainda fuma? - perguntava andando ao meu lado e próxima à mim. Dividindo contra a sua vontade da tóxica fumaça comigo.
| 
| -- É a única coisa boa nessa merda de mundo.- cuspia e recebia um olhar chateado.
| 
| -- Me preocupo com você, então tente dar uma diminuída, pelo menos.- pedia dando um sorriso de canto.

Eu sempre adorei ouvir você dizer isso. E ainda que não soubesse porquê, sempre fazia uma nota mental para deixar de fumar. Na época, fingia não saber porque me importava. Mas no fundo, talvez eu soubesse que gostava de você. 

E eu deixei de fumar… por um tempo.

Certo dia, realmente parei, surpreendentemente não tive recaídas e estava conseguindo lidar bem com o meu "vício". Uma semana depois, enquanto caminhávamos lado a lado pelo mesmo trajeto de sempre em direção à cafeteria, você me perguntou se eu tinha parado de fumar.

| -- Sim.- respondi olhando e sorrindo para você.

Com as bochechas assumindo um tom rubro, me disse que eu ficava linda com meu jeito despojado, tragando o cigarro entre os dedos.

Meu sorriso aumentou.
No dia seguinte, passei a carregar um único cigarro junto comigo, dentro do bolso onde sempre deixei os maços que comprava. Carregava-o comigo todos os dias, com a justificativa de que eu poderia voltar a fumar. Porém nunca tive a vontade de acendê-lo… por um tempo.

De certo modo, sempre soube que era para me lembrar de você. E eles ainda lembram.

A partir dali, tudo sobre você passou a significar o mundo para mim. Você me dava uma sensação melhor que a nicotina. E aos poucos, percebi que estava apaixonando-me perdidamente por você.

E inexplicavelmente, eventualmente descobri que você também dizia estar apaixonando-se por mim.

Começamos um relacionamento, às escondidas, seu pai não podia saber. Entretanto, nem por isso o relacionamento foi ruim.

Conforme o tempo transcorria, eu me vi entregando-me cada vez mais e mais para você. Me entregava como nunca me entreguei à outro alguém… e jamais me entregarei.

Em algum momento, percebi estar amando você.

Você também disse que me amava.

Apesar das brigas de certa forma constantes, e do sigilo, conseguimos completar três anos de namoro. Foram os anos mais felizes de toda a minha vida, com certeza.

Decidimos tocar a vida juntas e assumir o nosso relacionamento, não importando o que acontecesse.

Era o nosso aniversário de namoro e tínhamos combinado de nos encontrar no mesmo lugar de sempre. O dia era nublado, frio e entristecido. Mas, quando tratava-se de você, tudo parecia ensolarado, quente e feliz. Caminhava em direção à cafeteria, que de tanto irmos lá, a tornamos "nossa". Sorri ao tocar o pequeno cilindro de papel em meu bolso.

Encontrei-a sentada em "nossa" mesa, que ficava no canto do lugar, próximo a grande vidraça que dava uma visão privilegiada do lado de fora. Você parecia infeliz, muito infeliz.

Meu sorriso diminuiu e o coração falhou uma batida e me sentei a sua frente.

| -- O que houve?- perguntei tocando sua mão sobre a mesa.

O dia nublado agora me afetava. E um pressentimento ruim decaiu sobre mim.

| -- Não podemos mais ficar juntas.- disparou puxando sua mão da minha e rapidamente saindo. Não me dando a chance de perguntar o por que, muito menos de dizer que te amava. Talvez, eu pudesse ter feito alguma coisa.

Tudo pareceu destroçar-se, incluindo meu coração, que aparentemente morreu no peito.

A vontade de chorar fez-se presente, porém não derramei nenhuma lágrima sequer. Quase como se eu soubesse que isto iria acontecer.

Saí da cafeteria, completamente devastada e procurei pelo único cigarro em meu bolso. O primeiro que acenderia em quase quatro anos. Caminhei até uma loja de conveniência, enquanto lentamente tragava a morte contida no cigarro. Comprei um maço de Malboro, a caixa vermelha. De algum modo, eram os seus favoritos.

Naquele dia, voltei a fumar.

Alguns anos passaram-se e você estava casada com um homem socialmente "perfeito", esperando o complemento para uma família socialmente "perfeita". Você parece feliz.

Sorrio amarga toda vez que recebo notícias suas.

**Eu fumo de sete à dez cigarros por dia.**

**Às vezes, um maço.**

Fumo cada um deles para conseguir ouvir e sentir, em algum lugar distante em minha conturbada mente, você me dizendo que eles me matarão.

Sorrio melancólica, como sempre fiz. Enquanto trago uma morte lenta e tenho a débil impressão de observar a fumaça materializar seus sorrisos, olhares e qualquer outra coisa que represente você, aqui. Comigo.

Não serão todos estes cigarros que trago que me matarão. A culpada foi e sempre será você.

Você me matou no dia em que foi embora. Me matou da pior forma que alguém pode ser morto.

Você me matou por dentro, ao me deixar viciada e dependente de você. Quando me abandonou, deixando um coração partido junto de várias cinzas de cigarros para trás.

A ausência, (me) mata.

Os cigarros, não.

