---
title: Como vai você?
author: 
  - name: Sara Bastos
---

| Olá, como vai você?
| Tenho me perguntado sobre o seu desfecho.
| Nos últimos dias você tem me perseguido por todos os lados, 
| E mesmo evitando, te encontro
| Te encontro em todos os cantos que frequentávamos 
| Em nossos lugares preferidos e em dias nublados
| Te vejo no final de tarde quando o dia anuncia seu abandono
| No gosto do álcool e quando Equalizo nossa rádio 
| Eu te percebo no começo de agosto e no cheiro do inverno
| Naquela mesa que hoje se encontra vazia
| E em todos os lugares que você ocuparia
| Mas, te recupero em todas as suas coisas favoritas 
| 
| De fato, você tem que estado por todos os lados
| Eu te acho e não te sinto 
| Você está aqui e ali
| E ao mesmo tempo em lugar nenhum
| Está nesta fotografia que ficou
| E nos momentos que nunca voltarão
| 
| Embora eu tenha procurado maneiras para te eternizar 
| Também quero te deixar ir
| Mas quando eu vejo o tempo correr sem olhar para trás
| Sinto que essa busca é ordinária 
| Pois, eu vejo os botões florescendo, os dias nascendo e pessoas sorrindo
| Como se tudo fosse tão banal
| Como se tivéssemos caído no esquecimento eterno
| 
| Sua ausência no presente e sua presença no passado 
| Estão refletidos em todos os meus passos, hoje solitários
| Eles trazem à tona você e a nossa lembrança
| O futuro que me convidou, não é capaz de te chamar
| Apesar disso, ainda desejo saber como você estaria
| Escrevo porque há muitas perguntas que não querem calar
| E minhas cartas já não conseguem te alcançar
| Porém, espero em profundo desconsolo que esteja bem 
| Onde quer que esteja
| Esteja finalmente bem
| 
| Em memória de Murilo Werneck.

<a href="https://instagram.com/s.artxx"><i class="bi bi-instagram"></i></a>
