---
title: Conselho de vó
author:
- name: Bruna Vitoria Raimunda Pinheiro
categories:
- POEMA

---

| Tá doendo demais e o jeito que eu encontro de botar pra fora é esse
| Chorando minhas palavras 
| Cantando meus medos 
| Sambando sem jeito na cara da minha dor
| Precisando gritar sobre tudo que não entendo 
| Que não vou entender 
| Gritar a aflição da ignorância 
| Saudade da antiga ignorância 
| Acho que naquele época eu era mais calma
| Credo, tô saudosista.
| 
| Quero viver meu agora respirando devagar 
| O capitalismo tem roubado meu tempo e me deixado opaca;
| Tô mais opaca que pele de blogueira com maquiagem mate
| 
| Todo dia eu me olho no espelho e tento me dar brilho de novo
| Mesmo que seja com lágrimas nos olhos 
| Quero sentir mesmo que seja dor 
| Não me importo de ser transpassada por ela 
| Pq já sei que vai ser passado quando eu notar que a dor passou 
| Coloco minhas dores num saquinho e às carrego
| Tenho carregado num saquinho pq dentro de mim tá meio difícil 
| Quero analisar elas fora do meu peito pra ver se encontro razão 
| Nossa...
| A razão...
| Ao tirar essas dores do peito, vejo os buraquinhos 
| Abraço esse vazio e agradeço 
| Melhor vazia do que afogada no meu próprio sangue 
| Antes vazia por hora 
| Do que morta.
| 
| Me reconstruo a partir do conselho da minha avó 
| "Fia, na vida a gente tem dois sacos, um sem fundo e um com fundo, no com fundo você | coloca as coisas boas e no sem fundo o que não presta"
| Aquela velhinha acelera meu peito e mostra o quanto recomeçar
| Tem começar no meio 
| Recolho aqui, os cacos da minha pele, do meu coração, dos meus olhos e ossos
| Construo de novo um novo eu
| Me faço de arte chinesa que cola os trem com liga de ouro 
| Me faço de novo 
| Na minha eterna dança de subir e descer

<a href="https://instagram.com/bru_vit"><i class="bi bi-instagram"></i></a>
