---
title: do que antes era algo belo
author:
- name: Verônica Olmos
categories:
- LÍRICO

---

quando se é jovem e não se sabe de nada há tempo de sobra para aprender a amar. com você aprendi a amar e amar as pequenas coisas da vida. quando éramos jovens e não tínhamos ninguém além de nós mesmos a vida nos aproximou e esse foi o início de tudo.

não sei se você se lembra. o tempo todo sempre juntos, colados em nosso abraço, sorrisos alegres e risadas de felicidade. longas conversas sobre tudo e nada ao mesmo tempo, mesmo as nossas piores brigas eram rapidamente reconciliadas, e eu ainda lembro de cada conselho dado e os guardo como tesouro. 

éramos jovens e inseparáveis, mas algo mudou. a mesma vida que cruzou nossos caminhos separou-os novamente, hoje não somos mais os mesmos. "feliz aniversário!" respondidos três meses depois, antigas amizades já não têm mais espaço na sua vida, você foi embora e não consegui me despedir a tempo.

do que antes era algo belo hoje resta apenas um coração partido.

