---
title: Ângulo
author:
- name: Tereza Lacerda
categories:
- DIARIO

---

## sábado, 11 de dezembro de 2022

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/6aEQ365jPX55xfpA8OFfki?utm_source=generator&theme=0" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

Ontem eu fui no show do Grilo no Cine Joia, e por mais que eu já esteja acostumada a ir em shows, esse em particular foi bem especial. Vou tentar deixar registrado com detalhes como foi essa noite do começo ao fim.

Umas 8 da noite a minha amiga me deu uma carona até a estação Japão -
Liberdade, que fica muito próxima ao Cine Joia. Então eu fui andando até lá, e ah! Caminhar pelas ruas da cidade em noites de verão me deixa muito feliz, já fiquei um tanto
animada!

Chegando lá na frente, encontrei meus amigos e entramos na fila. Acho engraçado
que os seguranças desconfiam de mim em todo rolê porque acham que eu sou menor de idade (eu não sou).

Enfim, entramos na casa de show, e logo de início já me distraí com as paredes de lá, elas tem uns fios de led que ficam mudando de cor (eu adoro luzinhas). A música que estava tocando era muito boa também, bem parecida com as playlists que ouço no dia-a-dia (modéstia a parte). Parece bobo, mas gosto muito dessa sensação de pertencimento, porque é muito raro ver bandas/artistas brasileiros não tão mainstream tocando em rolês, então isso me deixa muito feliz.

Depois de algum tempo, a banda entrou no palco, e então, várias artes com a
estética do último álbum (e único) do Grilo começaram a ser projetadas nas paredes. Os integrantes estavam usando figurinos coloridos com a paleta de cores do álbum também. Eu gosto muito quando isso acontece em shows, porque acaba trazendo muitas memórias das minhas experiências pessoais com o álbum, e esse álbum em específico me marcou muito. Ele foi lançado durante a pandemia, e me acompanhou por todo esse tempo, tanto com reflexões pandêmicas individuais, quanto histórias com os meus amigos também (costumávamos ouvir muito as músicas em chamadas no Discord).

Em diversos momentos do show, a banda fez mashups com bandas e artistas como Pink Floyd, Nirvana, Caetano Veloso, etc. Isso acabou deixando bem evidente que esses artistas serviram de referência para as canções do álbum, e ao mesmo tempo trazendo uma sensação meio nostálgica, sei lá, gostei muito. Isso é uma das coisas que tornam a experiência do show muito única, adoro isso! Outra coisa que gosto muito é que o Grilo tem uma gama muito grande de gêneros musicais nesse álbum, e no show isso fica ainda mais evidente: eles trocam os gêneros das músicas, misturam tudo! Acho isso tudo muito
brasileiro, eu amo!

Em algum momento do show, a banda Aquino e a Orquestra Invisível entrou no palco pra fazer uma participação, e sério, que energia e presença de palco maravilhosas, sério, sério! Conheci a banda no mês passado em um show da Flerte Flamingo, e foi amor à primeira vista, eles arrasam muito mesmo! Não sei nem descrever a felicidade e energia que fiquei naquele momento!

A última coisa que queria deixar registrado aqui, é que em algum momento do show, no meio da música “Onde Flor”, o vocalista pediu pra galera de plateia abrir um espaço e entrou simplesmente UMA BATERIA DE ESCOLA DE SAMBA! Sério, sem condições, isso me deixou maluca! Eles fizeram a percussão da música (que ficou incrivelmente boa) e saíram. Muito bom.
Pra finalizar, queria dizer que a música me faz sentir muito viva, e é muito bom estar em ambientes que tornem essa experiência além de um simples som no fone de ouvido. Cantar, pular, dançar, improvisar, dividir isso tudo com outras pessoas... Deixa meu coração muito quentinho!

<a href="https://instagram.com/_cherry.py "><i class="bi bi-instagram"></i></a>

