---
title: "Lilás"
author: 
  - name: Nabê
---

Assim como o cafuné, a saudade só existe no português. Não sei se é fato, mas li um dia. "O amargor na lembrança doce". Como é manipuladora a saudade!

Desperta da maior simplicidade: um cobertor cheirando a amaciante ou fios de cabelo azul. Nasce até no cabide que sobra dentro do armário, que residia aquela calça que tanto gostava, mas que não lhe servia mais.

Eu queria que a saudade (assim como a calça) não coubesse mais em mim. Ficasse tempo demais na secadora e encolhesse até poder caber apenas em meu bolso. Mas como ela é grande, gigantesca! Forma uma onda na nossa boca: Saauuudade. E há algo nesse mundo mais avassalador que um tsunami?

Saudade: tão romântica e tão triste. Caricatura do melodrama. Quero abraçar mas não posso. Quero sentir mas não posso. Quero tudinho e não posso nadinha. Como é cruel a saudade!

| Saudade, saudade, saudade.
| Sau-da-de.
Digo como manifestação, pois não quero que ela vá embora também. Afinal, onde já se viu, sentir saudade da saudade…

<a href="https://instagram.com/nanabrmb"><i class="bi bi-instagram"></i></a>