---
title: reconhecença
author:
- name: Letícia Montes
categories:
- POEMA

---

| todas essas histórias — 
| eu sempre sentirei falta delas.
| 
| eu sei que elas sobreviverão 
| às tempestades mais severas 
| e às chamas mais altas 
| e ficarão dentro do meu coração 
| até meu último suspiro
| 
| mas eu sempre sentirei falta delas.
| 
| sentirei falta do toque suave 
| das palavras contra a minha garganta
| da lágrima contida e da sensação de ter milhares de mundos dentro de mim
| 
| eu sei que esses mundos crescerão 
| e crescerão e continuarão crescendo 
| até que esse universo se finde
| e então as palavras flutuarão 
| num vácuo quase eterno 
| até encontrarem outra fonte
| e elas estarão livres
| 
| mas eu sempre sentirei falta delas.
| 
| eu imagino que me tornarei 
| uma partícula muito pequena 
| e um pouco brilhante
| e que haverá algum outro 
| choque colossal de átomos 
| que fará existir um outro universo 
| para comportar minhas memórias flutuantes
| 
| e que eu renascerei como uma estrela
| ou como uma nuvem
| ou como um pássaro
| ou como um outro alguém desavisado
| 
| e que haverá um pouco de poeira de mim 
| em cada canto desse novo universo 
| para que eu
| ao atravessar avenidas
| sentir a chuva contra a pele 
| ou nadar no mar
| consiga me deleitar 
| com todas as maravilhas 
| que um dia aconteceram e que
| por reconhecença
| ainda me causarão arrepios
| 
| quem sabe os meus universos 
| estejam se multiplicando em palavras 
| e em histórias 
| e em saudades —
| 
| eu espero que sim. 

<a href="https://instagram.com/lelesphotoalbum"><i class="bi bi-instagram"></i></a>
