---
title: Um dia
author:
- name: Rayssa Santos Moreira
categories:
- CONTO

---

Qualquer dia eu vou lembrar de ti como um ardor na minha pele queimada pelo fogo. Vou olhar para trás e te ver perdido nos teus rumos que, em algum momento, se perderam de você. Em dias quaisquer, eu vou fechar os olhos e recordar cada sorriso que demos às escuras no quarto. À escura vida que nos encheu de esperança. Num dia comum, como hoje, eu vou sentir sua pele tocar a minha e me alegrar com a sua presença. 

Num certo tempo — por vezes errado —, eu vou me aproximar da nossa história e permitir que o meu coração se aqueça das lembranças que restaram. Mas sem deixar que ele se esfrie com a recordação de sua dolorosa partida. Vou me recordar do tempo em que eu era sua, e que, sem muito esforço, eu me debruçava sobre você para dizer o quanto eu te amava. O quanto te amei. 

Por alguns momentos, vou implorar o teu ficar sem te deixar partir. Vou rever seus conceitos e reviver velhos hábitos. Vou rir de prazer que a dor do gozo me causou e, sem medida, irei transbordar em você. Em algum dia - desses ou daqueles - sem reservar-me, vou berrar o teu nome e expor a dor da sua ausência. Mas sem perder a pose. O sorriso. E o medo. Eu vou tirar a tua alma de mim que, como tatuagem, ficou no meu corpo por uma vida. Ou talvez duas.

Em um dia simples, eu vou olhar tua boca, sorrir com os olhos e ouvir teus suspiros. Sempre conspirando a nosso favor. Vou te dizer que a sua presença faz falta e que dispenso tua ausência como qualquer alimento indigesto. Tão indigesto quanto as palavras que não saíram dos meus lábios ao dizer o teu nome.

Eu vou chorar. Implorar. E talvez te pedir. Fique mais. Um pouco. Uma vez. Fique? Não me parta de novo com a sua partida. Não me faça querer voltar no tempo e viver tudo de outro jeito. Sem o teu jeito. Porque estou te querendo novamente. E quantas vezes precisar. Quero estar perto, sem ter a distância dos nossos lábios. Dos nossos olhos. De nossas almas. 

Em dias normais, eu vou correr para você e te abraçar contra o vento. Contra o tempo. Contra o peito. Vou sentir teu coração pulsar junto ao meu. Eu vou viver. Eu vou.

Um dia, eu vou me apaixonar, e vou deixar me levarem de ti. Um dia desses. Qualquer um. Eu vou pensar em você com dois sorrisos: um na boca, outro no peito, e vou me lembrar do seu quase-beijo-doce que eu receberia, não fosse o teu não-querer. Prometo que te olharei com os mesmos olhos e te sentirei com o mesmo desejo. Não vou te matar em mim, eu juro! Se não posso viver pra você, tudo bem, eu aceito. Como sempre fiz. O que não dá mesmo é eu morrer para mim. 

Só preciso pensar em nós como um caso de um quase acaso, que aconteceria, não fosse o teu descaso despido de coragem. 

Dia desses, eu vou te esquecer. Mas não hoje.
