---
title: 'Exame da CNH'
author: 
  - name: "Gê"
---

Nove! Nunca esquecerei esse número, pois foi a minha nota na avaliação prática de condução veicular, ainda que meu desempenho tenha sido reprovável por vezes o suficiente para nunca dirigir na vida. Acontece que sou ansioso quando o assunto é avaliação. O instrutor foi bastante empático, sendo ele mesmo uma pessoa do meu calibre.

Ele começou a contar a história da vida dele e de como tirou o certificado que permitia a condução de veículos, uma vez que me viu nervoso a ponto de quase ter virado o carro na primeira curva, atropelado um cachorro e a moça que o levava para passear e ter quase batido no poste três vezes seguidas. A história da vida dele foi mudando de uma forma bem estranha. Não sei em que ponto a conversa mudou de “como eu tirei minha CNH” para “Quando eu era matador de aluguel”. Sempre me disseram que eu era uma pessoa que inspirava outras a se abrirem, mas isso foi demais. Naquele dia ouvi o relato de nove de seus “trabalhos”.

Tiveram dois políticos desconhecidos, três maridos infiéis, uma cantora famosa, um policial fardado, um jogador de futebol do Atlético do Mangabeira FC, mas o que mais me chamou atenção foi o de um padre. Nesse ponto, a gente já estava numa padaria comendo coxinha, uma vez que eu era o último a ser avaliado e ele não pareceu se importar muito com o tempo. 

A morte do padre tinha sido contratada por uma mãe que teve o filho abusado múltiplas vezes pelo referido secular durante aulas de violão. O contrato, a princípio, tinha sido de uma morte vexatória, com destruição da imagem, “morto pela própria perversão”, foi o que ele disse com um sorrisinho satisfeito, mas que tentava se esconder na imparcialidade do serviço. Porém, no decorrer do prazo programado, a morte foi mudando de forma, vindo a não ter mais forma nem mesmo de morte, acho eu que pela moralidade cristã da família e o medo de ir ao inferno tomar um chazinho com o capeta.

Mas o meu amigo ex-assassino estava imerso na vontade de fazer acontecer. Sendo ele pai, não soava certo que aquele indivíduo andasse livremente e quis resolver o problema do jeito que sabia. Organizou os itens: um cinto, vídeos pornográficos com os atos mais abaladores de prestígio de tal figura e sedativos que permitissem que o corpo inoculado reagisse a estímulos, ainda que sem controle próprio sobre eles. Foi à casa do alvo, lugar onde ocorriam também as aulas, carregando a mala com os itens. Avaliou se tinha câmeras, se a casa tinha ou não alarme, número de portas, tipos de fechadura, janelas e cortinas, mas o que o inquietou foi a ausência do padre na residência, embora tudo levasse a crer que ele estava lá. Se aproximou da janela do quarto, olhou por uma brecha entre as cortinas e viu que não estava sozinho, estava acompanhado de um garotinho. Não quis contar o que viu, mas a sua expressão não dizia nada além de puro nojo. Ele disse que estava prestes a intervir, quando viu o padre agonizando, sem ar, e o menino, de uns nove anos, se levantar triunfante enquanto via a vida se esvair daquele podre. 

Eu sabia dessa história, pois eu estava nela. Eu era a criança que matou meu abusador e ele sabia disso. Ele sabia de toda a repressão que passei, da polícia pressionando minha família porque o padre era a escolha para as missas feitas no departamento, da escola se negando a me aceitar porque recebia o então morto para falar de caridade, até o único hospital da cidade negava atendimento pois era da igreja, forçando a gente a se mudar algumas muitas vezes até achar um lugar onde essa situação não pesasse tanto. Ele disse que me observou durante todo o meu período de formação e de minhas dificuldades, procurando uma maneira de ajudar sob forma de pagamento pelo serviço que ele iria fazer.

<!-- <a href="https://instagram.com/thewriterofthedayz"><i class="bi bi-instagram"></i></a> -->

