---
title: 'O pacto'
author: 
  - name: "Rafael Mendes de Barros"
---

| Não pensei em teu vão passado lá,
| pois também já não perguntaste o meu,
| fica da oferenda para Oxalá,
| qual se perdeu,
| 
| todo o meu desejo, do Amor a senda
| para qual tentamos recuperar
| prumo; aqui me fartam ao abrir a fenda,
| tal é o esperar,
| 
| deste coração tão meu quanto teu,
| moralismos inúteis de que não podemos 
| mais fugir, por ora, sem cair no breu
| que conhecemos 
| 
| como hipocrisia… Gira a Roda posta,
| Sorte, acaso, tudo vai com o Destino,
| tal Samsara vem perseguir-nos… Gosta
| mais do refino
| 
| deste mundo, a vida das almas, vai 
| e aprecia cá como tu podes, pois
| sabes que o todo daqui se esvai,
| homem que é e sois,
| 
| finda humanidade…nem deposita
| mais que o necessário para Arte, mas
| vá a labuta, a Fé ela vale, insista…
| Faz e refaz 
| 
| sem as ilusões: a Comédia, Dante,
| não o retirou desse exílio seu,
| nem o trouxe para Beatriz que infante
| lá padeceu…
| 
| Marx não viu sequer a Revolução,
| Nietzsche não colheu os tantos frutos
| destas glórias tuas… A transformação 
| sem os astutos
| 
| não ocorre, mas sem perder jamais 
| consciência ao Fado… Van Gogh de longe 
| fez-se conhecer como artistas tais,
| triste se esconde
| 
| seu final… E nós que fazer podemos
| mais se nem canção, a Vinícius, não 
| lhe salvou do ocaso seu? pois vivemos
| sempre na ação
| 
| pela aurora própria ainda que no todo
| tudo venha já nos faltar; se é o Karma,
| Pacto ou coisa além de outra vida, o lodo
| mesmo que se arma
| 
| para separar-nos, nem nada posso
| por interferir, só Deus é que muda
| fado vosso… Venho a rezar pai-nosso:
| — Vez nos acuda…

<a href="https://instagram.com/rafael.mendes_10"><i class="bi bi-instagram"></i></a>

