---
title: 'Cartas para Machado'
author: 
  - name: "Leandro Lear"
---

São Paulo, 30 de julho de 2024

Saudações , caro Machado

Pensaste que poderias descansar em paz, não é? Bem, tiraste o pobre Brás Cubas de seu túmulo para que ele fosse um dos maiores personagens da Literatura Brasileira, então nada mais justo que eu te incomodar um pouco.

És um grande gênio, e creio que ninguém logrou criar uma obra tão potente quanto a vossa. Há 14 anos me tornei um apreciador incondicional de teus escritos, ainda não tive o privilégio de ler tudo que escreveste, porém posso dizer que tudo que li me marcou profundamente, incluindo Helena. 

Me aventurei nas searas da escrita há pouco. A ideia de defunto-autor foi o que me moveu, mas apenas copiar-te não era meu ensejo. Daí veio uma ideia fixa do leitor-defunto. E nada mais justo que te tornares um deles. 

Foste um homem muito à frente de seu tempo, me sinto um homem deslocado do meu. Considero-me esperançoso, pois desejo de alguma forma escrever com a pena da galhofa, como fizeste. 

Perdoe-me pelo meu linguajar vulgar, esta nossa separação temporal de mais de meio século dificulta ligeiramente nossa comunicação.  Não tenho palavras para agradecer-te a imensa influência que tiveste em minha vida. Após entrar em contato com a sua obra, decidi estudar literatura na faculdade (sim, atualmente isto é uma profissão). Passei meus últimos anos tentando me aperfeiçoar como professor, e hoje vejo que posso ser um professor-escritor, ou quem sabe um escritor-professor.

Recentemente, arrisquei escrever alguns poemas. Automaticamente lembrei-me de ti. Será que devo insistir nisso ou dedicar-me exclusivamente à prosa?

Seu mais humilde criado,
Leandro Araujo

<a href="https://instagram.com/thewriterofthedayz"><i class="bi bi-instagram"></i></a>

