---
title: 'Copacabana'
author: 
  - name: "Otávio de Sousa"
---

Não dormi. Dessa vez não foi a ansiedade nem o excesso de pensamentos que às vezes me arrebatam para longe de Morfeu; dessa vez em especial minha insônia tem outra causa, tem nome, sobrenome, CPF e endereço. Saí cedo de casa e fui andar pelo calçadão, Copacabana está opaca apesar da bela manhã que faz, mas isso continua sendo culpa dela. A vitória do Flamengo que tinha me feito tão feliz até quarta perdeu um pouco da graça, isso também é culpa dela, as crianças riem e jogam bola na praia, os adultos tomam seu primeiro contato com a água salgada do dia e voltam revigorados, eu estou meio bêbado de sono, mas ainda lúcido demais para me entregar às divagações típicas dos insones, eu tinha um pensamento fixo quando fechava os olhos e sentia o vento, eu pensava nela de calcinha de manhã se arrumando para ir embora como se fosse a coisa mais normal do mundo, eu que assistia àquilo me sentia em estado de choque, pois tinha percebido que não era mais capaz de viver longe dela, então desde àquela quarta-feira de manhã a comida, as pessoas, as mulheres especificamente; por mais belas que eu consiga admitir que sejam, me parecem foscas, opacas perante àquela lembrança, aquele conceito de ser mulher que só ela tem. Piso na areia sem o chinelo, a areia brinca entre meus dedos e vai embora de volta ao seu status quo de areia de praia, ando por algum tempo, o vento salgado, o sol recém-nascido e rude me queima a pele sem nenhuma delicadeza, tudo está tão fatigante agora que ela não partilha das experiências do dia a dia comigo. Ando em um ritmo lento como minha percepção me permite, mas o mundo não espera, ele gira, gira e me derruba como disse de certa forma Jimmy Fontana, merda! Pensei em Jimmy Fontana e isso me lembra ela, é dele a nossa música, bem, ela nunca teve voto nessa decisão, mas nós dois somos fãs do mesmo filme em que essa música aparece, logo essa música é nossa. As ondas estão tão ruidosas hoje, estão fora do ritmo em relação à orquestra urbana/natural que toca nas manhãs cariocas de Copacabana. Olho o relógio e são oito e meia, hoje é sábado, eu não trabalho, bem, menos mal, afinal quinta e sexta foram um suplício interminável, em dois dias que duraram dez anos, não importa o que eu faça, não importa por onde eu ande, eu ainda me lembro do sorriso dela de manhã logo depois de acordar e ver meu rosto amassado, eu lembro dela e de toda intimidade que temos apesar dos longos hiatos que acontecem por causa da rotina e lembrar desses hiatos me deixa inseguro pois lembro que não temos nenhum tipo de relação e que seria perfeitamente normal ela ter ficado com outras pessoas e isso me enche de ciúmes. Molho o pé na água salgada e sagrada para lavar minha mente dessas intemperanças irracionais, esse sentimento de abandono, seguido de miséria profunda e que só são completamente apagados pela presença dela e esse acontecimento denuncia algo perigoso acontecendo no meu cerne pecaminoso, eu estou apaixonado, nunca estive assim antes, mas a paixão é um desses sentimentos autodescritivos que têm tolerância pequena à ignorância e à indiferença, veja bem, eu tentei, eu lutei e venci até quarta-feira de manhã, quando, em um ataque desleal, eu simplesmente percebi de uma vez que não tinha como dissimular mais, rendido segurando as calças assim como Napoleão lá fui eu para o exílio insano do enamorado enquanto ela continua firme como uma rocha, ela simplesmente se levantou e foi pra vida como só mais um dia e eu aqui estou perdido, sem dormir, sem comer direito, com mensagens enviadas ao meu melhor amigo de madrugada que ele ainda não esteve em condições despertas o suficiente para responder e mesmo quando responder vai me dizer o óbvio, porque o que mais ele poderia dizer ? Para eu tomar cuidado? Para não ir com sede ao
pote? Para esperar um sinal dela? Bem, eu já pensei em tudo isso e já coloquei cada um desses planos em prática durante esses últimos três dias, até cair no desespero e mandar algumas mensagens na última madrugada pra ela também, chamei ela pra voltar a vir me visitar, propus um café, uma cerveja, tentei ser cordial, firme, profissional, engraçado, sério, bobo, corajoso, tímido, forte e fraco, tentei de tudo e acabei enviando mensagens demais e agora eu pareço um palhaço que conversa sozinho de madrugada no chat dos outros. Eu tenho aceitado a teoria que eu bolei, que ela deve me achar maluco, pois só isso explica a minha atual atitude de tentar estar perto dela sempre, eu simplesmente estou tão viciado nela que mal lembrei do cigarro nos últimos dias, mas, falando nisso, acendo um cigarro e fumo olhando o mar, me sento ainda admirando a paisagem, o cigarro mata, mas eu nunca senti uma sensação de vício como a que ela me causa, a abstinência dói demais e, por mais que isso que penso agora olhando para essa paisagem maravilhosa seja clichê, ainda assim me pegou desprevenido, me pegou em uma nova sensação de cumplicidade, de amor, de carinho e de amizade e infelizmente, para meu caso em específico, ela tem um botão de on e off para quando quiser, ela vem e vai e eu fico, chupando o dedo (ou cigarro), perdido em mim mesmo como nunca fiquei na vida, como Gregory Samsa eu me metamorfoseei em um ser insustentável. Apago a bituca na areia e guardo para jogá-la no lixo mais próximo, afinal basta eu estar insustentável, eu não preciso piorar as coisas para o planeta. Chego na portaria do meu prédio, lembro de apresentar ela para o Seu Carlos (porteiro) e não saber como classificá-la, me senti tão orgulhoso de tê-la comigo, em uma dessas coisas bobas da paixão que descobri recentemente em mim, que é me sentir sortudo demais por ela estar do meu lado e tenho vontade de sair por aí mostrando-a para qualquer um que me conheça para que eles também possam partilhar da mesma sensação de incredulidade. Entro no meu apartamento silencioso, tudo perfeitamente onde eu deixei, nenhum resquício da pizza que eu fiz para ela nem do filme a que assistimos na tv, do vinho que bebemos, das roupas dela pelo apartamento, nada que prove que aquela noite de terça e manhã de quarta-feira foram reais, nenhuma prova além da minha memória fraca que eu já sinto sendo intoxicada e deformada a cada segundo que passa, como se toda vez que eu puxo a memória eu a degrado mais, impossível eu ter essa memória pura ou até parcialmente fiel a realidade se eu continuar colocando os dedos engordurados da minha consciência sobre a tela fina que guarda o filme dela, a protagonista do meu longa-metragem. Queria ter tirado uma foto pelo menos para ter algo, acho que mostrar ela para o porteiro tinha meio que isso como objetivo também, o de preservar nem que seja na memória alheia, mesmo que seja uma memória inalcançável, eu sei que ela existe e que alguém foi testemunha do acontecimento que essa mulher é, como um evento meteorológico raro, como um milagre, sim, eu precisava de um irmão humano para me fazer crer que ela é real, eu precisava de uma testemunha.

Deitei na cama com um sabor amargo de solidão na boca, ainda relembro o corpo dela no canto da cama e lembro de como o sol driblava as cortinas e tocava o rosto dela naquela manhã de quarta, lembro dos braços dela me abraçando e na paz do rosto dela enquanto ela dormia tranquilamente, eu havia trocado a roupa de cama, mas mantive a fronha do travesseiro que ela usou, gosto de sentir o cheiro dela, logo eu sei que eu não vou me permitir manter esse tipo de conduta, não quero ser confundido com um obcecado psicótico, eu estou guardando esse segredo de mim mesmo, aproveitado esse prazer, antes que meu bom-senso retorne e exija racionalidade e método. Acordei e o sol denunciava que era fim de tarde, me levantei grogue, com o desânimo e confusão mental que só um bom dia de sono é capaz de proporcionar, olho o celular e apenas uma mensagem do grupo de trabalho (alguém perdeu uma chave ou algo assim, enfim, nada importante), uma mensagem da minha irmã, não abri, não estou afim de saber a nova fofoca do grupo de amigas dela em São Paulo, mais alguns grupos notificam, o meu fornecedor de maconha estava sumido há alguns dias, se pá ele se fodeu, nenhuma mensagem dela, ainda olho para o celular como se estivesse interessado pelos assuntos triviais dos grupos, eu vivo em um jogo de detetive comigo mesmo, sempre estou escondendo o que eu sinto de mim e dessa vez eu estou tentando esconder que eu estou decepcionado, eu estava esperando qualquer resposta dela. Saí de casa às seis da tarde, peguei meu carro pouquíssimo usado na garagem, no geral não sou muito fã de dirigir, mas na situação em que estou hoje necessito de um carro, deus me livre esperar um táxi nessa loucura que está o Rio de janeiro em pré-carnaval, pego o carro e sigo em direção ao Leblon até um bar de alguns conhecidos, preciso conversar, comer alguma coisa e principalmente beber para lidar com essa situação, afinal não é fácil para um adulto se apaixonar pela primeira vez, já não temos a elasticidade de alma para lidar com os traumas de uma paixão arrebatadora, com o tempo, a idade pede temperança, em uma categoria meio aristotélica de mediania. Estaciono o carro longe demais do bar, não vai ter como ficar de olho, mas foda-se, qual é a probabilidade? De todos os carros o meu? Sigo até o fim da rua e entro no bar, lá se encontram meus dois amigos mais chegados no Rio, Alexandre e Miguel, cada um de um lado de uma mesa de ferro que ostenta um grande logo de uma marca de cerveja. Para Miguel o que eu tenho é uma grande seca sexual malresolvida que está me gerando uma dependência emocional, nesse momento chega a cerveja, paramos a conversa para dar atenção ao garçom, logo que ele sai, voltamos à conversa, para Alexandre está tudo bem eu estar apaixonado, mas eu preciso colocar as cartas na mesa com ela, odeio as duas possibilidades, mas odeio a segunda opção mais ainda, eu odeio ter que lidar com conversas sérias e odeio falar sobre sentimentos, Alexandre aponta minha masculinidade tóxica enquanto degusta o tira-gosto, mais uma cerveja, eu me defendo como posso, não estou propício a autocritica hoje, volto pra casa no banco de carona do meu carro que por sorte não havia sido roubado, isso de certa forma me decepcionou sobre o Rio de janeiro, eu tinha certeza que alguém roubaria meu carro, mas estava tão fácil que imagino que os ladrões devem ter desconfiado.

Pelo resto da semana eu continuei esperando uma mensagem, para ser sincero eu havia enviado mais uma mensagem pra ela, mas nenhuma resposta, meu ego doeu mais do que a solidão, então eu também decidi ignorá-la. Estava no trabalho terminando um relatório estúpido que só a burocracia capitalista é capaz de criar, meu celular vibra, mensagem dela, ela quer me ver hoje à noite, pressenti uma situação chata que envolve um fora educado naquele molde de ‘não é você, sou eu’. 

Saio da Barra da Tijuca, consigo um táxi na terceira tentativa, o carro está repleto de um perfume doce e barato, atacou minha alergia de imediato, “merda, tudo que eu não preciso é espirrar o resto do dia”. O carro vai passando pelas ruas, eu vejo o sol se pondo aos poucos, ainda há algumas horas de sol, mas já dá pra saber que o dia está acabando e infelizmente a noite está chegando. Minha cabeça está às voltas, no rádio do táxi toca uma mpb antiga que eu não lembro o nome, mas me lembra a casa da minha mãe, sinto vontade de perguntar o nome pro taxista, mas logo a vontade passa, afinal tanto faz o nome da música, eu nunca mais vou escutar ela do mesmo jeito, afinal tudo da minha infância está desforme, a memória nostálgica é uma armadilha em que eu não quero cair.

São seis horas da tarde, estou na frente do espelho, estou arrumado demais, nada que eu visto está bom, minhas mãos estão suadas, e eu estou com o coração batendo de forma descontrolada, e meu cérebro está vazio, decido sair assim mesmo, no fim não importa tanto o quão bem eu estou vestido, tenho o pressentimento que a noite vai ser desagradável de qualquer forma, minha irmã iria discordar desse argumento, afinal para uma designer de moda mesmo as piores situações demandam estilo e elegância.

Pego meu carro e saio pelas ruas, minha primeira intenção é partir ao encontro dela naquele mesmo bar em que a levei no nosso primeiro encontro, mas eu acabo em Copacabana dando voltas, não tenho coragem, no rádio toca John Coltrane, acendo mais um cigarro, em um castigo divino a fumaça vem aos meus olhos, lacrimejo e logo se verte em lágrimas estúpidas, decido não ir, eu não quero um fim, a covardia toma conta de mim e eu continuo dando voltas e estaciono perto da praia, ignorando qualquer risco, começo a vagar pela praia, o oceano ruge em escuridão fantasmagórica, a fumaça do cigarro vai se tornando um com a atmosfera.

Chego em casa, ligo para a minha irmã, ela atende com uma voz preocupada, eu não sou de ligar, ainda mais assim do nada à noite, simplesmente pergunto se posso ficar na casa dela por uns dias, já não suporto mais o Rio, tudo aqui me lembra desse pseudoromance paranoico, logo após ligo para Edgar, meu chefe, ele me atende com mais preocupação ainda, me demito às onze horas da noite de uma quinta-feira, eu não explico o motivo e isso o irrita, mas o que eu posso falar? Não existe nenhuma explicação racional, eu só não quero mais estar aqui.

Parto para São Paulo na segunda, me desfiz de tudo que podia e deixo o resto para que meus amigos resolvam para mim, parto como um covarde, melhor assim, a covardia é extremamente coerente com a minha natureza.

Nunca mais falei com ela, esperava que ela me procurasse, mas não aconteceu, melhor assim, apatia combina perfeitamente com a natureza dela.

<a href="https://instagram.com/dastavio"><i class="bi bi-instagram"></i></a>

