---
title: 'A inveja em Casas Vazias: as desilusões da maternidade '
author: 
  - name: "Livia Marciano"
---

<div style="text-align: right; width: 60%; float:right">
*“A natureza, que em muitas coisas é mais madrasta do que mãe, 
imprimiu nos homens, sobretudo nos mais sensatos, uma fatal 
inclinação no sentido de cada qual não se contentar com o que tem, 
admirando e almejando o que não possui: daí o fato de todos os bens, 
todos os prazeres, todas as belezas da vida se corromperem e se 
reduzirem a nada.”* (Roterdã, 2011, p. 370.)

*"Nunca quis ser mãe, ser mãe é o pior capricho que uma mulher 
pode ter”* (Navarro, 2022, p. 29).
</div>

<div style="clear: both;">

Casas Vazias é uma história sobre ausências e inquietações. Ausência de uma mãe a partir do desaparecimento de seu filho, ausência da mulher que deseja a maternidade, mas que lhe é negada. A violência ao redor dessas duas mães arremata um cenário de ojeriza às mulheres. Brenda Navarro é excepcional na sua escrita, as palavras duras estão ali e te transportam para diferentes realidades sociais a partir do sequestro de uma criança, o menino Daniel.

Para partirmos da mesma página: Casa Vazias é o romance de estreia da mexicana Brenda Navarro, publicado no Brasil em 2022 pela TAG em parceria com a Dublinenses, dois anos depois do seu lançamento no México. Na obra, grande parte escrita em fluxo de pensamento, acompanhamos o desaparecimento de uma criança em plena luz do dia. De um lado, uma mulher que nunca quis ser mãe e perde seu filho em um rápido momento de desentação no parque. Do lado oposto, uma mulher que deseja imensamente a maternidade a ponto de sequestrar uma criança, o pequeno Daniel.

A autora é socióloga especialista em estudos de gênero, o que nos fornece algumas pistas na sua assertividade ao desenhar duas personagens opostas, pela classe social, e próximas, pelas dúvidas e disputas morais impostas pela maternidade: como pensar em uma mãe que renega o filho? Como as estruturas de violência familiar condicionam uma mulher? 

A sombra das estruturas patriarcais na maternidade e na figura feminina atravessam todo o romance. Navarro apresenta uma visão dolorosa sobre as desilusões de uma personagem que lentamente se esvazia, em primeiro momento, com o nascimento do filho e depois, com a perda dele. “Éramos espectros. O que desaparece leva algo da gente que não volta, chama-se sanidade” (p.24). Quando seu filho desaparece e "leva algo junto”, já não há mais a consciência para estabelecer a luta contra os julgamentos do mundo externo. 

De outro lado, uma mulher que deseja ser mãe se confronta com uma dupla desilusão: um filho não é capaz de salvar o seu relacionamento fracassado. Vemos de maneira crua um processo de banalização da violência pelo seu companheiro e sua família que se intensifica com a descoberta de que "Leonel", a criança roubada, era neurodivergente. 

As narradoras nunca são nomeadas, parece-me uma forma de cravar a falta de individualidade a partir da maternidade acidental, que arrebata a vida de duas mulheres. Falhar com a sua "função natural” de "mãe suficientemente boa” é a ruína da primeira. Para a segunda, além do crime condenável, seu desengano se concentra na falsa esperança em uma criança que, em suas idealizações, a salvaria de seu entorno desumanizado pela brutalidade. 

Prolongo a análise sem delimitar a questão da inveja, eis aqui: a autora desenvolve uma trama densa especialmente polêmica e intrinsecamente feminina, não só pelas narradoras mas pelas dores e debates ocultos sobre a maternidade na perspectiva de gênero (própria do seu trabalho como socióloga). No ocidente, a inveja é recorrentemente representada como uma mulher ou, no mínimo, a partir de formas femininas. A individualidade de que falávamos antes toma centralidade ao olharmos para a história dos pecados capitais. A inveja toma proeminência dentre os demais pecados concomitantemente com o surgimento, no século XIX, das noções subjetivas de indivíduo.

Para uma exploração da inveja na obra de Navarro, fiquemos com a classificação da inveja pela psicanalista Melanie Klein:

> “a caracteriza como um sentimento profundamente destrutivo que surge do vazio e de mundos internos devastados, pois esvaziar o leite e a bondade do outro deixa o indivíduo (invejoso) envenenado e danificado, gerando também um ciclo de ódio, de medo de represália, e a inevitabilidade da repetição.” (Harris, 2018, p. 16). 

Se, a partir da psicanálise, pensamos que a inveja surge da insatisfação, desde o nosso nascimento, pelas margens entre falta e desejo, retorno a obra de Navarro para centralizar a inveja na mãe que se faz adotiva. Ao longo de toda a narração, inclusive nos momentos em que a personagem retorna ao passado para pensar sobre sua família, fica claro o grande vazio carregado pela falta de afeto. Há uma cadeia de violências endêmicas que colocam essa personagem em uma situação muito determinante de sua vida. O sequestro de Daniel/Leonel aparece como saída para finalmente quebrar um ciclo vicioso da **falta** de afeto e **desejo** de finalmente “ajeitar” sua vida por meio de uma família. Destaco duas das muitas passagens cruciais que evidenciam minhas suposições; a primeira é a confirmação do desejo e da falta: 

> “Mas é que de verdade, a gente deveria ser uma família, eu queria uma família, queria de Rafael uma família, e disse isso para ele quando saí da casa de minha mãe. Porque eu saí de lá porque ela bateu no meu irmão na última vez que vimos ele.”

A segunda dá enfoque ao arrependimento de suas ações ao deixar que seus sentimentos se sobrepuseram à razão, deixando a inveja falar mais alto: 

> “Assim, eu começava o ano desejando que, naquela tarde, eu não tivesse tido o impulso de abrir a sombrinha vermelha e passear pelo parque como quem não quer nada e levar o menino mais bonito que eu já vi na vida.” 

Muito da desilusão se baseia em invejar uma romantização do "ser mãe”, a ideia de construir uma família perfeita com filhos amorosos retorna à narradora ao cruzar o caminho com a mãe biológica de Daniel/Leonel: 

> “Uma vez fui entregar um pedido [de doces] no Desierto de los Leones, era uma casona no meio de um bosque [...]. Me sentia miserável, com minha roupa velha e meus sapatos quase furados, e todos ali com roupas fresquinhas, suas tacinhas de vinho, seus cabelos limpos, seus sorrisos brancos e perfeitos. Fiquei olhando os convidados, me chamou atenção uma mulher com duas crianças bem loiras. Não estava entendendo bem quem ela era; seria a empregada? Não parecia, estava bem-vestida, relaxada, ao lado de um homem alto, bonito [...]. Fiquei espantada, o menino era o mais bonito que eu já tinha visto. Foi a primeira vez que vi Leonel [...]. Me reacendeu a vontade de ter a minha filha, mas eu não acreditava em mais nada.”

Navarro possui enorme sensibilidade ao encarar as diferenças de gênero e de classe. Especialmente, traduz nessa personagem o desejo pela construção de uma família como forma de suprir uma cadeia estrutural de violência e desafeto. Explorando o caminho tortuoso da maternidade, a autora coloca em destaque a inveja pela perspectiva de virada quando o imenso desejo de possuir “o objeto amado” se transforma em potência destrutiva de si. A obra traz para a superfície dilemas reais da maternidade, jogando luz sobre o vazio identitário que atravessa e destroi duas mulheres de distintas realidades sociais. 

**Referências**

| HARRIS, Adrienne. Inveja Feminina: exploração preliminar. **IDE**, São Paulo, v. 40, n. 65, p. 13-22, nov. 2018.
| NAVARRO, Brenda. **Casas Vazias**. Porto Alegre: Dublinense, 2022. 192 p.
| ROTERDÃ, Erasmo de. **Elogio da Loucura**. Rio de Janeiro: Saraiva de Bolso, 2011. Tradução de: Paulo Oliveira.

</div>

<a href="https://instagram.com/liviamrcn"><i class="bi bi-instagram"></i></a>

