---
title: 'Pleura do momento presente'
author: 
  - name: "Rafael Mendes de Barros"
---

| Saibas que ainda que a vir possa o terror ante de nós imposto
| por alguma das vãs hordas que aqui cercam-nos, já do gosto 
| lembre a grã sensação qual bem nos traz lúpulo mais cevada,
| malte e coisa ademais que se contém nesta fugaz, gelada,
| boa cerveja, afinal tu não ouviu este ditado nosso?
| Vês: bebida nos dá tal lucidez, pois nestas doses, posso,
| homeopáticas é néctar que traz brilho da juventude,
| vir a recuperar tônos e assim mesmo o vigor da saúde, 
| logo após mais um dia tão por banal como por exaustivo…
| Sei que clamas aí todo o voltar teu desse tempo altivo 
| dado aos nossos avós, nem me caber nestas afãs censuras
| ponho-me eu, porque até sei que razão tens no que vez auguras…
| Paulistana de tuas urbes seguir vem ao assaltar dos lobos 
| que fazer se ao votar nossa infeliz turba deixou-nos bobos?
| mas se ruem provisões estas no ser seu da alcatéia difusa,
| cai província, porém na hora ainda não, que antes dormir-o abusa,
| mor poder que se deu p’ra o eleitoral rito do principado…
| Certas vezes nos vêm hienas tomar reino que é destinado 
| para o leão que no então, sorte do enfim, já seguirão bem longe 
| dessa audaz capital que em federal paço no cerne esconde 
| selva própria ao matiz teu do acordar tão natural da pólis;
| lembra: o estrago se deu fruto do aquém vão rebelar, conformes
| fez-se às massas qualquer tipo de ação; caiu uma presidente,
| desde outrora, no andar, vamos por vir, como que residente
| deste abismo,e no assim: cabra a fugir desses leões, e os leões 
| são cercados a fio pelas desleais hienas; tecer canções 
| passa o Tempo, entretém, mas não nos dá são verniz do amanhã…
| nota em trópicos que todas as crias, filhos da terra irmã,
| temem ver Sucuri que é por algoz tudo, porém até 
| furta-se ela ao Jaguar, tal parecer certo nos diz: é o que é;
| e há a República ter que se encontrar próprio com teu Jaguar, 
| vãos momentos tombar foram Aqueus reinos ou Roma e dar
| para ti meu falar pouco sei que eu tenho; beber, o músculo 
| nos relaxa a pensar: — Oh como é boa perto do breu crepúsculo!
| Já aos antigos se pôr por invejar, tu no tentar, não mais
| venhas: Tempo a voltar nunca nos vem, justo p’ra o Amor jamais…

<a href="https://instagram.com/rafael.mendes_10"><i class="bi bi-instagram"></i></a>

