---
title: Resenha do filme *"Barbie"*
author: 
  - name: Cibele Brotto
---

Desculpa surfar na onda desse hype, mas agora que você está aqui, vou mandar a real: não é uma resenha sobre o filme. Ou é. Depende do ponto de vista.

Na verdade, é mais um comentário no meu estilo *filósofa de botequim* sobre o que ficou aqui depois dessa experiência. Mas preciso confessar que enquanto estava preparando a edição e pensando nos textos que seriam publicados este mês, uma pergunta ficou ressoando na minha cabeça: até que ponto a imagem influencia o tesão? Eu sei que pode parecer bobo e óbvio, mas essas são as inquietações que mais me interessam. Quanto mais visível, mais instigante. 

De cara, alguns serão enfáticos sobre a influência da beleza no jogo da sedução. Já outros, dirão que o que importa é a essência. Na película, essa me pareceu uma das questões centrais, afinal, a Barbie só se move em direção à uma aventura de caráter existencial depois de conceber celulites. Quando ela se encontra extremamente triste, a razão da sua maior decepção e desilusão com o seu mundo antes perfeito é agora se perceber feia. E isso significa deixar de ser olhada e desejada. Essa é uma quebra drástica, afinal, a Barbie é envolta em um mundo sedutor. Ela tem e pode ser tudo, é onipotente. E onipresente, pois todas são Barbies, *"hi, Barbie"*.

Esse olhar, que no mundo invertido da Barbie afeta o Ken, mero acessório da narrativa da boneca, explicita muito bem o desejo de ser reconhecido pelo outro, *“I only exist within the warmth of your gaze”*. O fato de a Barbie viver em um mundo feito para ela e não se dar conta da existência do Ken ou considerar os seus desejos, me parece muito o que acontece simbolicamente com as mulheres no nosso mundo real. As imagens tem continuidade em retas paralelas, no mundo da Barbie o Ken precisa ser validado, ele é feito para isso, no seu mundo e no mundo real, a Barbie precisa ser desejada. No mundo real é à mulher que esse papel foi atribuído. A necessidade da validação do olhar do outro é imperativa para a sua existência e, para isso, se torna necessário manipular diversos artifícios para que esse corpo seja atraente. Desde a pose até a textura da pele. 

No entanto, se torna evidente que a necessidade de empenhar-se para atingir o inalcançável esteticamente, até mesmo no sentido do que é "legal" socialmente, ou seja, a moda, se constitui numa busca terrivelmente equivocada em termos de acolhida. Por esse motivo, o Ken nunca conquista a Barbie, mesmo sendo lindo e apaixonado, nem a Barbie conquista as adolescentes, mesmo incorporando o ideal de feminino contemporâneo com seus diversos atributos físicos, intelectuais e capitais, tampouco as mulheres são bem sucedidas, pois mesmo respondendo a duras penas as diversas demandas do nosso mundo, ainda lutam para conquistar uma posição de autonomia simbólica e política. Me parece que aí existe a grande falha, a eterna insuficiência no olhar do outro, ou pior, do nosso. Sempre vai existir um detalhe a ser lapidado, a armadilha é justamente tentar satisfazer essa lacuna a qualquer custo. Nenhuma estrutura mental pode vencer essa empreitada. Tá aí o jogo.

Até que ponto a imagem influencia o tesão? Sinceramente, acho que pouco. A beleza é relativa, assim como os valores que compõem a essência de cada um. Me parece que a questão precisaria mudar, até que ponto *a nossa própria imagem* influencia o tesão? Assim, seria muito mais interessante pensar o quanto a nossa autoestima é sequestrada pelos outros - e o quanto legitimamos isso. Pior ainda, pelo o que supomos que os outros esperam. Talvez, se eu me sentisse possuidora do meu corpo e confortável com ele, eu conseguisse gozar mais. Talvez, esse deva ser justamente o problema.

