---
title: "O canto da sereia"
author: 
  - name: Artemísia Sales
---

| No oceano profundo dos seus olhos, 
| Vejo o mar que não enxerguei ao meu redor. 
| Seu jeito demorado, decidido,
| Me fez querer salvar sua vida 
| Ao invés de destruí-la.
| 
| Neste cemitério de abismos, 
| O homem de Apolo desvenda meus olhos
| E me sinto impelida a buscar a superfície 
| Em seu rosto tranquilo. 
| 
| Não se afogue querido, 
| No anseio da alma, 
| No medo das paixões. 
| Eu, criatura sombria 
| Enlouquecida pela lira do deus solar, 
| Observo seu corpo de cores quentes 
| Se projetar belo sobre as ondas.
| 
| Será que busca abraçar meu corpo 
| Inclinado nos rochedos obscuros?
| Não vê que sou apenas pouco mulher 
| E bastante horrenda? 
| Mas o homem que toca as chamas do sol 
| Não teme o frio das águas escuras, 
| Envoltas em meu cabelo ondulante,
| E vê sua sereia com uma magia encantadora. 
| 
| Serpenteio meus braços em sua direção,
| Guiada por teu olhar celestial.
| Sabe que no seu rosto encontrei o calor 
| Que precisava para despertar meu feitiço. 
| 
| Canto a minha canção a ti, 
| Mas não me escuta em seu delírio divino
| - Apenas ouve os sussurros distantes.
| 
| Então venha e me encare uma vez mais, 
| Meu deus inebriante,
| E veja a sereia que faz da ilusão, 
| O desejo.  
| E anseie por mim, me tome para si  
| Do mesmo modo que bebe o vinho, 
| E me toque, 
| Do modo que se tocam suas antigas canções. 
| 
| Pegue meu coração e o queime
| Em suas chamas de sol, 
| Seja minha âncora nesse mar tortuoso,
| Ame a sereia que fantasia 
| Seu ritmo indecifrável 
| E ame o fato de nunca poder tocá-la. 
| 
| Pois ela já não existe, 
| A não ser nesta tragédia
| Que narra a história da memória 
| Em sua melodia jamais esquecida,
| Dos tempos míticos dos deuses e criaturas
| Enlouquecidos pelos amores
| Versados no canto da musa.

