---
title: Devasso
author:
- name: Otavio de Sousa
categories:
- POEMA

---

| Tenho imaginado
| Você cruzando a porta
| Vindo em minha direção
| Um olhar erótico
| Afinal isso é um sonho
| Safado
| Perdição
| Acelerado
| O coração é ereção
| Um toque no meu braço
| Um beijo encontrado
| Você nua ao meu lado
| Sem explicação
| Tenho imaginado
| Cenas de filmes
| Pornográficos
| Mas sem a parte encenada
| Apenas paixão
| Sem a parte mentira
| Sem a indústria fria
| É algo pessoal
| Mais meu que seu
| Apenas
| Tesão
| Ao seu lado
| Sem razão
| Tenho me masturbado
| Com alguém inventado
| Pois você não é
| Aquela da minha
| Imaginação
| Mas ainda quero que bata
| Na porta
| A qualquer hora
| Me peça por algo
| E terminamos
| Isso no colchão
| Não quero o sexo em si
| É algo além
| Quero a experiência
| De ti
| Quase aquém
| Do possível
| Do plausível
| Da visão
| Quero que sem ti
| Eu possa sentir
| A sua respiração
| Quero você de quatro
| Entregue aos meus braços
| Como uma
| Meditação
| Sentir seus seios
| Seus lábios
| E seu orgasmo
| Na minha
| Mão
| Quero que isso saia da minha mente
| Que seja algo diferente
| Que realmente exista algo
| Sem ação
| Não é como se eu sentisse a necessidade
| De te tocar
| Eu quero que você me toque
| Pelo seu bel prazer
| Quero ser desejado
| É um sentimento engraçado
| Algo que não pode ser evitado
| Acredite
| Eu tentei
| Tentação
| Quero uma noite
| Apenas uma noite
| De todo nosso prazer
| Nos açoite
| Servidão
| Me sinto servo
| Do meu ego
| Que recalca o desejo
| Escuridão
| Em uma parte qualquer
| Do meu cérebro
| E essa libertinagem
| Que eu tanto quero
| Por perto
| Seu corpo
| Por baixo
| Do meu
| Você sussurrando meu nome
| Devassidão

<a href="https://instagram.com/dastavio"><i class="bi bi-instagram"></i></a>
