---
title: "febre"
author: 
  - name: Sea Stars
---

| A atmosfera do quarto ferve,
| Assim como seu toque em minha pele.
| Suas mãos passeiam livremente por toda a extensão das minhas pernas,
| E seus beijos reivindicando cada pedaço da minha carne como sua, me deixam em
| febre.
| 
| Suas hábeis e delicadas mãos invadem a minha saia,
| As pontas dos seus dedos incendiando cada mísera fibra do meu corpo,
| Eles deixam pequenos incêndios por toda parte.
| 
| Minha blusa desliza dos meus ombros para o chão, arrepiando-me dos pés a cabeça.
| Você brinca com as alças do sutiã roxo que uso, querendo ver o meu desespero
| transparecer em sílabas pronunciadas pelos meus lábios.
| 
| Sua língua invade a minha boca e eu provo o seu refrescante gosto de menta, que parece
| deixar tudo mais fervente.
| Já não sinto a saia ir para o chão, quando você morde com uma delicadeza bruta a pele
| recém exposta do meu seio.
| 
| Os beijos sobem pelos meus tornozelos e inferno, você era a encarnação do próprio
| diabo.
| E eu me sinto entrar em uma febril combustão, quando você finalmente me dá aquela
| atenção.
| 
| Sinto-me sapatear nas brasas do seu reino de pecados, quando você vai o mais fundo
| que pode dentro de mim.
| Você comanda tudo e me olha com atenção, assistindo-me febrilmente queimar.
| Desfaço com o corpo em chamas, e o olhar que você me lança, indica que acabamos
| apenas de começar.
| 
| Todo esse fogo é perigoso, o ardor é o bastante para matar.
| Você me dá febre.
| 
| E mesmo que eu possa morrer,
| Eu amo a maneira como você me queima e incendeia.


<a href="https://instagram.com/meet.inthesea"><i class="bi bi-instagram"></i></a>
