---
title: nós
author:
- name: Vandoski & B.S.
categories:
- LÍRICO

---

<p style="text-align: center; text-style: bold;">**I**</p> 

É difícil escrever sobre algo que não precisou passar, contorcer, rasgar e sofrer para transitar dentro do meu grande novelo enrolado, que carinhosamente chamo de “eu”.

Não tentei te decifrar, não fiquei analisando o quanto me queria, ou pior, se queria o que eu estava fazendo. Sempre tive a devolutiva como norte e nunca chupei sem olhar de relance pra boca… Mas você, com seu esforço admirável em silenciar o que começa como impulso e termina em um som intenso e curto, consegue falar diretamente com o que há de mais primitivo em mim. 

Com você foi diferente; em momento algum questionei estar lá. Não me obriguei a largar a luxúria que foi me permitir flertar com uma realidade em que, ao invés de partir de mim, partimos juntos. 

<p style="text-align: center; text-style: bold;">**II**</p> 

| *Você segura a minha mão e me conduz a lugares inimagináveis.*
| 
| *Delineio-me em notas penetrantes e você me lê com voracidade.*
| *Comunicamo-nos na mesma coreografia e, em um abraço cerrado, sinto a vibração de cada átomo do seu ser.*
| *Entrego-me.*
| *Você dedilha notas e melodias por todo meu copo.*
| *Entrego-me;*
| *ofegante por ter você em totalidade, completamente sua, na harmônica consonância de ser um.*
| 
| *[Você, em redundância. Nós, em unidade].*


