---
title: O rapto da razão
author:
- name: Frans Amorim
categories:
- POEMA

---

| Tempestuoso como os dilúvios de março
| Naufrago entre desejos e amores
| Os naufrágios que ajudei a me empurrarem
| Às profundezas de meu furtivo ser
| 
| Uma Helena, bela, bela Helena, me monta o cerco
| Seria a de Troia?
| A mulher que nos ensinou que todo amor
| É sangue, é guerra, é fantasia, é morte e é também conquista
| 
| Para o coração apaixonado, cabe uma vida inteira num único dia
| Bem soube Ulisses, o traidor e o traído
| O costurar obsceno de Penélope, feito e refeito
| Fio a fio costurando pele com pele
| 
| Minhas epopeias trocam o heroico do alto
| Por algo de baixo que seja heroico
| Não haverá mais Penélope esperando meu traiçoeiro e cigano Ulisses
| 
| Continuarei a viajar até que, de navio em navio, Poseidon me roube
| Libertaremos a sábia e exausta Atena
| A sempre-mãe, a sempre-protetora
| Pedem outra sabedoria essas formas de viver
| Outras presenças.

<a href="https://instagram.com/_fransamorim"><i class="bi bi-instagram"></i></a>
