---
title: seu rosto é uma pintura
author:
- name: Samira Clissa
categories:
- LÍRICO

---

Seu rosto é uma pintura, uma das mais belas obras-primas que eu já vi. Seus olhos são oceanos, e seriam o Pacífico, se não fosse pela intensidade com a qual eles me encaram, como se quisessem me despir por inteira. Seus cabelos são tão escuros como a noite de uma cidade pequena do interior, e sempre tão bagunçados, tornando sua cabeça um mar negro.

Absolutamente tudo o que faz me excita. O jeito que ele dispõe seus braços ao redor de seu corpo quando está com frio, como ele inclina as costas quando se aproxima de mim, a maneira com que  seus lábios, cor de pétalas das rosas que nascem na primavera, dançam suavemente quando ele recita um poema hesiódico. 

Tudo nele torna-me mulher, e conheço-me conforme o desejo. 

Quero que ele me toque, que me coloque contra a parede e que sussurre meu nome. Quero me juntar a ele, de maneira que sejamos duas almas numa mesma carne. Quero que ele queira assim como eu quero. Que ele queime por mim assim como eu queimo por ele.

Não há nada que me impeça de fazer todas as coisas que imagino. Imagino-me memorizando seu rosto como as páginas de um livro, imagino sua mão sobre o coração enquanto seu olhar me perfura. Imagino seu toque sobre meu altar, seu beijo contra meus lábios. 

Não consigo evitar nada disso quando o vejo passar. Roupas no chão e mãos nos cabelos, sem regras ou prudência que possam nos dividir. *Não conseguiremos escapar disso*, ele me diz. Mordo os lábios enquanto ele sussurra tudo o que quer comigo, e eu sei que um dia, nós iremos fazer tudo o que eu imagino.


<a href="https://instagram.com/samyclissa"><i class="bi bi-instagram"></i></a>
