---
title: 'a Boba'
author: 
  - name: "Monalisa de Bandana"
---


:::{.line-height}
| Escuta bem, que essa podia ser pra você, na verdade, quem sabe ela não é? 
|
| Que engraçado 
| Engraçado você 
| Agia no não me querer, e coincidentemente depois do bloqueio até mandou seus amigos me seguirem para saber de minha vida 
| Esse afeto era de chove e não molha, descaso constante e incerteza absurda que incomoda
| Poderia eu negar todas as solicitações, entretanto até prefiro que me vejam, deixe que pratiquem o exercício de me olhar e trabalhem a língua incansavelmente ao me devorar
| Na nova conta, recebi tua DM. Agora o restaurante do meu eu fechou e você quer comer? 
| Depois daquilo achei que cê não queria 
| E vindo de um branco, bombado, padrão, até que eu entenderia 
| Contou para eles daquele fatídico dia? 
| Dia de nosso encontro, e eu toda ingênua, mal sabia que um terceiro você também levaria
| Até palavras motivacionais das funcionárias do estabelecimento ouvi 
| Eu estava para uma Malfati completa, porém você decidiu que seria válido me reduzir apenas a uma Boba mal-interpretada
| Meu sorriso caiu por terra, minha alegria havia sido cancelada, estava propenso a me tornar o maior emo das trevas. Agora, sem apetite e com refluxo
| O que não te contei é que na imensa bolsa que levei, lá dentro dedicado a você havia guardado um arranjo de flores, belos jasmins tão cheirosos que estavam a atrair todos os bem-te-vis, sabiás, beija-flores, andorinhas, maritacas
| Não contente em te exaltar, tinha também um chocolate daqueles caros, nele grampeado, uma cartinha que dizia: “desejo, necessidade, vontade… você tem fome de quê? Eu tenho fome de você”
| E, olha, eu mal sabia.
| 
| No final daquela noite, dividi o chocolate com minha irmã. Alguém que realmente o sabia apreciar
| O buquê dei a quem pudesse a natureza contemplar
| Que engraçado você 
| Que agora volta por entre os panos a me procurar como um cão faminto e sem lar 
| Imagine só se soubesse tudo que eu havia feito
| Teria ainda sido esse ser cheio de desfeito?
:::

<a href="https://instagram.com/monalisadebandana"><i class="bi bi-instagram"></i></a>
