---
title: Banquete do tempo
author:
- name: Henrique de Oliveira Calheiros
categories:
- POEMA

---

| Abro um círculo, abro a boca e devoro um relógio
| Devoro porque posso, porque passa
| Dentro do círculo mastigo os ponteiros
| Eretos monumentos do tempo
| Os reduzo a palitos de dente
| 
| Conduzo um ritual a Cronos
| Uma revolução absoluta
| Rompendo com o rompimento
| E com a certeza do lamento
| 
| A terra vibra e canta solene
| Contrasta meu timbre perene
| Protesto! Não quero sumir
| De um tique para um taque partir
| 
| Na Ciranda, comendo
| Ascendo assim sendo
| Rindo e roendo
| Nascido e nascendo
| 
| Revolta com cada volta
| Que desatina indiferente
| Conduz a vida a frente
| Independente do que sente
| Ou pensa minha mente
| 
| Abri um círculo e a boca
| E desafio a ideia oca
| De aceitar a tradição
| Não! Estilhaço esse vitral
| Essa sina ancestral
| 
| Recuso o que conheço
| Mas reconheço que desconheço
| Para além de minhas fronteiras
| Desconstruo minha cela
| Transfiguro em aquarela
| O que se passa entre as orelhas
| 
| Na vanguarda de minha jornada
| Fecho a boca e o portal
| Observo a dança astral
| Da qual não entendo nada
| E em cada elemento
| Ecoa um momento
| De uma vida passada
| 
| Passada a tristeza
| O que resta na mesa
| É a natureza
| Do tempo, da vida
| Incompreendida
| Decifre-mo-na em paz
| Pois no banquete do tempo
| Não há história repetida
| Pois a cadência de cada batida
| É a gente que faz.


<a href="https://instagram.com/henrique_calheiro"><i class="bi bi-instagram"></i></a>
