---
title: <b>h u n  g  r   y  .</b>
author:
- name: Lucas Boldo
categories:
- LÍRICO

---

:::{.right}
| a carne já não me sacia
| nem a morta, nem a tua
| as palavras não têm mais açúcar
| as pílulas descem secas
| sinto azia ao trocar de música
| as infinitas fotos são todas intragáveis
| excessivamente abundantes
| tenho fome de algo novo
| longe de tudo que conheço ou conhecerei
:::

---

Quero respirar a fumaça mais tóxica que houver e reclamar meus pulmões sãos
ouvir os gritos, plantar o licor das festas e colher a falsa polpa da modernidade
novos programas, propagandas, sorrisos cheios de lentes 
um punhado de luzes pixeladas, nupérrimas, distrair mente e estômago
ficar estufada de um nada recém-adquirido – que quero renovar em 12 parcelas
gozar com recortes desfigurados, peitos, coxas, costelas, corpo nenhum
engolir o tempo que deslizo com os dedos para o fundo das minhas olheiras
ver-me espelhada no escuro, resignando-me à minha fome



<a href="https://instagram.com/boldo.lucas"><i class="bi bi-instagram"></i></a>
