---
title: Tenho fome de…
author:
- name: Amanda Genevieve
categories:
- LÍRICO

---

Acho que a fome é um buraco que fica por um tempo no nosso interior, mostrando que estamos incompletos, que algo nos falta. 

Vago por aí buscando algo que vá preencher esse vazio, algo que vá me tirar desse buraco e me aliviar da sensação de que ainda sou tão incompleta. 

Tenho fome de me sentir em casa, de ter um lar em que eu possa descansar, de achar um ponto na minha vida em que eu sinta que agora tudo vai se ressignificar e mostrar que o tempo de sentir tanta dor se cessou, que agora tudo será diferente. 

Minha alma tem fome, tem sede e vai à caça todo dia. 

Chego a pensar que a minha alma é selvagem, de tanto que busca, de tanto que caça alguma presa a fim de preencher esse vazio que anda comigo há tanto tempo, que quase se tornou minha extensão. 

Acontece que almas selvagens sabem onde buscar suas presas, sabem o momento certo para se suprir e suprir o vazio que reside no nosso interior, como sabem também o instante exato em que só um outro alguém vai saciar a minha, tão nossa fome de solidão. Almas selvagens sabem se desprender da fome, entendem que por mais que a fome esteja as acompanhando por tanto tempo conseguem se enxergar sem ela, conseguem se ver de uma forma mais livre –  por mais que a liberdade estivesse sempre tão fora do seu alcance. Por isso que quando a fome é saciada me vejo perdida, tentando me entender como sou sem ela. 

Não sei como é seguir meu caminho tão livre assim.

<a href="https://instagram.com/Amandaa.ols"><i class="bi bi-instagram"></i></a>
