---
title: 'Caspita'
author: 
  - name: "Brunno R. Sousa"
---

Sinceramente, estou com raiva. Do que? Deus há de saber, porque eu decerto não sei, e
olha que sei de muitas coisas, mas ultimamente tenho andado tão perplexo e injuriado com
minha própria mente que falho constantemente em percebê-la. Está aqui, quase intacta,
perfeitamente usada e em terríveis ótimas condições, boa o suficiente para funcionar dentro
de meu corpo que não é bom o bastante para tê-la, e disso tire suas próprias conclusões. O
ponto é que estou fulo! Por quê? Como eu bem disse, Deus há de saber, mas eu? Eu me
encontro vítima de mim, de minha fúria, chora ó deusa a cólera do pobre coitado que sou,
que tanta morte trouxe a si mesmo, que tanto ódio infundado deixou à tona com suas
palavras inflamadas. Falho finito filho de finados. Me engano, no caso, minha mente me
engana, luta contra mim, maldita criatura sedentária, me faz cruel, frenético, exigente, certo
estava Cesário Verde, pois me vejo agora maluco, insano, doente.

Falha introdução. Certo, me deixe começar mais uma vez. Sinto raiva, mas não consigo
entender se é de mim mesmo, do mundo, da moda, dos modos, das mentes. Minto, eu sei
muito bem o que estou sentindo, mas me faltam palavras para explicar o infinito abismo que
é se enraivecer por nada. O abismo, o nada, a noite, à noite, o infinito abismo, as infinitas
palavras, mas que merda, mas que inferno, mas que caspita! Claro, me vejo cego, cego de
raiva, e então escrevo, vejo a infinidade do céu escuro e escuto ao fundo minha mente se
precipitar, ou seria a chuva? Me inundo em pensamentos explosivos e vigio as estrelas para
que não saiam do lugar, controlo o véu noturno e vejo a vida, vejo a vela, vejo nada, beijo
ela, sinto calma. Pela primeira vez em tanto tempo sinto calma, e ela contrasta minha raiva,
a deixa vermelha em um mar azul, sangue na água.

Me aprofundo em um mar nem um pouco complexo, e entendo com facilidade a fluidez
da vida, das coisas, do mundo. Chego ao fim de minhas forças formais e minha forma
mental se expande além do que existe em mim de mais obscuro. Digo palavras difíceis,
faço rimas fáceis, insisto em aliterações preguiçosas para que alguém, em algum lugar,
possa achar graça, mesmo que não seja de verdade. Olho para a folha e se passaram
horas, o nada se tornou alguma coisa, respira e berra na minha frente, e em minha mente
vivi toda sua história. A raiva, ela se foi, e só Deus há de saber o que era de início, mas
agora que vive expressa em minhas palavras, sinto que já é seguro voltar.



<a href="https://instagram.com/maybebrunno"><i class="bi bi-instagram"></i></a>
<a href="https://instagram.com/sadmancafe"><i class="bi bi-instagram"></i></a>
