---
title: 'Desproporção'
author: 
  - name: "Rafael Mendes de Barros"
---

Oh, por que desferir contra o meu ser Ira tamanha em ação 
pela qual nosso Deus vem se ofender? Vês que desproporção 
nesta vida é o causar todo ao feliz ou do infeliz desfecho, 
pouco restam-me aqui louros dos quais — poeta ser, não me fecho
para a vida — possa eu ter a orgulhar, nem desses faustos tantos,
prêmios mor ou quiçá desses troféus tenho comigo espantos
dessas glórias; porém trago de mim mesmo qualquer, de histórias,
coisa tal lá do bar, vinho e dos mais, que no marcar memórias 
eram amigos de estar junto ao juntar copos, pois preferi
mais mulheres dispor, graças em flor, tudo era o que eu pedi 
nesse altar… Se restou de algo em bordel ou nas bacantes foi
níquel que se perdeu, saiba rapaz: viva assaz, ria, diga oi;
cabe a Ossanha possuir ritos do Amor com ervas medicinais,
não se zangues atoa, abra sua mão, tente observar sinais…

<a href="https://instagram.com/rafael.mendes_10"><i class="bi bi-instagram"></i></a>
