---
title: 'O tal retorno'
author: 
  - name: "Giovanna Sabino"
---


Caro leitor,

Ouvi outro dia um homem que gritava a plenos pulmões no meio do metrô: "Jesus irá voltar".

Isso me fez refletir em todo o caminho de volta pra casa, como a definitivamente nenhum pouco cristã cabeça pensante que sou:

Jesus irá voltar? ... Irá? 

Refleti se a conjugação do verbo parecia apropriada à situação... Ele irá no futuro voltar ? Não me parece o caso.

Jesus, aquele Jesus da Bíblia... O que eu mesmo não conheço tanto... Ele já voltou várias vezes.

Jesus voltou como todas as crianças pretas que morreram com tiros dados pela polícia a caminho da escola.

Jesus voltou como Dandara, espancada pela ignorância e pelo ódio, por todos aqueles que toleram tudo o que há de ruim no mundo, mas não a existência de uma mulher.

Jesus voltou como Miguel, ignorado e desprezado pela burguesia, sozinho em uma queda de 9 andares.

Jesus voltou e morreu no pavilhão 9 do Carandiru, sem direito à lei, ou advogado, engasgado com o próprio sangue sob os olhos frios da “justiça” do governador, que descansava no ar condicionado.

Meu amigo, volta um Jesus todo ano e todo ano o matam. O que não faltaram até agora foram Jesuses na nossa história, o que não faltaram até agora foram aspirantes a Jesuses: Todos mortos... Todos assassinados.

Trucidados, fuzilados, torturados, desaparecidos.

Caro leitor, esse retorno é mesmo o problema? Acho que até eu, com minha cristandade questionável, posso ver que a questão vai além: É sobre o nosso constante vício, não... me corrijo, é sobre a nossa incapacidade de não matar o senhor menino Jesus sempre que ele tenta voltar.

O ódio é predatório e ciumento, e caça toda mínima faísca de luz que encontra.

E depois de pensar sobre isso, leitor, um pensamento mais assustador cruzou-me a mente:

Se o tal Jesus da Bíblia, aquele que os cristãos tanto gostam, retornasse... se ele visse a história de Dandara, a de Miguel, a das crianças, a do Carandiru…ele ficaria? Você ficaria? Quem, de fato, ficaria, meu leitor?

<a href="https://instagram.com/forlissies"><i class="bi bi-instagram"></i></a>
