---
title: 'Campampante'
author: 
  - name: "Caio Aruanã Batista"
categories:
- CONTO
---

Numa angulação, indiferente para a maioria, encontro o substrato da minha alma como que intocado pelos caminhos batidos das estradas esquecidas. Encontro, no recôndito mais inexplorado, a esperança da existência dum lugar cuja presença não se faça presente.

Alimento minha fome, fome de pertencimento, no galope apaixonado do roçado. Como que adentro, passo a passo, a constelação natural das mesófitas do gado que pasta, na maestria da existência, ruminando pelas encostas ensolaradas do sertão. Escuto, ao longe, a sinfonia do rei anu-branco, respondida pelo chopim-do-brejo e redarguida pelo amigo curió-ó. De costas, corre o mundo.

Sentado, no topo dum morro, ressoa o cheiro do pito. Tento, ao máximo, eternizar o instante esvoaçante que, dali a pouco, será memória. Tento, como quem tenta agarrar o conceito sensificado, exprimir o inexprimível que, repetidamente, se furta à palavra. Pito, no mais das vezes, ladino.

Longe de tudo e perto de nada, abro, como uma brecha, a possibilidade do esquecimento da totalidade. Arreio a mula, acendo o paiero e galopo sem bulha na escuridão do imaginário, em que cada estalo é assombrado. Existindo, na indiferença do mundo, sou tomado pela mansidão que, incessantemente, grila na angulação do meu intocado.


<a href="https://instagram.com/Batista.caioaruana"><i class="bi bi-instagram"></i></a>
