---
title: 'Indiferença'
author: 
  - name: "Amanda Genevieve"
categories:
- CRÔNICA
---

Era uma sexta-feira, saí do trabalho, passei em casa, me arrumei e fui em direção ao bar
para me encontrar com a minha amiga Laura.

Pedimos duas cervejas e uma batata frita, Laura parecia inquieta demais, suas pernas não
paravam de balançar embaixo da mesa, falava com ela e era como se ela não tivesse me
escutando, ficava olhando ao redor como quem espera por alguém ansiosamente. Irritada
com toda essa ansiedade dela, falei:

-- Que que foi, hein!? Não para de mexer as pernas, não me escuta direito, nem parece que tá aqui. O que tá acontecendo?

Laura disse:

-- Sabe o que que é? Às vezes eu queria ser que nem você, desprendida, não ligar pra quase nada. Desde que o Paulo chegou na minha vida, ando inquieta demais. Não penso em outra coisa sem ser ele, ando medrosa demais, ao mesmo tempo que me sinto corajosa, pronta para tudo. O amor me invadiu e às vezes me pergunto se não é doença, ou loucura minha, porque deito minha cabeça para dormir, a minha mente me lembra o som da voz dele, ou a forma como ele me olha com seus olhos grandes e castanhos. Parece que a minha mente é mais dele do que a minha.

Aliviada que eu finalmente entendi a sua inquietude, respondi:

-- Estou desprendida, porque não tô amando ninguém nesse nível no momento. Você... já tá. E o amor nada tem a ver com a indiferença. É muito cuidado quando se ama, é muito olhar pra si, olhar pro outro. Nos desencontramos e encontramos várias vezes quando amamos. Por isso as pernas balançando, você tá aprendendo a amar e entendendo que, por mais que a gente queira muito um amor, a gente estranha quando ele chega, porque ele não avisa que vem com tanta confusão, alegria, sons altos, risos largos, choros exagerados e saudades intensas, parece que é um corpo estranho dentro da gente, de tanto que faz a gente se mexer com essa mistura de emoções. A gente quer devorar esse amor que tanto nos devora. Estar desprendida é estar indiferente e a indiferença não gera movimento. Não é à toa que o amor te invadiu e desde então a indiferença foi embora. Amor é movimento, é a gente querer melhorar pro outro, melhorar pra gente mesmo. Indiferença é uma certa quietude, que gosta de estar onde está, não olha tanto pro outro e, por isso, se aquieta. Parece que você tá enlouquecendo, mas você só tá amando. Saiu da inércia, para o amor.


<a href="https://instagram.com/Amandaa.ols"><i class="bi bi-instagram"></i></a>
