---
title: 'Tem lugar para mim?'
author: 
  - name: "Paula S."
categories:
- CONTO
---

Um elevador. Normal, comum, nada de especial, o único no prédio. Mas em sua porta fechada há faixas amarelas e pretas se cruzando, quase como uma cena de crime, e nas suas portas um aviso colado, o elevador se encontra quebrado, sem previsão de conserto.

Mas não tem problema, o aviso lhe deixa saber que é possível usar o elevador do prédio ao lado para chegar nos andares superiores. Simples, não é?

*O tornozelo explode, o joelho sai do lugar, o quadril chora, a cadeira range, a coluna pede arrego.*

Calma, não precisam reclamar, vocês têm três escolhas, a primeira é simplesmente subir alguns lances de escada. É igual a arrancar um band aid, pode até doer, mas acaba rápido.

A segunda é retornar o caminho que acabaram de fazer, andar uns cem metros e subir alguns degraus para chegar no prédio aqui do lado, lá o elevador funciona, um pouco melhor, não é? Sempre tem jeito para tudo! Vocês só precisam aprender a olhar para as possibilidades que a vida dá, se vocês ficarem reclamando assim, tem gente que vai achar que estão se fazendo de vítimas.

Ah, você não pode subir uma escada de jeito algum? Bom, hum, tem a última opção, não precisa subir um único degrau, olha que bom! É só andar por aproximadamente quinhentos metros, enfrentar uma pequena subida, bem pequena, entrar por aquele outro prédio lá, e andar mais uns quinhentos metros, fácil assim. Eu levo só uns cinco minutinhos a mais fazendo isso, é bem tranquilo.

*dor, dor, dor. O passo falha, o joelho estrala, a muleta machuca o braço, a roda emperra, a mão suada escorrega da bengala. dor, Dor, DOR.*

E isso só nessa primeira vez, agora que vocês já sabem desse pequeno inconveniente nos próximos dias podem ir direto para o terceiro prédio, por ali você só anda algumas centenas de metros. Sem grandes dificuldades.

O que foi? Você vem de ônibus e o ponto que ele para não é perto dessa entrada? Bom, por que vocês não se juntam e pedem uber? Não tem ninguém que pode dar uma carona? É, seria bom se tivessem carro, sabiam que têm desconto, quem me dera. Olha, queria poder fazer mais por vocês, mas agora não tá dando, tem muita gente sofrendo com a falta de verba, não são só vocês. \[Sinceramente, se vira, não é o que você já tem que fazer todo santo dia, no ônibus, no metrô, na rua, no trabalho, na escola, na faculdade, no cinema, no show, no jogo de futebol, no restaurante ou no bar quando sai com seus amigos, e sei lá mais por onde que você anda?\]

*Todo dia, será que dá, quantos metros faltam, tem como fazer esse caminho, tem outra rota, tem rampa, tem elevador, tem degrau, tem como usar o banheiro…*

*Tem lugar para mim?*

Pessoal, não adianta se alterar. Não estão grandinhos o suficiente para saberem que o mundo não gira em torno de vocês? Todos temos algum problema, vocês precisam ser fortes, mostrar para o resto do mundo que são capazes mesmo com as suas questões, são verdadeiros heróis e heroínas, deviam se orgulhar disso.

Sei que não é fácil, eu mesmo sofro com um monte de dor pelo corpo, a idade chega e isso acontece, mas olha para vocês ainda jovens, a vida toda pela frente. É chato mesmo essa situação, eu tô com vocês! Mas precisam entender que não tem o que a gente possa fazer agora. 

*nunca tem*

Ei, viu, deixa eu te perguntar, você já tentou ir numa benzedeira? Fiquei sabendo que cirurgia espiritual faz milagre, e naquelas igrejas que os pastores fazem as pessoas voltarem a andar? Talvez seja melhor procurar outro médico, porque a prima da minha vizinha também precisava de muletas, mas foi em um médico excelente que consertou ela rapidinho, depois se você quiser eu tento conseguir o contato. Reza para Deus, que eu tenho certeza que ele vai te curar.

*ah, claro, valeu.*

Espero ter ajudado, qualquer coisa tamo aí para o que precisarem.

Inclusão é muito importante para todos nós aqui.





<a href="https://instagram.com/pahsantiago"><i class="bi bi-instagram"></i></a>
