---
title: 'Tia Auxiliadora Responde'
author: 
  - name: "Anônimo"
---

*“Querida Tia Auxiliadora, eu estou interessada em um cara do trabalho já tem uns meses, mas não sei mais o que fazer para que ele me chame para sair. Eu sempre puxo assunto, dou um jeito de ficar próxima e mais de uma vez comentei que estou solteira ou que me animo em sair depois do trabalho para comer ou beber uns drinks. Mas até agora nada, ele me responde sempre educado e sorrindo, mas fora isso nunca fala comigo. Por favor, me ajuda! A.: Trabalhadora Desesperada por Amor.”*

Ih, hoje já começou com sofrimento amoroso, gente ignorada é um horror, ou estão sempre se lamentando, ou não têm noção da falta de interesse do outro. Se bem que eu poderia ser um pouco mais compreensiva, afinal, só a vida sabe quantas vezes eu mesma não tive um amor não correspondido. Só me resta tentar ajudar essa pobre coitada, foi por isso que eu criei esse espaço. 

“Ah, Trabalhadora Desesperada por Amor, se depois de meses praticamente se jogando para cima do queridão, ele não tá te dando bola, sinto dizer que só lhe resta o título do filme que desesperou milhares de mulheres solteiras nos primórdios dos anos dois mil, Ele Não Está Tão a Fim de Você. Mas vou te dar um passe livre, que você pode ser dessa tal de geração z, que ainda tem muito a aprender, então deixa a tia ensinar. 

Desesperada, desculpa, Trabalhadora, a verdade é que, mesmo depois de todo esse seu investimento, se ele só fala com você para te responder e não demonstra nenhum outro interesse, ou ele é sonso, ou ele é burro. Então passa para outro, de preferência fora do trabalho, nunca ouviu dizer que onde se ganha o pão não se come a carne? Deus me livre uma reclamação no RH por assédio, concorda? Mas faz assim, continua com o crush a distância, que trabalhar é pior que morrer e um crush ajuda no incentivo.”

Ê laiá, quando vejo o próximo pedido de conselho, noto uma temática comum, mais um mal-amado, sofrendo com a indiferença que pelo menos uma vez na vida atinge a todos nós. Mas a gente sempre se recupera, o ego ou orgulho que todo o ser humano tem, pelo menos um pouco, sempre age na nossa crença de que temos direito a atenção e amor. 

*“Tia Auxiliadora, acho que tem algo de errado com a minha esposa. Ela só reclamava, sempre enchendo o saco, eu não podia pedir nada, fazer nenhum tipo de brincadeira. Agora ela não se importa com mais nada do que eu falo, tento conseguir uma reação dela de qualquer jeito, faço piadinhas e tento irritar ela, mas percebo que ela só finge o menor dos interesses no que eu digo ou no que faço. Como conserto ela? At.te., Marido Ignorado.”*

“Digníssimo Marido Ignorado, ou melhor, Futuro Divorciado, enquanto você fica se perguntando se tem algo de errado, o Brasil inteiro já tem certeza que ela não te ama mais. Afinal, é uma verdade universalmente conhecida que uma esposa, quando é constantemente ignorada, irritada pelo bel prazer do seu marido e passa a ser completamente indiferente a este, chegou ao seu limite e, não te ama mais.

Por isso meu conselho é: aceite esta realidade e para ser bem-sucedido na sua futura vida amorosa, pense em tudo que fez e faça o contrário, porque não tenho dúvidas de que o problema é você. E a realidade, pro pessoal que também tá lendo aqui, é que o amor às vezes acaba, sem muitos motivos e explicações, o relacionamento se desgasta e os dois deixam de se encaixar juntos, nem sempre dá para consertar algo quebrado... Boa sorte no divórcio!”.

Porra, será que fui muito grosseira? Nem sei se é isso mesmo que aconteceu, mas pô, em pleno 2024, com tanto post de Instagram e TikTok ensinando a ser um bom marido, ele ainda quer tratar a mulher assim e esperar que ela viva para lhe agradar. Espero que o divórvio venha mesmo. 

Ah, lá, mais uma ignorada, mas, pera, essa é diferente, essa pega no coração, como pode…

*“Não sei mais o que fazer, tia Auxiliadora, não importa o que eu faça para lhe agradar, o meu pai nunca me trata do mesmo jeito que os meus irmãos. Muitas vezes é como se eu fosse invisível dentro da minha própria casa…*
