---
title: 'Isso não é uma autoficção'
author: 
  - name: "Anônimo"
---

Querida,

Estávamos na escada. Eu do lado esquerdo, você do direito. Ou talvez ao contrário, não importa muito. Meu olhar se direcionava ao seu rosto, se esforçando para captar cada linha da sua testa e cada manchinha do seu queixo. Tinha medo de que você se esvaísse do meu cérebro ao longo dos meses. Queria te gravar. Os seus cílios são ridiculamente grandes. Quando você fecha os olhos, parece uma boneca de porcelana, daquelas que eu tanto admirava na vitrine das lojas. Lembro que fiz minha mãe comprar uma, com a promessa de que finalmente dormiria de luz apagada. Quebrei o compromisso na segunda semana. Quando acordava antes de você, com os raios da manhã invadindo o cubículo que nos confinava, ficava admirando os seus cílios. A forma como eles se encaixavam perfeitamente na sua face.

Pensava obsessivamente no quão cinematográfica era a cena. A escadinha apertada do prédio residencial-comercial de Ipanema agora estava tendo espaço para receber o término do casal lésbico que nem casal era. A escada se encaixou à gente e eu só queria me encaixar para você. Na negação, encontrei espaço para afirmar. Eu não gosto de você. Eu não quero namorar com você. Eu não estou perdidamente apaixonada por você. Esperava não te perder. Ir ao encontro das suas não expectativas. Aquilo daria um ótimo filme. Espera aí, pra eu pegar uma câmera e documentar a nossa última discussão? Ou ao menos tirar uma foto, naquele plano estreito da escada. Nós temos uma cena de obra francesa independente. Não se encontra isso todo dia em Ipanema. Negação-afirmação.

A cada palavra enunciada pela sua boca bem definida, também de boneca de porcelana, sentia a nossa relação indo embora. Pior, entendia que, para você, aquilo nem uma relação era. Estava desesperada. Procurava garantias de que seu corpo, seus dedos, as nossas conversas aleatórias pré e pós-sexo fossem esperar o meu retorno. Não era para aquilo estar acontecendo. Nossa história era cinematográfica, digna dos filmes de romance da sessão da tarde. Modéstia à parte, eu checava alguns requisitos para ser uma boa namorada. Sei que isso é problemático. Mas você sabe que eu checava.

Os sinais estavam ali. Você nunca me chamou pelo nome. Eu sei disso porque sempre fiz questão de pronunciar cada sílaba do seu. Nem apelido fofo eu tinha. Eu era o “mano”. A escolha consciente de ignorar esses sinais vinha da escolha consciente de ignorar todos os problemas da minha vida nas minhas transas com você. Você constituía o bucolismo da minha Arcádia. Agora que você estava indo embora, ficaria sem nada, sem nenhuma fuga para continuar não entendo os emaranhados do meu cérebro. Eu queria que aquela escada absorvesse meu corpo. E absorveu. Ao menos parcialmente. A parte que me fazia querer evitar o espelho. A parte que tinha medo do próprio reflexo e faria qualquer coisa para evitá-lo. A parte que não se sente preparada para conduzir o próprio carro e não entende porque caralhos a deram uma CNH sem exame prévio. Para você, eu me vesti. Mas, na viagem de volta, fiquei nua para mim mesma.

Atenciosamente,

Não Importa

