---
title: 'Minitratado sobre falsidade: um ensaio mal elaborado'
author:
- name: Anônimo
categories:
- ENSAIO

---

Vi por acaso uma chamada para esta revista. A temática da edição é falsidade e… O que há para se falar a respeito de *falsidade*?

Podemos começar com um fato: há um pouco no coração de cada um.
Para onde ir agora? Não sei. O que há para se falar a respeito de falsidade quando as nove horas de trabalho não me deixam direito pensar?

No trabalho tem falsidade. Na família e até no círculo de amizades mais próximo existem trocas de falsidade.

O que posso afirmar é: há um pouco no coração de cada um. A falsidade está por todo canto. Preenche cada célula que pede por socialização, afinal, é assim que se firmam laços humanos, não é?

Por onde vou escuto sempre fofocas, trocas de informações inúteis a respeito dos erros e escândalos pessoais dos colegas, além de alfinetadas que é preciso sempre estar desviando o tronco porque podem te pegar — e quando te pegam… *Aí… Dolorido demais arrancar a farpa*.

Mas, e quando a fofoca é um verdadeiro aviso? Quando dizem “cuidado!” ou “aquele ali já fez aquilo…”, como reage depois disso?

Onde começa e termina a falsidade?

O primeiro dicionário de termos que o Google oferece para entendermos o significado de *falsidade* nos aparece como

:::{.right-push}

| **falsidade**
| substantivo feminino
1. qualidade do que é falso; característica do que é contrário à verdade ou que dela se aproxima apenas na aparência. "é clara a f. do documento"
2. o que é falso ou enganoso; mentira, calúnia. "suas alegações são pura f."

:::

Os sinônimos de falsidade nos aparecem como “fingimento”, “fita”, “hipocrisia”, “mentira” e outras muitas palavras que carregam o mesmo valor semântico que aquela. O que todas apresentam em comum é justamente essa ideia de ser algo enganoso.

Vivemos no “mundo das aparências” se tem algo que nos será comum é a aparição de pessoas, situações, interações, que são completamente enganosas pois nos são apenas aparência, nada mais.

Como conhecer algo quando tudo o que sabemos sobre é o que nos chega somente através da
*visão*?

Pensei em começar a falar sobre balé. Queria ser bailarino. Mas nunca nem pisei numa escola
de balé porque mamãe viu em mim um menino e nunca pensou que balé fosse coisa de menino, afinal, nesse *mundo de aparências* meninos não se mostram dançando balé. Quantas
oportunidades de moços bailarinos o mundo deixou de conhecer?

Essa coisa *pura* que é a dança. Por que se contaminou com a falsidade ideológica da nossa sociedade? Por que isto é falsidade, né? Mentir para a gente, dizer que isto é de menina, não de menino! Que jogar bola, ter agilidade com o pé com uma bola na ponta é coisa de corpo de
menino. Se quer se mexer, tendo um pinto entre as pernas, vá jogar bola! Sem esse papo de graciosamente levantar salto, fazer plié e rodopiar.

Quando penso em *falsidade* tento resgatar o que me vem na cabeça. Quais momentos de falsidade já vivi? Com quem já fui falso e quem já foi falso comigo? A primeira entidade que
mentiu para mim foi minha própria família quando me disse que sou menino. A segunda entidade foi a sociedade que, através da minha família também, me diz que não posso aprender balé, sonhar alto, querer ser um grande e reconhecido escritor.

A terceira mentira da minha vida é que existe algo como *ser escritor, ser artista, fazer arte e escrever para revista*. Nada disso existe. Tudo é mentira. Tudo tem viés ideológico. Mas é isso. Nem tudo que carrega em si falsidade é digno do meu desprezo. Quando a gente se maravilha com o falso tem outro nome: encanto, fantasia.

Penso sobre a *falsidade*, uma palavra carregada de juízo de valor negativo. Mas penso também sobre o *encantamento*, uma palavra carregada de um juízo místico de valor — que
pode cair pro positivo e pro negativo…

O que é *falsidade*? É a máscara, a covardia, mas também aquela tentativa de dissociar para
alcançar o belo.

