---
title: O Grande Ego
author:
- name: Diego Rodrigues
categories:
- CONTO

---

Sábado, 7h.

Ele acorda e, começando sua rotina, segue para o banho e logo se admira na frente do espelho. Com seu cabelo castanho jogado para trás, escova seus dentes claros e os confere com um sorriso forçado. Os olhos cor de âmbar se penetravam, sua pele tinha uma textura suave e seu corpo era magro e estruturado. "Rum..", solta ele com um leve sorriso de canto, e com a toalha ainda na cintura vai para a cozinha. Pega uma chaleira e a enche com a água da torneira, e, lá fora, pela janela, vislumbra seu carvalho branco. Com o café sendo coado, ele segue para sua omelete com tomate. Ao sentar à mesa percebe uma água sanitária na ponta, pequeno deslize. "Tanto faz".
Sente a luz do sol entre os galhos de sua árvore vinda da janela e levanta. Lavando a louça, novamente sua visão buscava o lado de fora. A rua com casas sem muros, vizinhos em seus passeios matinais com filhos e pets, todos que passavam admiravam a grande *Quercus* Alba, possivelmente com dez metros de altura, enraizada na grama verde, com galhos firmes e um tronco forte. Ele mesmo a plantara na infância, e hoje morando sozinho era tudo que tinha. Hoje ela se encontrava perfeitamente cuidada, com suas folhas verdes já brilhantes com o sol nascente, sua sombra cobria todo seu quintal e invadia parte da rua, onde havia algumas pessoas se aproveitando e admirando a magnitude da árvore. E mais um sorriso de canto sai de seu rosto.

Sábado, 12h30.

Terminados os afazeres da casa, vinha-lhe o melhor momento do dia. Vestido como uma pessoa normal da sua idade, ele pega suas ferramentas e segue para o jardim. Começa jogando as folhas caídas para próximo das raízes. "Bela árvore" alguém soltou na rua. Com um sorriso simpático, ele agradece. "Cuido dela todos os dias, é o segredo", expressa encarando a árvore do outro lado da rua cujo dono ele conhecia: estava menos verde naquela manhã. "A minha deve estar doente, tem ficado meio seca e fraca". "Sim, sim. Pude notar isso, andei regando pra você, mas deveria ter mais tempo com ela". O sorriso já não estava ali... O vizinho se fecha culpado, despede-se com um abaixo de cabeça sem graça e segue para sua casa.
Hora da grama. Ele a apara com uma pequena enxada, e novamente ouve alguém. "Que árvore incrível você cultiva aí", elogia uma mulher qualquer da rua. "Sempre procurei por sementes para cultivar uma em casa, mas nunca encontrei". Um gelo lhe vem ao peito, como se uma lasca de madeira fosse tirada de sua árvore para conservar um vinho barato. "Tente no inverno, mas não posso lhe garantir sucesso", profere dessa vez com um olhar mais calmo, animado e cativante, contornando o desconforto que tomara seu corpo por um segundo. Ele finaliza, e com um último aceno aos curiosos da rua volta para casa satisfeito com o resultado de uma vida. Na cozinha, organiza seus equipamentos, jogando a garrafa vazia sobre a mesa fora, e vislumbra uma última vez pela janela a grandiosidade do carvalho.

Sábado, 21h00.

Deitado, ele se tranquiliza em seu momento sozinho. Pode ser cansativo cativar pessoas, mas o trabalho vem sendo perfeitamente concluído. Repassa os cuidados com seu jardim, reelabora um contato calculado para manter seu trabalho impecável perante os vizinhos e pessoas que erraticamente passavam por ali. Imaginando cada árvore da vizinhança, orgulha-se de como todos seus planos foram perfeitamente aplicados, preparando-se para o início da sua rotina semanal. Atenta-se em como erradicar todos os pequenos detalhes que possam tirar o foco do que realmente lhe importava. Afinal, uma próxima árvore poderia ofuscar o grande carvalho branco em seu jardim.

:::{.right}
-D.
:::

<a href="https://instagram.com/digsrodrigues"><i class="bi bi-instagram"></i></a>
