---
title: Transformação Merecida
author:
- name: Gustavo Henne
categories:
- CONTO

---

Quando Gregório Souza acordou, certa manhã, de um sonho inquieto, ele se descobriu transformado em algo que para ele sempre foi inadmissível: um despossuído. Despossuído era a classe mais inferior. Inferior não somente em relação aos grandes, mas aos pequenos, aos pequeniníssimos. Alguns os chamavam de invisíveis, outros não os chamavam, pois não existiam na prática. Afinal, se não possuíam nada, nada eram.

Foi há tempos que os merecidos declararam que a sociedade deveria sim ser separada em classes bem-definidas, cada qual teria seu papel, seus deveres e seus direitos. Porém eles mesmos disseram que não seria nada de novo, pois sempre foi assim, mas agora seria oficializado e considerava melhor as atuais dinâmicas sociais, não sendo uma divisão binária e obsoleta. Porém havia tantas classes que as más línguas dizem que muitos não conseguiam entender a qual realmente pertenceriam, alegando que eram uma ou duas classes apenas. Diziam “nós e eles”, mas eram apenas subversivos, uns párias.

Gregório fazia parte de uma classe amplamente respeitada, principalmente por quem estava abaixo, que não eram poucos. Seu pai era advogado, seu avô advogado, seu tataravô advogado… Ele era empresário, pois lhe ocorreu que seria mais vantajoso. No começo, seus pais rejeitaram a ideia, porém essa transformação seria bem-vinda, já que ele poderia, por exemplo, contratar advogados. Havendo também já o capital inicial, conquistado com muito mérito e suor pela família, ele conseguiu abrir sua empresa: uma agência de estimulação
empreendedora. Ele seria, assim, um estimulador, o que era muito respeitado. 

Até então, a agência era muito bem-conceituada, contratando muitos nomes relevantes da área, conquistando muitos novos empreendedores para diversas áreas, padarias, açougues, fazendas etc. O conselho era sempre o mesmo, Gregório dizia sem bocejar: “não durma, trabalhe”. Os merecidos achavam isso digno de reverência, ainda mais conhecendo a trajetória inspiradora de Gregório. Afinal, construir uma empresa como essa era garantido somente diante de muito mérito, não? Então, o que Gregório poderia ter feito para deixar de ser um estimulador, uma classe tão relevante, pela qual fez tanto?

Isso não era relevante, tampouco deveria ser revelado, era segredo que cabia apenas aos que decidem os méritos individuais de cada um decidir, os merecidos. É natural, como se a própria natureza discutisse isso, mas, claro, trajada a rigor: de terno e gravata.

Gregório levantou de onde estava, que, aliás, era um lugar aonde nunca tinha ido, pelo menos não fisicamente, já que seus vídeos tão inspiradores eram sempre referenciados por lá. Ele levantou, finalmente, saiu de lá em busca da casa de seus pais. Há uma estação perto, mas ele não tem posses para conseguir usá-las, então vai andando. Horas depois, ele chega em sua casa, seu berço eterno… Ele precisava dormir, nunca esteve tão cansado, não consegue nem pensar.

Ele assobia como sempre para que alguém abra a porta. Ninguém abre, mas ele consegue ver as luzes sendo apagadas, o que achou rude, deve ser coisa de empregado preguiçoso. Não se importa com isso. Gregório vai aos fundos, tenta abrir o portão com sua digital, mas é negado. Não, não pode ser. Com sangue nos olhos, Gregório, com muito esforço, pula o muro, ele sabe que seus pais vão estar na sala, quase dormindo. Dito e feito.

| – Pai, por que estou sendo negado?
| Seu pai não o olha, continua rindo e assistindo à TV. Sua mãe o despreza:
| – Você não é ninguém, não merece estar aqui, não merece nada.
| – O que eu fiz?
| – Nada que preste.
| – Falsos! – gritou; um empregado fecha a cortina.

A polícia chega e o prende, sem dizer nada também, pois ele não merece mais ouvir a voz humana. Seus pais nem olham para trás. Ninguém nunca mais lhe dirige a palavra, a não ser para bater o martelo e escapar um “culpado por…”. Aos curiosos, dizem as más línguas que ele teria transado com a esposa de um merecido durante uma festa em um iate. Gregório Souza teria dito que foi um sonho.

<a href="https://instagram.com/gutohenne"><i class="bi bi-instagram"></i></a>
