---
title: 'Meditação'
author: 
  - name: "Rafael Mendes de Barros"
categories:
- POEMA
---

| Deus: já, se é vencer nesta vida vã
| preso ao orgulho grão necessário preço
| e em arrogância mor me verter o afã…
| — Sei, não mereço
| 
| tal legado, e o preço não pago ter;
| e ainda que eu tão bem fatigado pela
| solidão, me fosse, a tentar viver,
| bem sem sorvê-la,
| 
| uma vida, então, já abnegada, voto-lhe
| minha oferta ao altar para que me traga 
| teu alento sobre, qual dor porquê 
| não se viu, chaga 
| 
| que se houvera, sim, só no amor pudera
| dar-se à cura e a mesma amizade, enfim,
| frente a monstruosa e malsã Quimera,
| pôr-lhe o seu fim;
| 
| pois aquele que hoje se nega ao afeto 
| teu pendor, talvez até tarda em ter
| prova do amargor, o sabor discreto 
| que a soberber
| 
| vosso ser, o rouba; de Exu se sabe:
| — Quão lhe dá em graça tão para o humilde,
| tão pra o afortunado o que qual lhe cabe…
| Nisso, Matilde,
| 
| fica o adágio meu para ti: — Chibata,
| bate, embata e tanto castiga no ermo
| ou em mansão, paupérrimo ou rico mata,
| pune o soberbo;
| 
| pensas que sem pé nem cabeça digo
| tudo o que te digo? Vês, Iemanjá,
| Pomba-gira pregam-nos peças, e ido,
| pensa, quiçá:
| 
| — Já gozemos, em ora, no beijo ou abraços,
| — foge a mocidade, e esvai, que é ligeira —
| perto está tristeza que em lida, aos laços,
| faz-se certeira.

<a href="https://instagram.com/rafael.mendes_10"><i class="bi bi-instagram"></i></a>
