---
title: A mosca
author:
- name: Arhon
categories:
- CONTO

---

Eu sou. Quando se acorda, certo dia, bifásica, quase que inteiramente pertencente ao outro mundo — na dubiedade do véu que se fia perante o medo: do não se pertence, não se faz. Do que se queima, não obstante, fraco, no amanhecer da eternidade.

Sentada, pairando no sofá da sala, quente e úmida, sentindo ventar-se enquanto se levava embora dali. Por mais que sonho ou mentira fosse, atirava-se em êxtase da janela: ah, que agouro; a infindável vontade de desfalecer-se em murmúrios. Enfim, acabada! Ao chão já não seria Ruth. Ossos, pele, sangue. Tornar-se-ia outra de ar, de alma, de vida. Pregressa, havia sido o que se há de saber. Imensa e inventiva. N’um quase-quase de amor, tentava moldar o mundo. Pensava que, que, que... sem nem viver, nem historiar. Estática. No plano, tudo era vida, ao dobrar-se dúbia sobre o que será.

Ambulava em despropósito monumental, pé ante pé, varrendo os cômodos com olhos baixos. Pr’onde haviam ido os outros? Corria em si, sem sair do lugar.

Amava sem fim um eterno entre. O chá de hibisco arroxeava-se à sua frente. Ela pedia mais infusão, mais cor, mais vida. Que respirem!

Lá fora um pássaro, que quentura, Meu Deus! e já é março. Sentia em si uma lágrima, ontem ainda era junho. Tudo passaria correndo assim o tempo todo...? e ela se esticaria para caber no mundo. Até que.

Uma criança à porta, em plenitude infantil, tocava a campainha, hoje não, não quero! Obrigada. Em cabeça, lhes dizia-lhes, estava morta! Precipitou-se a caminho da morte e foi-se. Soube penosamente disso quando tocou o couro branquíssimo da poltrona. Estava quente-ferve do sol que ali ladrilhava: naqu’Ele exato ponto. Soube que havia morrido e que já não mais se veria pálida e anestesiada frente ao espelho. E tudo isso, meu Deus, que tenho vivido... vivi mesmo?

Penetrava a pele — pelos, gordura, tudo! O calor se estreitava pelo chão de taco e se deitava cansado, pálido, efervescente.

E eu, então, me morri?

Viu, de lampejo rubro, secreto, o que se passava.

Dormia forte, de raiz severa, eternamente cansada. Ninguém a salvaria do sono eterno do ócio. Ao ter-se-ido, esperava... esperava... vinha vindo um de repente, aparentemente infeliz, mas que felicidade seria ser tirada daquilo. E de súbito: uma mosca! Exatamente aquela da qual se pensava. Sólida, saída já de um terceiro plano astral — vistosa, majéstica, vagando pela sala bolorenta. Estava. E simplesmente assim, por estar a trouxe de volta à realidade. A mosca bicho-vivo foi, por si só, o contato supremo: a felicidade dignificante do viver atada e entorpecida numa realidade planificada. Adormeceu infantil, sonhando em deixar de ser. Quando finalmente acordou, já não era mais.

