---
title: "Astros"
author: 
  - name: "Rodrigo Adriano Machado"
---

| Não sei se é pior não saber nada sobre Martinha ou estar apaixonada por outra mulher: Sônia. Fico pensando nas duas. Não deveríamos nos preocupar com ex, mas a carne é fraca quando envolve outras carnes boas. Falando nisso, estou com fome.
| — Claudette, você está indo para a estação de metrô? Posso ir com você?
| Não havia como disfarçar o trajeto. O jeito era aturar Tico, o estilo classe média simulado pobre, seu papo furado de militante fingindo que não estava dando em cima de mim. Nessas horas me escondo em um canto escuro da minha consciência como se fosse uma terceira pessoa passiva em uma conversa.
| — Quer que eu carregue sua mochila?
| — Não está pesada, tudo bem.
| — Essa nossa vida de proletariado que estuda é cansativa, não é?
| Aceno positivamente com a cabeça. Lá no canto da minha mente está a imagem dela sorrindo para mim. Sorriso de dentes grandes, cabelo black power, olhos castanhos, aqueles lábios grossos, queria tudo... Como será a voz dela?
| — Você vai fazer alguma coisa sexta-feira depois da aula? A galera vai se reunir em um barzinho para discutir política…
| Antes de terminar com Martinha eu já estava investigando aquela garota bonita nas redes sociais. Bem, não tinha como prever que Martinha estaria transando com um tatuador: agora não consigo mais olhar para o corpo dela. Digo, consigo mas não gosto.
| — Eu sou de libra e você?
| — Do que você está falando?
| Meu estômago revira, coloco a mão na boca.
| — Meu signo. Eu sou de libra com ascendente em capric… 
| Vomito. Ele tenta me segurar e empurro-o para longe.
| — Você está bem?
| — ESTOU ÓTIMA, NÃO ESTÁ VENDO?

<div style="display: flex; justify-content: center;"> 
*
</div>

| Sentada na lanchonete perto de casa fico olhando a rua. O lado bom de Martinha ter ido procurar a mãe é que deu tempo para nos afastarmos. Tenho a impressão de que todo mundo que conheço tem uma família ferrada. Meu pai, por exemplo, me deixou de herança esses olhos verdes. Não sei como meu pai é e não me interessa. As pessoas elogiam meus olhos sem saber que me ofende, enfim. 
| Enquanto termino meu lanche, entro na internet para vasculhar minha musa. Me falta coragem para puxar assunto, comentar nas suas fotos. Pesquiso o nome dela e não encontro nada. Sou a sede de álcool agora, mas ainda é quarta-feira e preciso trabalhar amanhã cedo.
| — Estamos fechando, quer mais alguma coisa? – Pergunta o garçom.
| — Não. A conta, por favor.


<div style="display: flex; justify-content: center;"> 
*
</div>

| Tomo banho e deito nua na cama.
| Descobri isso quando um cara tentou me impressionar em um encontro. Ele começou a me contar o enredo de um romance e imediatamente bocejei. É claro que a princípio achei que o problema era fulano, dias após o encontro fiz o teste comprando o livro em uma banca de jornais. Uma das poucas felizes coincidências na vida. Foi uma década lutando contra a insônia — exercícios físicos, dieta sem cafeína, meditação, etc. —, até que me tornei leitora de Clarice Lispector. Xingo quem falar mal dela perto de mim. Nunca soube o conteúdo da segunda página, mas já sonhei sobre. Boa noite.

<div style="display: flex; justify-content: center;"> 
*
</div>

| Saio do trabalho para enfrentar a enorme fila do supermercado. No começo estou distraída e subitamente sinto novamente um forte enjoo. A voz das pessoas na minha frente surgem como resmungos até que as palavras começam a fazer sentido.
| — Acho que mês que vem terei mais sorte. — Diz um barbudo.
| — Ah, sim, a lua estará ao seu favor. — Responde uma garota de cabelos vermelhos.
| Largo minhas compras no chão e saio correndo. Acho que estou precisando visitar uma psicóloga. Desta vez o nojo não me fez vomitar, mas foi por pouco.
| No metrô, lotado, começo a ler um pôster para me distrair. Creio que ninguém
| presta realmente atenção nessas coisas. Incrível como se gasta dinheiro com esses anúncios cafonas. Reconheço, em uma foto, o sorriso e o cabelo black power: é ela! Meu coração dispara. Então ela é modelo? Nos últimos meses passei por esse mesmo lugar quase todos os dias e fiquei parada exatamente aqui.
| Pego o celular e encontro a conta dela na rede social. Leio que se trata do metrô Vila Sônia. Sônia!


> Rodrigo Adriano Machado, mestre em Filosofia (PUC-SP), escritor com alguns prêmios literários, guitarrista e vocalista no projeto Os Belos Cães Cantores. 

| \@reles.escritor <a href="https://instagram.com/reles.escritor"><i class="bi bi-instagram"></i></a>
| \@rodrigoadrianomachado <a href="https://instagram.com/rodrigoadrianomachado"><i class="bi bi-instagram"></i></a>
| \@osbeloscaescantores <a href="https://instagram.com/osbeloscaescantores"><i class="bi bi-instagram"></i></a>