---
title: 'Companion of disquiet'
author: 
  - name: "Clara Maas"
---

| There’s a parasite eating away at my skin. I haven’t given it a name yet. 
| Perhaps it shouldn’t be something too presumptuous. Sharing my own might do, for now.
| I wouldn’t want it to be lonely in this poor destiny, mangled in my entrails. And if it only had it been by tragedy, and not a choice of one’s own. How horrid it must be, to be partaking away in all these parts of me. But I suppose it couldn’t have known it then, when it slid away through my skin, between my bones and under my fingernails. 
| Could be only a matter of seconds, before it also learns to be disgusted by me, as it is often one of those gullible cases to see something stood as towering as a Titan and beg to be a pebble beneath its foot. 
| It eats what I eat and that can’t be too reliable. I’ve been guilty of building a gluttonous monster once, can I be blamed for doing it twice? 
| Perhaps if I keep on feeding it, abandoning me will no longer be an option. 
| I used to be frightened by hate, but now devotion worries me more.

<a href="https://instagram.com/clara_maas_"><i class="bi bi-instagram"></i></a>