---
title: Michel Foucault e o enigma nietzscheano
author:
- name: Rodrigo Adriano Machado
categories:
- ENSAIO

---

Parte 1

Há momentos poéticos na Filosofia em que um pensador intempestivo trespassando --- e trespassado pelo --- seu contexto nos informa uma antevisão surpreendente. Nisso, nem sempre percebemos que nosso presente --- também chamado de Sociedade do cansaço [^1]--- teria profundos vínculos com o nojo enquanto sintoma moderno.

[^1]: HAN, Byung- Chul. Sociedade do cansaço --- Petrópolis, RJ: Vozes, 2017.

Na terceira parte do livro Assim falou Zaratustra --- texto célebre em que Nietzsche apresenta diagnósticos, críticas e alternativas à modernidade ---, o personagem principal nos conta um sonho.

Aqui resumo: Vi um jovem pastor contorcendo-se, sufocando, estremecendo, com o rosto deformado, e uma negra, pesada serpente que lhe saía da boca. Alguma vez vi tanto nojo e pálido horror em um rosto? Havia ele dormido? E a serpente rastejou para dentro de sua garganta --- e ali morde firmemente[^2].

[^2]: NIETZSCHE, Friederich. Assim falou Zaratustra: um livro para todos e para ninguém. --- São Paulo: Companhia das letras, 2011, p. 152.

O sonho é sugerido enquanto enigma. O tema sobre o que discorre o filósofo é de um grande cansaço. O que é sabido nas suspeitas do autor trata-se da modernidade enquanto ponto de encontro para pelo menos três feridas narcísicas da humanidade:1 - O planeta Terra não é o centro do universo (escândalo teológico/ geocêntrico); 2 - O humano não passa de mais um animal entre animais (escândalo antropocêntrico, biológico); 3 - O Eu racional, sujeito que inaugura a modernidade, é tão verdadeiro quanto qualquer ficção produzida ao longo da história (descoberta do inconsciente filosófico-psicanalítico).

Uma quarta ferida narcísica poderia ser proposta em bifurcação. 4 - O humano é um animal histórico, porém, não faz a história como bem quiser, e muito da nossa imagem de sujeitos enquanto consciência possui por base nossas relações econômicas: as ideologias não são mais do que máscara política e "religiosa" dessas relações.

Que não bastasse herdarmos essas feridas neste nosso caso humano, Nietzsche, no citado livro, analisará outro grande problema: a domesticação antropotécnica: "\[...\] Transformamos o lobo em cão, e o próprio homem, no melhor animal doméstico do homem"[^3]. No tom de uma filosofia poética, no transcorrer do texto, o filósofo finalmente nos dirá a interpretação do enigma do nojo: "O grande fastio pelo homem --- isso me sufocou \[...\]: Tudo é igual, nada vale a pena, o saber sufoca"[^4].

[^3]: Idem., Ibid., p. 162

[^4]: Idem., ibid., p. 210.

Aqui é o momento que gostaria de propor um desdobramento ou articulação, dada a problemática nietzscheana, em outro pensador. Pontualmente, Ailton Krenak, em livro recente, nos direciona para Michel Foucault. No capítulo O amanhã não está à venda do livro A vida não é útil (2020), Krenak lembrará que "Foucault tem uma obra fundamental, Vigiar e punir, na qual afirma que essa sociedade de mercado em que vivemos só considera o ser humano útil quando está produzindo"[^5]. A abertura que o pensamento de Foucault propicia na interpretação de Krenak --- inclusive um dos eixos centrais do livro que se deixa notar pelo título --- vai na direção do tema da Biopolítica, ou seja, a política sobre a vida: "Com o avanço do capitalismo, foram criados os instrumentos de deixar viver e fazer morrer: quando o indivíduo pára de produzir, passa a ser uma despesa"[^6]. Jamais para corrigir Krenak, mas justamente fazer par com sua interpretação, é importante irmos até a aula de Foucault sobre o nascimento da Biopolítica[^7] e ajustar esse detalhe citado: é um fazer viver e não um fazer morrer que implicará as consequências desta domesticação do homem que Nietzsche nos alertava na sua antevisão e Foucault, de seu modo, elaborará na perspectiva de uma tomada de poder sobre o homem-espécie e não o homem-corpo como fora nos regimes disciplinares. É a positividade da vida, a promoção da saúde e bem estar da população (cientificamente higienizada) acima de tudo, o lugar onde jamais desconfiávamos, que esse Biopoder penetrará sutilmente8.

[^5]: KRENAK, Ailton. A vida não é útil. --- São Paulo: Companhia das letras, 2020, p.87.

[^6]: Idem., Ibid., p. 87.

[^7]: Aula de 17 de março de 1976 presente no livro Em defesa da sociedade, p. 285-315. 8\"\[\...\] Com essa tecnologia do poder sobre a \'população\' enquanto tal, sobre o homem enquanto ser vivo, um poder contínuo, científico, que é o poder de \'fazer viver\'.\[\...\] Eis que agora aparece um poder que eu chamaria de regulamentação e que consiste, ao contrário, em fazer viver e em deixar morrer\" In: FOUCAULT, Michel. Em defesa da sociedade. --- São Paulo: Martins Fontes, 1999, p. 294.

Talvez, apenas como metáfora didática, poderíamos nos servir do jargão empreendedor de nossos tempos e dizer que é um modo de "otimizar o estado de vida": evidentemente uma vida capital, de preferência com a terapia em dia.

> Rodrigo Adriano Machado, mestre em Filosofia (PUC-SP), escritor com alguns prêmios literários, guitarrista e vocalista no projeto Os Belos Cães Cantores. 

| \@reles.escritor <a href="https://instagram.com/reles.escritor"><i class="bi bi-instagram"></i></a>
| \@rodrigoadrianomachado <a href="https://instagram.com/rodrigoadrianomachado"><i class="bi bi-instagram"></i></a>
| \@osbeloscaescantores <a href="https://instagram.com/osbeloscaescantores"><i class="bi bi-instagram"></i></a>
