---
title: 'Resenha: "Glicerídeos" de Junji Ito'
author:
- name: Vitor Baratinha
categories:
- RESENHA

---

Glicerídeos é um conto que faz parte do compilado  “Contos Esmagadores”, lançado no Brasil em 2023 pela editora Pipoca e Nanquim.

No conto, acompanhamos a protagonista Yui, uma adolescente que mora com seu pai e irmão em uma casa que fica acima de uma churrascaria da qual seu pai é dono, em uma cidade que fica nos entornos do Monte Fuji.

Por conta da má ventilação da churrascaria, toda oleosa e engordurada, a casa onde moram também acaba ficando com o ar todo engordurado. Essa situação faz com que Yui se torne sensível a toda gordura, chegando ao nível em que ela descobre que tem uma espécie de “poder” que faz com que ela consiga detectar e ver toda gordura ali no ar de sua casa.


Goro, o irmão de Yui, é um adolescente que pratica bullying com sua irmã, além de ter um hábito bizarríssimo de beber garrafas de óleo como se fossem refrigerante. A situação piora quando ele chega à puberdade e começa a desenvolver sérios problemas de acne por conta de toda gordura e óleo nos seus hábitos e espaço.

Toda tensão e frustrações de cada membro da família se misturam quando em uma das práticas de Bullying com sua irmã, Goro espreme suas espinhas na cara de sua irmã, fazendo com que o pai saia em defesa dela e mate o próprio filho por acidente. Após isso o pai decide usar da própria carne e corpo gorduroso do filho para servir de churrasco aos clientes do seu negócio.

O pai então volta seus olhares para a filha Yui, que agora não consegue nem dormir com medo de seu pai matá-la para pegar sua gordura e carne. 

Porém o conto acaba com Yui tendo um sonho do monte Fuji entrando em erupção com rios de gordura caindo dele, fazendo alusão a uma imensa espinha e assim a história tem seu “fim” meio abrupto fazendo esse grande clímax nojento.

Glicerídeos não é a obra mais profunda ou até mesmo assustadora que se tem dentro do gênero do horror, mas faz uso perfeito do sentimento de nojo para te deixar imerso e com horror de cada imagem de cada quadro. Até mesmo para o autor Junji Ito, que é considerado o mestre do mangá de horror, é uma de suas melhores utilizações de horror corporal.
Os quadros em que nos mostram as paredes, cobertores e a testa dos personagens, simplesmente cobertos por óleo e gordura, provam que isso pode ser tão aterrorizante e nojento quanto qualquer história de sangue ou temas paranormais.

A escrita de Ito, apesar de simples, abre espaço para o choque e apreciação do surrealismo das imagens e situações bizarras que são apresentadas. O uso criativo do sentimento de nojo e temática não convencional pode surpreender até aqueles que já estão acostumados com o gênero ou com outras obras do autor.

<a href="https://instagram.com/Obaratinha_"><i class="bi bi-instagram"></i></a>
