---
title: 'Com amor, a burguesia!'
author: 
  - name: "Giovanna Sabino"
---

Você leu nas notícias, caro leitor ? Leu o que elas contaram no jornal de ontem?

Faltaram-me as palavras para comentar enquanto folheava as páginas e precisei escrever-te.
A manchete dizia em letras decoradas: "Crise na economia: onda de suicídios de trabalhadores causa queda de bolsa de valores e economistas já não sabem o quanto isso afetará o PIB no fim do ano."

Os trabalhadores, coitados, desistiram. Não havendo mais a quem gritar por direitos, visto que o eco era incontornável, não havendo mais quem mandar ao congresso e não havendo mais burocracia pacífica que o salvasse da sua iminente morte por exaustão ou humilhação nas mãos de um rico qualquer, o trabalhador libertou-se. Decidiu sobre a única coisa que a burguesia ainda não havia tirado de si, sua própria vida.

O metrô parou, tantos eram os corpos nos trilhos, todos exaustos e famintos. Nas ruas não se andava, tantos eram os pedaços humanos, todos exaustos e famintos. Nas pontes já não havia mais espaços onde se pendurassem cordas. Todas as overdoses foram de álcool e droga barata, não havia dinheiro que pagasse mais.

Foi o que eu li no periódico da manhã ao menos, caro leitor. Algo a esse respeito deve ser feito, afinal, quem servirá nas ceias de fim de ano e nos restaurantes? 

Mas, passado esse assunto secundário, falemos do supérfluo que é o que nos preenche! Devo sair agora, entretanto tenho pilates, e os corpos na rua causaram um trânsito desgastante!

Com amor, a *burguesia*!

<a href="https://instagram.com/forlissies"><i class="bi bi-instagram"></i></a>
